DataBiosphere/terra-workspace-data-service

CODE_OF_CONDUCT.md

Taken from the broadinstitute github code of conduct; no one on Databiosphere seemed to have one.  Given that this repo is under Databiosphere, is it appropriate for the enforcement to refer to  http://broad.io/EthicsReporting?

AJ-468 add code of conduct

---

static/swagger/openapi-docs.yaml
static/swagger/swagger-ui.html

* in the HTML definition, fix the path to index.css
* in the OpenAPI definition, remove "(pending)" from the GET and PATCH apis because they are now implemented.

bugfixes for swagger ui [AJ-511]

---

README.md
build.gradle

This enables Spotless, but does NOT yet enable any auto-formatting of code (e.g. via `build.dependsOn spotlessApply`) nor any linting.
Putting this PR up to give a chance for folks to play with the formatting before we enable anything automatic! My recommendation for enabling Spotless is:
1.  merge this PR
2. merge any other nontrivial outstanding PRs
3. run `spotlessApply` and make a single PR that contains only the formatting changes plus turns on formatting enforcement

configure spotless [AJ-470]

---

service/src/main/resources/static/swagger/swagger-ui.html

When hosted in a leo app, the path to the swagger page becomes something like: 
- `https://leonardo.dsde-dev.broadinstitute.org/proxy/google/v1/apps/terra-dev-fc995c1b/terra-app-5503bfa7-b1d9-4140-973b-35e0b60e2f24/cromwell-service/wds/swagger/swagger-ui.html` 
and the associated resources are more like (for example): 
- `https://leonardo.dsde-dev.broadinstitute.org/proxy/google/v1/apps/terra-dev-fc995c1b/terra-app-5503bfa7-b1d9-4140-973b-35e0b60e2f24/cromwell-service/wds/webjars/swagger-ui-dist/favicon-32x32.png`
This change makes the references relative not absolute so that they are proxy-safe when loaded in an image deployed as a leo app

BW-1346: Make swagger's links relative not absolute

---

service/src/main/resources/static/swagger/openapi-docs.yaml

Changes the swagger server definition to be relative to the hosted swagger page.
- Swagger is hosted at `.../swagger/swagger-ui.html`
- APIs are hosted at `.../<API path>
Therefore the relative server path is `../` to escape the `swagger/` URL segment.

BW-1346: Update swagger UI to make calls to relative paths

---

build.gradle

Trying to find a better spotless config, this switches from [google-java-format](https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how) to the eclipse predefined format.
This PR *_only_*  changes build.gradle, it does not reformat any existing code. Because of this, `spotlessCheck` will fail on this PR - the current code formatting has spots that are not legal with eclipse format. I've done this so reviewers can pull this branch, run `./gradlew spotlessApply` locally, and see the changes.

switch google-java-format to eclipse format [AJ-470]

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/EntityController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/EntityDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RefUtils.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/EntityReference.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/EntityControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/EntityDaoTest.java

[AJ-496](https://broadworkbench.atlassian.net/browse/AJ-496)
Instead of using a map with "entityType" and "entityName" keys, have references be accepted as simply a string beginning with an identifier, with entityType and entityName separated by a /.
Question: Presumably this convention will need to be documented somewhere.  Should that go in the openapi-docs.yaml?  In the README?  Both?  Neither?

aj-496 replace reference map with string

---

service/build.gradle

We have the other sonarqube properties but this one got left out.

aj-556 add sonar.projectName property

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/Record.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordRequest.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordRequestTest.java

Removed the confusing duplication of id and type for PUT/PATCH.
Also renamed `Record.name` to `Record.id`, which caused some corresponding changes

remove duplicate id and type for PUT/PATCH single record [AJ-538]

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordColumn.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

I'm dividing AJ-528 into smaller PRs.  With this PR, I originally intended to start using named sql parameters since those are usually easier to look at and reason about, but unfortunately there are a number of [constraints](https://stackoverflow.com/questions/422369/are-there-any-illegal-characters-when-using-named-parameters-in-jdbc) that spring jdbc imposes on named sql parameters that led me to abandon that effort.  I think we may want to consider limiting what we allow for record type and column names sooner rather than later or at least evaluate whether the same level of naming flexibility that we offer in Rawls is required.  
Anyhow, what was left in this PR was then switching away from using LinkedHashMap as a parameter type for the RecordDao#batchUpsert() method.  It's not …

AJ-528: don't depend on LinkedHashMap to guarantee stable iteration, use a list instead

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

- In `RecordDao` Convert inline quoting of table and column names to method calls
- `RecordDao.getSingleRecord()` now returns an Optional
- PUT single record previously didn't include any nulled out attributes in its response payload (i.e. if PUT was used to update an existing record any existing attributes not included in the request payload would not show up in the PUT response body) This change should make the PUT response consistent with GET for the same Record, which seems correct to me, but let me know if I've misunderstood things.
- When creating a new record type, create foreign keys for references at table creation time.
- Sonar squawking about public test methods.

AJ-528: Add quoting function, Return Optional instead of null, Show All Attributes with PUT update path, New tables include FKs in create

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

[AJ-559 Inserting relation to non-existent record creates relation attribute](https://broadworkbench.atlassian.net/browse/AJ-559)
If creating relation fails due to the related table not existing, the column for that relation should not be created. Included the foreign key constraint when initially creating column so we can catch the sql error at the same time.
I ran `build` so there's a number of changes that are just whitespace, hopefully it's not too disruptive.

AJ-559 don't create column for invalid relation

---

README.md

Updates the README with a one-click link to view WDS' swagger definition.

add hosted swagger-ui link to readme [AJ-565]

---

README.md
service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/InvalidNameException.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java

I threw in a few small sonar fixes in addition to disallowing characters for record type names and attribute names.

AJ-567: Sanitize user input for table and column names to remediate SQL injection risk

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/SqlUtils.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RelationUtils.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/AttributeSchema.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/RecordTypeSchema.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/InvalidNameException.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/Record.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordType.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/SqlUtilsTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordResponseTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordTest.java

Highlights of this refactor:
* `RecordType` class is now immutable
* we perform validation in the RecordType constructor (starts with "sys_", is sql-legal)
* all methods that accept a record type as argument now accept RecordType instead of String, and we pass around RecordType instead of repeatedly transforming it to and from String
* we only translate RecordType to a String value where absolutely necessary, such as when using in a sql statement
* `toString` for RecordType now returns just the name value, making it easy to use a RecordType directly in url templates (such as inside unit tests)
There's a lot of lines of code that changed due to the pervasiveness of RecordType
After this PR merges, I'll make follow-on PRs:

RecordType wrapper class refactor

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RelationUtils.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/Record.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributes.java
service/src/test/java/org/databiosphere/workspacedataservice/DataTypeInfererTest.java
service/src/test/java/org/databiosphere/workspacedataservice/TestUtils.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

Philosophically, I am realizing that my motivations for refactoring classes like this are:
* where I'm less confident about the underlying representations - like using `Map<String, Object>` to represent attributes - I want to abstract callers from knowing about those representations
* providing domain objects that include some encapsulated logic, as opposed to pure record classes
---
Highlights of this PR:
1. Calling code is able to call methods directly on `Record` or `RecordAttributes`, instead of retrieving the underlying `Map` of attributes.
[Example](https://github.com/DataBiosphere/terra-workspace-data-service/pull/76/files#diff-6fdffee8355da583e8db9f8b0995789baa890a7fc0b2ba3da10e381f60afee25R284
), using `Record toInsert`:
```java …
```

RecordAttributes model [AJ-507]

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

[Aj-604 Blank relation value displays incomplete relation identifier](https://broadworkbench.atlassian.net/browse/AJ-604)
If a relation attribute is blank, it would show up as simply the terra relation identifier string without a recordId (`terra-wds:/recordType`:
This PR simply checks for null before adding the relation identifier:

aj-604 check for null relation

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/resources/static/swagger/openapi-docs.yaml

title.
This was tripping up CBAS integration because us humans were confused by it

AJ-611: don't require trailing slash for create-instance API

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java

Move the create-instance API to `/instances/{version}/{instanceId}`.
This works around a weird issue in Spring that causes `There was an unexpected error (type=Method Not Allowed, status=405). Request method 'GET' not supported.` errors

fix create-instance and swagger ui [AJ-619]

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/TsvSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/BatchDeleteException.java
service/src/main/resources/application.properties
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/SmallBatchWriteTestConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvDownloadTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/resources/batch_write_tsv_data.json

I've tested this with a record type larger than 1gb and confirmed that it works even on a 100mb heap.  Changes are in place to make sure we stream from db to java.sql.Resultset, from Resultset to intermediate domain object, and from domain object to http response.  I can share a large json file you can use as input to the batch write API if you'd like to test for yourself.

AJ-596: TSV Streaming Download

---

build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/SearchRequest.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/TestUtils.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java

[AJ-615](https://broadworkbench.atlassian.net/browse/AJ-615)
Allows sorting by a given attribute.  Naive implementation of however postgres interprets the sort.  Defaults to RECORD_ID if none given.

aj-615 paginated sort by column

---

service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java

* Datetime attributes now serialize to e.g. `2022-04-25T12:00:01`
* Date attributes now serialize to e.g. `2022-04-25`
* The `RecordAttributes` underlying `Map` now contains `LocalDate` and `LocalDateTime` values

dates and timestamps should be human-readable [AJ-620]

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java

follow-on to #81 : when calling the TSV endpoint, download the result as a file by setting `Content-Disposition: attachment`

AJ-596: download TSV as attachment

---

.github/workflows/publish.yml
.github/workflows/release-python-client.yaml

This PR will generate a python client and push it to PYPI.
The `python` yaml is called by the `publish` yaml so that it only occurs after the latest tag has been generated and uses that one.

Aj 628 python client

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java

there's some yak-shaving in here.
The ultimate goal is for the `createOrReplaceRecord` PUT single-record API to stop auto-creating instances if the supplied instanceId does not exist. That runtime change was pretty easy.
However, it caused some issues in unit tests. So I updated unit tests to create the relevant instance before each test ran. In `FullStackRecordControllerTest`, this ran into even more issues because the database is persistent, and each create-instance call past the first would fail with a 409 conflict.
So, I also added a delete-instance API (with a couple tests of its own and swagger doc). This isn't the only solution to the testing situation, but it felt like a beneficial addition for debugging and such. If reviewers think the delete-instance API is a bad idea, I can …

dont autocreate instance in put-record; add delete-instance API [AJ-614, AJ-674]

---

service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/resources/application.properties
service/src/test/java/org/databiosphere/workspacedataservice/controller/CorsLiveMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/CorsLocalMockMvcTest.java

When deployed behind Terra's Azure Relay, WDS's CORS responses and the Relay's CORS responses conflict with each other, resulting in CORS errors in the browser. Relay configuration [here](https://github.com/DataBiosphere/terra-azure-relay-listeners/blob/a9576c888e934d51ef9bad486aa69e8c2aa92e4a/service/src/main/java/org/broadinstitute/listener/relay/Utils.java#L34).
This PR changes WDS to _not_ issue CORS responses, unless WDS is running with the "local" Spring profile. That profile is not enabled by default, but engineers can toggle it on if they need to connect to a local WDS from a browser.

disable CORS headers for non-local development [AJ-696]

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/RecordTypeSchema.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/GeneratedClientTests.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/resources/logback-spring.xml

I ran GeneratedClientTests before updating swagger and they passed so I think this change won't break swagger clients.

AJ-728: Identify pk column in schema apis

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/AttributeComparator.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributes.java
service/src/test/java/org/databiosphere/workspacedataservice/TestUtils.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvDownloadTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributesTest.java

This PR adds the primary key to the attribute map in the JSON response.    I also took the liberty to add code to order the JSON attributes with PK first and all other attributes following in alphabetical order and to order the TSV columns by that same ordering scheme.  When I tested with terra UI, [this code](https://github.com/DataBiosphere/terra-ui/blob/7976a29f882b3814ff7d65a08cbfbcf949257ed0/src/components/data/DataTable.js#L154-L156) led to problems, my fix was to make those lists match on the server side and update the schema API to include the primary key column too as part of this PR.

AJ-726: Add Primary Key to JSON response

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java

Uploading a TSV that contains duplicate ids now yields an error message of "TSVs cannot contain duplicate primary key values."
Per refinement, scope of this ticket is to make the error message better. If we want to allow duplicate PKs in a TSV, we'll do that in a future PR/ticket.

better error message for TSVs that contain duplicate IDs [AJ-721]

---

build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

[AJ-754](https://broadworkbench.atlassian.net/browse/AJ-754)
This PR eliminates the error described below. If you upload an array of strings into a column that is a scalar string, your array of strings will be serialized into a scalar. For instance, if you upload `["array","of","strings"]` into a scalar column, you will end up with a scalar value `"{array,of,strings}"`.
I am not convinced this is the final behavior we want. However, I consider this PR as a strict improvement over throwing an error, so I suggest we merge it as-is while we debate what the functionality should be.
1. Create a new WDS instance
2. use the PUT single-record API to create a record with a single attribute whose value is a scalar string
3. use the PUT single-record API to replace that record, this time specifying …

AJ-754: Don't fail with a SQL Error when passing list data to a STRING attribute

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

[AJ-735: Delete arrays of relations](https://broadworkbench.atlassian.net/browse/AJ-735)
Deleting a record should remove the values from the relation-array table; deleting a record type should drop the join table altogether.
[AJ-735]: https://broadworkbench.atlassian.net/browse/AJ-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AJ-735]: https://broadworkbench.atlassian.net/browse/AJ-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Aj 735 delete array of relations

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordService.java
service/src/main/resources/application.properties

* bring in terra-common-lib (TCL) for its retryable-transaction annotations
* annotate most APIs with a transaction, right in `RecordController`
* annotate the streaming-write APIs at a lower level in `BatchWriteService`
* remove `@Transactional` from any other runtime code in deference to the TCL transactions
In a future PR I'd like to make the transactions less broad - for instance, don't include the http response itself inside the transaction - but this will require a fair bit of refactoring of `RecordController`. So for now, the transactions are wide and long

[AJ-767] transaction support 

---

service/build.gradle
service/src/main/java/bio/terra/common/README.md
service/src/main/java/bio/terra/common/db/DatabaseRetryUtils.java
service/src/main/java/bio/terra/common/db/ReadTransaction.java
service/src/main/java/bio/terra/common/db/WriteTransaction.java
service/src/main/java/bio/terra/common/retry/CompositeBackOffPolicy.java
service/src/main/java/bio/terra/common/retry/transaction/TransactionRetryInterceptorConfiguration.java
service/src/main/java/bio/terra/common/retry/transaction/TransactionRetryProperties.java
service/src/main/resources/application.properties

followup to #160 .
This PR removes https://github.com/DataBiosphere/terra-common-lib as a dependency, and copies (as source code) just the pieces of TCL we really need. Including TCL as a whole had undesirable side effects such as resetting logging config; we also had to intentionally disable some TCL features such as Liquibase. By copying just the pieces we need, we keep WDS slim and without unpredictable side effects.
The drawback is that the code copied in here will not benefit from TCL fixes/enhancements, if those ever happen. An ideal solution would be to fix/repackage TCL, but that's larger in scope than I'd like to tackle right now.

abandon terra-common-lib [AJ-767]

---

.github/workflows/publish-docker.yml

If there are multiple jira ids in a commit message - e.g. if there is one in the actual message AND in the branch name - the auto-push to cromwhelm will fail because the jira id output will have extraneous text.  This change will only look for the first match to a Jira Id.

AJ-719 update

---

service/src/main/resources/static/swagger/openapi-docs.yaml

A collection of swagger fixes:
* add `operationId`s for `/version` and `/status`; this eliminates two messages during compile.
* resolve all errors/warnings as reported by IntelliJ
Compilation warnings on this branch vs. main:

swagger cleanup

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/resources/application.properties
service/src/main/resources/logback-spring.xml
service/src/test/java/org/databiosphere/workspacedataservice/SentryInitializerTest.java

This PR configures [sentry-logback](https://docs.sentry.io/platforms/java/guides/logback/) in WDS. We create a new Sentry-specific logback appender, set some variables on the `Sentry` object, and then magically Sentry finds exceptions in our logs and sends them to the WDS-specific Sentry dashboard.
Using the logback approach for Sentry should make this fully compatible with [Application Insights instrumentation](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-spring-boot) when we add that in the future.
See the dashboard at https://sentry.io/organizations/broad-institute/projects/wds/?issuesType=all&project=4504299946835968.
The `samurl` and `lz_mrg` environment variables depend on https://github.com/broadinstitute/cromwhelm/pull/172 which in turn (partially) depends on …

Sentry via Logback [AJ-763]

---

.github/workflows/release-python-client.yml

We've seen sporadic failures in GHA when running `openapi-generator-cli version-manager set 4.3.1`. Let's try enabling the npm cache and see if that alleviates it. 
setup-node/npm cache documentation: https://github.com/actions/setup-node

AJ-808: enable npm cache

---

.github/workflows/release-python-client.yml

Reverts DataBiosphere/terra-workspace-data-service#167
That PR apparently isn't right; it causes job failures: https://github.com/DataBiosphere/terra-workspace-data-service/actions/runs/4000813358

Revert "AJ-808: enable npm cache"

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

new API to list all instances inside a given WDS service.
The UI troubleshooter can use this to determine if the default workspace instance exists.

AJ-675: list-instances API

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvDownloadTest.java

Before this PR, if you 1) download a TSV for a given table and then 2) attempt to delete the table, you hang.
The TSV download was leaving a stream unclosed, which I hypothesize was not properly releasing a db lock or a thread (or something!).
This PR ensures the stream is closed, and manual testing shows it addresses the issue.

AJ-836: ensure TSV download stream is closed

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordService.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/TestDao.java

See [AJ-734](https://broadworkbench.atlassian.net/browse/AJ-734)
Adds support to update array-of-relations attributes.  Current behavior fails on updating attribute datatype of relations, so this is reinforced with arrays of relations and given clearer messaging.
[AJ-734]: https://broadworkbench.atlassian.net/browse/AJ-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-734 Update arrays of relations

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/DataTypeMapping.java
service/src/main/resources/data.sql
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/DataTypeInfererTest.java
service/src/test/java/org/databiosphere/workspacedataservice/TestUtils.java

See [AJ-678](https://broadworkbench.atlassian.net/browse/AJ-678)
Adds a FILE type to record attribute data types.  Only recognizes azure storage container (https://[].blob.core.windows.net/[]) or drs (drs://[]) files.
[AJ-678]: https://broadworkbench.atlassian.net/browse/AJ-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-678 File datatype in WDS

---

service/src/main/resources/static/swagger/openapi-docs.yaml

See [AJ-845](https://broadworkbench.atlassian.net/browse/AJ-845) and [AJ-846](https://broadworkbench.atlassian.net/browse/AJ-846). 
Before both calls were returning "None", now they return objects. Generated the client locally and tested to make sure everything worked as expected. 
version: 
status: 
Tested for all datatypes and adjusted the casing and naming appropriately. It will likely make sense to generate tests for these, but that work fits better into defining what automated testing looks like for the client which is captured in [this ticket](https://broadworkbench.atlassian.net/browse/AJ-816). 
[AJ-845]: https://broadworkbench.atlassian.net/browse/AJ-845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AJ-846]: …

AJ-845 and AJ-846: Fix response types for /status and /version in swagger definitions, properly describe types

---

.github/workflows/publish-docker.yml

https://github.com/DataBiosphere/terra-workspace-data-service/pull/164 attempted to only grab the first jira id in a commit message if there was only one.  For some reason I thought it was working when apparently it was not.  Hopefully this time is correct.

[AJ-719] Update publish-docker.yml

---

.gitignore
service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/resources/applicationinsights.json

Relates to https://broadworkbench.atlassian.net/browse/AJ-764
Validated via a workspace within a BEE: https://terra.wds-only.bee.envs-terra.bio/#workspaces/wdsonlybillling/appInsightsTest
Then observing data incoming to https://portal.azure.com/#@broadinstitute.org/resource/subscriptions/0fa61a72-3a6b-4d51-a7e9-75fbeb7c7ed9/resourceGroups/mrg-terra-dev-previ-20230224115705/providers/Microsoft.Insights/components/lz9c9522004165f6249b4e9e9545c3de2f2a97220ea65e14ee345942cc7192f9f1/overview

AJ-678: Give WDS the ability to leverage Azure Application Insights

---

service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/ControllerConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/DataSourceConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInfererConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/service/JsonConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/tsv/TsvConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/DataTypeInfererTest.java
service/src/test/java/org/databiosphere/workspacedataservice/SentryInitializerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/SqlUtilsTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/HttpSamClientSupportTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/StreamingTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordRequestTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordResponseTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvDeserializerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvJsonEquivalenceTest.java

Using `@SpringBootTest` without any qualifiers in our unit tests meant that each unit test instantiated the full set of available `@Bean`s, including the two Hikari datasource connection pools.
Given the number of unit tests we have, this eventually consumed the max connections (default 100) allowed by Postgres, and tests would intermittently fail with `Failed to obtain JDBC Connection`. In #184 this error was very easy to make happen, though it happened inconsistently on different unit tests. Additionally, raising the `max_connections` flag on Postgres makes the error stop, but that's a band-aid solution.
In this PR:
* separate the `@Bean`-producing methods into a few different `*Config` classes : `DataSourceConfig`, `DataTypeInfererConfig`, etc. Previously these all lived in …

AJ-679: move @bean producers into separate classes

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/InstanceDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/SqlUtils.java
service/src/main/java/org/databiosphere/workspacedataservice/service/InstanceService.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockInstanceDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockInstanceDaoConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceNoPermissionSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamExceptionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java

In this PR:
* Extract the instance-related methods out of `RecordDao` and into `PostgresInstanceDao`, which implements the interface `InstanceDao`
* create a `MockInstanceDao` for testing
* use the `MockInstanceDao` in all four of the `InstanceService*` tests, which prevents them from creating a Hikari connection pool at all
Discovered as part of AJ-679 and blocks that ticket; does not resolve that ticket.

AJ-679: extract InstanceDao from RecordDao

---

service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/SamConnectionException.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/SamRetryableException.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/SamServerException.java
service/src/main/resources/application.properties
service/src/test/java/org/databiosphere/workspacedataservice/sam/HttpSamClientSupportTest.java

In this PR:
* `HttpSamClientSupport` graduates from an abstract class to a Spring bean, so it can implement `@Retryable`
* all calls to Sam gain retries, if the Sam client encounters a 500, 502, 503, 504, or 0; 0 indicates a failure to connect such as a `SocketTimeoutException`
* some new Sam Exception classes, to disambiguate the retryable exceptions from the not-retryable.
#194 adds retries for APIs and introduces the `RetryLoggingListener`. If #194 merges before this PR, this PR should update to use the logging listener in the Sam retries. If this PR merges before #194, we'll want a follow-on PR to add the logging listener.

AJ-899: retries for Sam

---

CONTRIBUTING.md

Following the investigation of https://broadworkbench.atlassian.net/browse/AJ-943, it seems we must manually approve the automerge PRs.  Adding a line in contributing to this effect.

AJ-943 must approve automerge PRs

---

.github/workflows/submit-dependencies.yml

Github's dependabot analysis has limited support for Gradle, which will not work out of the box for our project. You can see WDS's depdencies here: https://github.com/DataBiosphere/terra-workspace-data-service/network/dependencies - right now, there's no Java dependencies listed because Dependabot isn't parsing Gradle. See [this simple summary](https://dev.to/cricketsamya/gradle-with-dependabot-1o47) or details in [this issue report](https://github.com/dependabot/dependabot-core/issues/1164) for explanation of the Dependabot/Gradle issues.
So, this PR sets up the [gradle-dependency-submission](https://github.com/marketplace/actions/gradle-dependency-submission) action to submit gradle dependencies directly to the [Dependency Submission …

AJ-954: submit deps for dependabot

---

.github/workflows/submit-dependencies.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Followup to #198.
In this PR:
* Upgrade gradle to 8.0.2. I didn't realize the `gradle-dependency-submission` action required gradle 7.5, even though that's [clearly documented](https://github.com/marketplace/actions/gradle-dependency-submission). I figured we'd upgrade to latest.
* Upgrade sonarqube to 4.0.0.2929, to be compatible with the newer maven. The older version of sonarqube broke on gradle 8.
* swap the order of the :service and :client modules when processing dependencies … I figured :service is more important and if we run into any errors, at least we'll have a better chance of seeing the output of :service in the action's logs.
In earlier commits of this PR, I set the action to run on PRs, you can see the successful run of the action here: …

AJ-954: upgrade gradle to allow dependecy submission to work

---

service/src/main/java/org/databiosphere/workspacedataservice/sam/DisabledSamResourcesApi.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamConfig.java
service/src/main/resources/application.properties

Temporarily disable all Sam resource operations until AJ-964 and WM-1862 land.
This PR replaces the `ResourcesApi` from the Sam client with a noop class that returns true for all permission checks and does not create or delete any Sam resources.

AJ-963: temporarily disable Sam operations

---

build.gradle

Update versions of spring boot and spring dependency management plugins.
Spring boot latest is 3.0.5. I've updated to 2.6.14, the latest available version of the 2.6 series. I'd like to go higher but prefer to do that in a separate PR with more testing and reviewing of release notes.

AJ-992: spring boot, spring dep mgmt updates

---

client/swagger.gradle

Updates jackson to 2.14.2 inside the `:client` build, as recommended by the [dependency graph](https://github.com/DataBiosphere/terra-workspace-data-service/network/dependencies).

AJ-992: update jackson in :client project

---

build.gradle

Upgrades from Spring Boot 2.6 to 2.7.
I didn't see anything in the [Spring Boot 2.7 release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes) that needed attention.
The latest stable version of this plugin is 3.0.4. However, the [Spring Boot 3.0 release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes) "strongly recommend that you upgrade to Spring Boot 2.7 before migrating to Spring Boot 3.0" … so I'm doing that here, and we can evaluate an upgrade to 3.0 separately.

AJ-992: upgrade to Spring Boot 2.7

---

service/src/main/java/org/databiosphere/workspacedataservice/InstanceInitializerBean.java
service/src/main/java/org/databiosphere/workspacedataservice/InstanceInitializerConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/FailingSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/MisconfiguredSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/InstanceService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/GeneratedClientTests.java
service/src/test/java/org/databiosphere/workspacedataservice/InstanceInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/InstanceInitializerNoWorkspaceIdTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvDownloadTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/SamDaoInvalidWorkspaceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceNoPermissionSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamExceptionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceTest.java

In this PR:
* don't create or delete `wds-instance` Sam resources when creating/deleting WDS instances, including at startup time
* write APIs check permissions against the `workspace` Sam resource, not against `wds-instance` child resources
* we always check permission against the workspace specified in the `WORKSPACE_ID` env var, regardless of the WDS instance id
* _**remove the workspaceId query parameter from the create-instance API, since it is now obsolete and we rely on the `WORKSPACE_ID` env var instead**_
* if the `WORKSPACE_ID` env var can't be parsed to a UUID at startup, inject a `FailingSamDao` class instead of `HttpSamDao` - this will return false for all permission checks, log the failure reasons, and show the failure reason in WDS' `/status` API
* simplify a bunch of …

AJ-964: use workspace Sam resource, not wds-instance

---

service/src/main/java/org/databiosphere/workspacedataservice/process/LaunchProcessException.java
service/src/main/java/org/databiosphere/workspacedataservice/process/LocalProcessLauncher.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/LaunchProcessException.java
service/src/test/java/org/databiosphere/workspacedataservice/process/LocalProcessLaunchTest.java

Adding ability for WDS to launch a child process that will be used by back/restore for cloning. 
Jira ticket [here](https://broadworkbench.atlassian.net/browse/AJ-996).

AJ-996 Adding ability to launch child process

---

service/src/main/java/org/databiosphere/workspacedataservice/service/InstanceService.java

See the first item at https://medium.com/javarevisited/spring-transactional-mistakes-everyone-did-31418e5a6d6b:
> @Transactional is powered by [Aspect-Oriented Programming](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#aop). Therefore, processing occurs when a bean is called from another bean.
We had two cases where annotated transactions were called from within the same class; this PR removes those.

AJ-952: transactions must be called from another class

---

build.gradle
client/build.gradle
service/build.gradle

Adds the Broad Artifactory caching proxy as the first repository, with maven central as the second.
This will help with any maven central outages.

AJ-968: prefer artifactory caching proxy

---

Dockerfile

We need to invoke `pg_dump` in WDS during cloning of workspaces -- this Dockerfile allows us to include the Postgres client -- it extends from app-sec blessed code here: https://github.com/broadinstitute/dsp-appsec-blessed-images/blob/main/jre/Dockerfile.17-alpine
Reminder:
All PRs merged into main will generate a PR in https://github.com/broadinstitute/cromwhelm to update the WDS image deployed to kubernetes. 
After your merge, you must go to this repo and approve this generated PR and make sure it merges.
That merge will then generate a PR in https://github.com/DataBiosphere/leonardo.  This may or may not automerge; be sure to watch it to ensure it merges.

AJ-1005: Create Dockerfile to include postgres client for prod WDS

---

build.gradle
service/build.gradle

Relates to https://broadworkbench.atlassian.net/browse/AJ-1000
Resolves concern defined here: https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/22
Release notes related to Spring Boot Actuator: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.11
Reminder:
All PRs merged into main will generate a PR in https://github.com/broadinstitute/cromwhelm to update the WDS image deployed to kubernetes. 
After your merge, you must go to this repo and approve this generated PR and make sure it merges.
That merge will then generate a PR in https://github.com/DataBiosphere/leonardo.  This may or may not automerge; be sure to watch it to ensure it merges.

AJ-1000: Bump Spring Boot version to 2.7.11 to resolve security risk with Cloud Foundry

---

.github/workflows/release-python-client.yml

The combination of:
* #206 
* #222 
makes it such that the `WORKSPACE_ID` env var is required; if that var is not set, all Sam permission checks will fail.
In the `release-python-client.yml` action, we didn't have `WORKSPACE_ID` set; so as soon as we re-enabled Sam, permission checks started to fail, and therefore at least one test failed. This PR should fix that!

AJ-1006: set WORKSPACE_ID env var for python tests

---

build.gradle

Update snakeyaml - a transitive dependency - to address security-scan warnings.
Create a new section in our gradle files specific to transitive dependencies.

AJ-1026: update snakeyaml

---

service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java

If we can't figure out which environment WDS is running in, don't send anything to Sentry.
This will be the case when running unit tests in GHA, for instance. It should help us cut down on noise in Sentry.

AJ-1026: dont send to Sentry for default 'unknown' environment

---

client/artifactory.gradle
client/swagger.gradle

The addition of a `dependencies.constraints {` stanza in #226 caused artifactory publishing to fail.
This is explained in [this jfrog issue](https://github.com/jfrog/build-info/issues/198).
After poking around a bit, I have implemented the hack fix from the comments in that issue.
As a bonus, I renamed the gradle task `workspacedataserviceResttemplateClientLibrary` to `wdsClient` - shorter, easier to use, and doesn't tie us to using rest template.

AJ-1026: fix artifactory publish

---

build.gradle
client/swagger.gradle

In #226 I tried to upgrade snakeyaml, but was ineffective. I specified a dependency constraint … but since the versions controlled by `io.spring.dependency-management` take precedence, the constraint did nothing.
[This comment](https://github.com/spring-projects/spring-boot/issues/34405#issuecomment-1479808747) helps with confidence that Spring Boot 2.7.11 and snakeyaml 2.0 work ok together.
In this PR:
* upgrade snakeyaml via the `dependencyManagement` block, which is the `io.spring.dependency-management`-specific way to do it
* remove the ugly rewrite-pom hack which is no longer necessary.

AJ-1026: actually upgrade snakeyaml

---

README.md

* add `SAM_URL` and `WORKSPACE_ID` env vars to readme
* remove `render-config.sh` from readme, since it is unnecessary. Should I remove the script entirely from the repo?

AJ-1026: update README for env vars

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/java/org/databiosphere/workspacedataservice/cache/CacheLogger.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/MisconfiguredSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/PermissionsStatusService.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamDao.java
service/src/main/resources/application.properties
service/src/main/resources/ehcache.xml

In this PR:
1. Replace the simple in-memory ConcurrentHashMap cache provider - the "Simple" provider - with ehcache. This gives us way more features and configurability.
2. Modify the SamDao interface and implementation classes to play nice with ehcache. Previously we were caching the `org.broadinstitute.dsde.workbench.client.sam.model.SystemStatus` object, which is not serializable (ehcache requires serializable values); now we just cache a Boolean
3. Remove the eviction of Sam cache via a `@Scheduled` invocation and replace with a TTL on the cache itself
4. Add debug-level logging for cache operations
This PR is pre-work for [AJ-769](https://broadworkbench.atlassian.net/browse/AJ-769). In that ticket, I expect to make pretty heavy use of a new cache and would like control over that …

AJ-769: move to ehcache

---

.github/workflows/publish-docker.yml
.github/workflows/tag.yml

Also it appears that some changes didnt make it (as well as a line of code was deleted that should not have been in the previous PR). Honestly not sure how that happened now, maybe somehow my laptop and PC had conflicting versions (not sure) and some of my earlier changes on the previous PR got overwritten. Anyways, fixing so it should work now. 
Basically there was no error but PR didnt get created since there is no Jira ID present: https://github.com/DataBiosphere/terra-workspace-data-service/actions/runs/4985324312/jobs/8924787454

AJ-945 Adjust release github action to require Jira Id as part of manual trigger

---

.github/workflows/publish-docker.yml

I missed the part where ACR was being tagged and then re-tagged. Fixing to make sure that works correctly. 
It appears we do not use ACR images today - should we still be pushing them or just take this out until we do start to use them?

AJ-945 - Fix azure image docker image tagging

---

service/src/test/java/org/databiosphere/workspacedataservice/controller/ConcurrentDataTypeChangesTest.java
service/src/test/java/org/databiosphere/workspacedataservice/retry/TransactionRetryTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorSamTest.java

In my environment, unit tests take ~60 seconds. This isn't bad, but we can do better.
In very unscientific testing on my local system with other apps open, I saw the following results. These times are the average of running each test 5 times.
| | Before | After |
|--------|--------|--------|
| `TransactionRetryTest` | 37.62s | 2.38s |
| `ConcurrentDataTypeChangesTest` | 8.9s | 5.7s |
| `RecordOrchestratorSamTest` | 4.2s | 0.2s |
This PR speeds up tests by:
* reducing concurrency for `ConcurrentDataTypeChangesTest`
* reducing retry counts and wait durations for `TransactionRetryTest` and `RecordOrchestratorSamTest`

AJ-1063: speed up unit tests

---

service/build.gradle

* upgrades `sam-client` to latest version
* puts a constraint on `org.json:json`, which is a transitive dependency of `sam-client`, to use the latest version `20230227`. This addresses CVE-2022-45688.
Note: the fix from #228 does NOT appear necessary in this case, since the `dependencies.constraints` stanza is in service/build.gradle, not build.gradle. This means the POM file generation in the :client project is unaffected.

AJ-1063: upgrade Sam client and org.json:json

---

service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDao.java
service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java

https://broadworkbench.atlassian.net/browse/WOR-877
I misunderstood how cloning instructions work the first time around. Using `LINK_REFERENCE` resulted in clones linking their policies to the source instead of merging them. [Read this](https://docs.google.com/document/d/1dRtE_nZf8e231DZmk_-9CDbjYTiIN2ZZwI95uF1w2pg/edit#heading=h.nbmbwtfq4byd) for more details if you care to.

fix clone instructions

---

.github/release-drafter-config.yml
.github/workflows/release-drafter.yml

part of AJ-999 but does not complete that ticket.
Incorporate the [Release Drafter](https://github.com/marketplace/actions/release-drafter) github action, using recommended config, to help us automatically generate drafts for release notes.
I'm suggesting we let this run for a bit and see what it does for us, then we can make a decision on whether or not it'll benefit us. We'll see, after we gather some data!

AJ-999: incorporate Release Drafter action

---

service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityEvent.java
service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilder.java
service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityLogger.java
service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityLoggerConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityModels.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/DataRepoController.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/MisconfiguredSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/DataRepoService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/InstanceService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/resources/ehcache.xml
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilderTest.java
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/LogStatementTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/MockSamClientFactory.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceNoPermissionSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamExceptionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceTest.java

Enables activity logging for all write operations, as part of control M1 for production readiness. I end up with log entries like this:
```
2023-05-17 15:25:31,925 INFO  [a50716bb-eb7b-4003-b571-26ee004d52cf] org.databiosphere.workspacedataservice.activitylog.ActivityLogger: user 213400982345703434599 created 1 instance(s) with id(s) [b0a945bd-a737-4017-a519-786392023a0d]
2023-05-17 15:25:58,307 INFO  [eee6fd6f-b108-4db9-8844-b8ae0b92ba83] org.databiosphere.workspacedataservice.activitylog.ActivityLogger: user 213400982345703434599 created 1 record(s) of type mytype with id(s) [123]
2023-05-17 15:26:05,042 INFO  [db12c397-3b56-412c-8846-6670f3358970] org.databiosphere.workspacedataservice.activitylog.ActivityLogger: user 213400982345703434599 deleted 1 record(s) of type mytype with id(s) …
```

AJ-769: activity logging

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/TsvStreamWriteHandler.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributes.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributesTest.java

Fixes [AJ-1028](https://broadworkbench.atlassian.net/browse/AJ-1028)
This PR fixes an issue caused by extra tabs in a TSV file, specifically in the headers. This created empty columns and serializing issues for Postgres (specifically, `ERROR: zero-length delimited identifier`).
This fix is inserted in TsvStreamWriteHandler.java when we're processing records. It iterates through the attributes (which converts the Treemap to a Set since `while` looping and removing directly would give us false negatives if the value `remove()` returns is null) removing any entries with empty keys (aka empty TSV headers). 
We're now seeing happy 200s
[AJ-1028]: https://broadworkbench.atlassian.net/browse/AJ-1028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1028 Fix PostgreSQL error caused by blank TSV headers

---

pull_request_template.md

Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. 
After your manually trigger the github action (and it completes with no errors), you must go to [this](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that merged succesfully.
The terra-helmfile PR merge will then generate a PR in https://github.com/DataBiosphere/leonardo.  This may or may not automerge; be sure to watch it to ensure it merges.

AJ-945 - Adjust PR template wording

---

README.md

If the path for the nginx command is not absolute, it fails. Adjust that in the ReadMe. 
Reminder: …

AJ-1070 - Fix nginx to be an absolute path

---

service/src/test/python/test.py

https://github.com/DataBiosphere/terra-workspace-data-service/pull/239 changed the behavior of tdr import to create a table, but did not update the python test to reflect these changes.  The import snapshot python test was then leaving extra tables in the db, causing other tests to fail.  This PR tests the behavior and then cleans up after itself.

AJ-1010 fix import python test

---

service/src/main/java/org/databiosphere/workspacedataservice/service/DataRepoService.java
service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoServiceTest.java
service/src/test/python/test.py

https://github.com/DataBiosphere/terra-workspace-data-service/pull/239 added `Snapshot Id` and `Import Time` attributes to the snapshot import, but as these were last minute add-ons, they were not covered by tests - and didn't work correctly!  This PR ensures they are actually added to the import table and updates tests to verify that.

AJ-1010 fix snapshot attributes

---

.github/workflows/release-python-client.yml

This changes the logic to run python tests on any new PR and PR update. The GAH already specifies to only publish the client if the branch that the GAH action is being run on is "main". 
Reminder: …

AJ-1063 - Change GAH to always run python tests

---

service/src/main/java/org/databiosphere/workspacedataservice/InstanceInitializerBean.java
service/src/main/resources/application.properties

This PR depends on broadinstitute/terra-helmfile#4233.
It takes the `STARTUP_TOKEN` env var exposed in that other PR and makes it available as a Spring property.

AJ-947: expose startup token to WDS

---

build.gradle

Upgrades Spring Boot. See https://spring.io/blog/2023/05/18/spring-boot-2-7-12-available-now
I don't believe we are vulnerable to CVE-2023-20883 but let's upgrade anyway.

AJ-1088: upgrade spring boot 2.7.11 -> 2.7.12, addresses CVE-2023-20883

---

.github/workflows/publish-pacts.yml

See [AJ-1055](https://broadworkbench.atlassian.net/browse/AJ-1055)
This PR adds a github action to automatically publish consumer tests to the [DSP Pact Broker](https://pact-broker.dsp-eng-tools.broadinstitute.org/).  The action, as written, specifically names tests written as Sam as provider; that will need to be adjusted in the future when contract tests against other providers are added.  
See the link to the pact broker to verify that `wds-consumer/sam-provider` contracts were updated at the time of this PR.
[AJ-1055]: https://broadworkbench.atlassian.net/browse/AJ-1055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1055 Create publish-pacts.yml

---

service/build.gradle
service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java

Addresses CVE-2022-23437.
Xerces is a (deeply) transitive dependency of pact. This PR upgrades the pact gradle plugin and pact consumer/junit library to latest, which carries an upgrade to a non-vulnerable version of xerces.
between versions 4.2.21 and 4.3.0, pact changed behavior of `pactVersion` in `@PactTestFor`. Our tests were failing unless we explicitly specified `pactVersion = PactSpecVersion.V3`

AJ-1088: upgrade pact, which upgrades xerces transitively

---

service/build.gradle
service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java

This reverts commit 2a502ee6fc791c36da7cea0ceee8b7576296c208.
sam-provider contract tests for wds-consumer are failing after this commit. Let's revert and get everything passing until we figure out what's actually happening.

Revert "AJ-1088: upgrade pact, which upgrades xerces transitively (#262)"

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/service/TsvStreamWriteHandler.java

The version of `jackson-dataformat-csv` we had was not in sync with Spring Boot's version of other Jackson libraries, and this caused some annoying errors, like `java.lang.NoSuchFieldError: USE_FAST_DOUBLE_WRITER`.
This PR aligns the jackson versions and fixes the one syntax compatibility issue that came from the downgrade.

AJ-856: downgrade jackson-dataformat-csv

---

service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/TsvStreamWriteHandler.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java

[AJ-1059](https://broadworkbench.atlassian.net/browse/AJ-1059)
If a user tried to upload a tsv to a pre-existing table, but the primary key (leftmost column) in the tsv differed from that in the existing table, they received a hideous error.  If the primary key was passed as a parameter in the API call, then it was checked for conflict before reading the TSV.  But if it was not passed as a parameter, we could only find it out by reading the tsv, at which point we're past the point of checking against the existing table.
I solved this the easy way, by fetching the pre-existing primary key at the conflict check and passing it in to the `TSVStreamWriteHandler`, where previously would only be the parameter-passed key.  This results in a message "Uploaded TSV is either missing the `primaryKey` …

AJ-1059 compare primary key on tsvs

---

service/src/main/resources/logback-spring.xml

Changes WDS logging:
* removes the file logger, since we don't need that in prod
* removes color coding from console logs, so logs are easier to read in Azure Portal
* aligns the logging pattern very closely to Spring's default from org/springframework/boot/logging/logback/defaults.xml
* aligns the console appender very closely to Spring's default from org/springframework/boot/logging/logback/console-appender.xml
Here's what logging looks like now:

AJ-1099: clean up logging patterns

---

service/src/main/java/org/databiosphere/workspacedataservice/service/TsvStreamWriteHandler.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/BadStreamingWriteRequestException.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvErrorMessageTest.java
service/src/test/resources/tsv-errors/column-separator.tsv
service/src/test/resources/tsv-errors/empty-header-line.tsv
service/src/test/resources/tsv-errors/invalid-middle-byte.tsv
service/src/test/resources/tsv-errors/too-many-entries.tsv

We already have error trapping for specific TSV problems, like duplicate column names. But, we didn't have catch-all error trapping for the exceptions we didn't expect; this PR adds that. Plus, some new known-bad TSVs for use in unit tests.

AJ-1109: more helpful TSV errors

---

service/src/main/java/org/databiosphere/workspacedataservice/datarepo/HttpDataRepoClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/HttpWorkspaceManagerClientFactory.java

See https://broadworkbench.atlassian.net/browse/AJ-1065
We want to reuse the low-level http clients for the Sam, WSM, and TDR libraries. This PR does that, following examples previously set such as:
https://github.com/DataBiosphere/terra-workspace-manager/blob/3970810228cb235d507dcdb4a3c54f33fff5c463/service/src/main/java/bio/terra/workspace/service/iam/SamService.java#L106
https://github.com/DataBiosphere/terra-data-catalog/blob/main/common/src/main/java/bio/terra/catalog/rawls/RawlsClient.java

AJ-1065: reuse http clients for Sam, WSM, TDR libraries

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/service/MDCServletRequestListener.java
service/src/main/resources/logback-spring.xml
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackMDCRequestResponseTest.java

This is a followup to https://github.com/DataBiosphere/terra-workspace-data-service/pull/264#issuecomment-1579345929.
The unique requestId in our logs was making those log lines quite long and annoying.
This PR switches the requestId from a 36-character UUID to a [hashid](https://hashids.org/) which will typically be 8 chars.
Here's what the new log entries look like:

AJ-1099: shorter request id; shorter log entries

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/CloningController.java
service/src/main/resources/static/swagger/openapi-docs.yaml

Work in #212 included functionality to backup our database using pg_dump. Now that we want to add the restore functionality, we should aggregate those APIs under the name Cloning instead of Backup to be inclusive.

AJ-1122: Rename Backup to Cloning

---

.github/workflows/publish-docker.yml

#212 introduced changes to `publish-docker.yml` that broke; see https://github.com/DataBiosphere/terra-workspace-data-service/actions/runs/5282685550/jobs/9557927242 for an example of the error.
This PR changes things around to ensure we auth before attempting to push to GCR.

auth docker before pushing to GCR

---

Dockerfile

Base debian image is going through a change, adjust how postgres will be installed given the new base image. 
Corresponding PR for base image update: https://github.com/broadinstitute/dsp-appsec-blessed-images/pull/45
Reminder: …

AJ-935: adjust docker file with changes from focal to jammy in base image

---

service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java

[AJ-1101](https://broadworkbench.atlassian.net/browse/AJ-1101)
For provider-side contract tests to work properly, we need to let them know what path we're expecting.
See https://broadworkbench.atlassian.net/wiki/spaces/IRT/pages/2787672065/Demystifying+Provider+States+Callbacks+-+pathFromProviderState for explanation.
[AJ-1101]: https://broadworkbench.atlassian.net/browse/AJ-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1101 include resourceId as key in contract test

---

client/build.gradle

first discovered in #284.
At least one of the transitive dependencies of the artifactory gradle plugin version 4.18.2 have been removed from the internet. This caused builds/tests to fail.
This PR updates the plugin to latest, which fixes those failures.

AJ-1122: update artifactory plugin

---

service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/TsvSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvDownloadTest.java

Reviewer: the github diff is easier to see if you ignore whitespace.
This PR addresses [AJ-1142](https://broadworkbench.atlassian.net/browse/AJ-1142): it properly handles arrays and JSON objects in TSV downloads.
At the implementation level, this PR includes:
* change `TsvSupport` from a class of static methods to a Spring `@Component`; this makes it easy to give that class an `ObjectMapper` for serialization.
* When serializing the TSV, first get the `DataTypeMapping` schema for the record type. Make serialization decisions based on the datatype of the column in question:
* for arrays and JSON objects, serialize the value as JSON
* for scalars, continue using the `.toString()` for that value
* Add unit tests to fix the missing coverage
NOTE: While working on this PR, I discovered …

AJ-1142: json, array datatypes in TSV download

---

Dockerfile

Reverts DataBiosphere/terra-workspace-data-service#283 - need this to fix the release

Bring AJ-935 back: adjust docker file with changes from focal to jammy in base image

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/sourcewds/HttpWorkspaceDataServiceClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sourcewds/WorkspaceDataServiceClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sourcewds/WorkspaceDataServiceConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/sourcewds/WorkspaceDataServiceDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sourcewds/WorkspaceDataServiceException.java

This is a split out PR in hopes to make https://github.com/DataBiosphere/terra-workspace-data-service/pull/280 smaller. This PR adds the wds client that will be used for destination WDS to trigger backup on a source WDS (where the clone was initiated). 
Reminder:
After you manually trigger the github action (and it completes with no …

AJ-955 - Add source WDS Api client to enable trigger of backup from one WDS to another

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/leonardo/HttpLeonardoClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/leonardo/LeonardoClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/leonardo/LeonardoConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/leonardo/LeonardoDao.java
service/src/main/java/org/databiosphere/workspacedataservice/leonardo/LeonardoServiceException.java
service/src/main/resources/application.properties
service/src/test/java/org/databiosphere/workspacedataservice/leonardo/LeonardoDaoTest.java

This is a split out PR in hopes to make https://github.com/DataBiosphere/terra-workspace-data-service/pull/280 smaller. This PR adds the leonardo client that will be used to request the source WDS url to enable cloning. 
Reminder: …

AJ-955 - Adding Leonardo Client to WDS to extract source WDS Url during cloning

---

service/src/main/resources/static/swagger/openapi-docs.yaml

the enum definition for `BackupJob`'s `status` field was incorrect. Specifically, this allows for `ERROR` status, which previously was not allowed and could not be deserialized.

fix status enum for BackupJob

---

service/src/main/resources/application.properties
service/src/main/resources/static/swagger/openapi-docs.yaml

part of AJ-1075 but does not complete that ticket.
This exposes the chart version and docker image version in WDS's `/version` API. It builds on previous terra-helmfile PR here: https://github.com/broadinstitute/terra-helmfile/pull/4211
AJ-1075 will require UI work to complete; this PR satisfies the backend functionality to support the UI.
See https://howtodoinjava.com/spring-boot/info-endpoint-custom-info/#4-adding-custom-information-to-info-endpoint for explanation of the code changes in this PR.

AJ-1075: expose chart version and docker image version in /version api

---

service/src/main/java/org/databiosphere/workspacedataservice/InstanceInitializerBean.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/CloningController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/CloneDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresCloneDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BackupRestoreService.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/CloneResponse.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/CloneStatus.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCloneDao.java

This PR adds an api call that will expose the overall clone status - this specific call will be used by the terra ui to display the overall status of the cloning process. 
Reminder: …

AJ-937 - Add clone status api call that terra-ui will use

---

service/build.gradle
service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java

This updates the pact libraries to latest, which requires minor changes to the pact tests. We originally did this in #262 but rolled it back because pact tests were failing. We found the failure cause, which was NOT due to the library update. Now that the pact tests are passing, let's revisit this upgrade.
This should address dependabot issues about `xercesImpl`.
---
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is …

AJ-1162: update pact libraries

---

service/build.gradle

updates our `guava` dependency to latest. This should address dependabot warnings.
---
Reminder:
The …

AJ-1162: update guava

---

.github/workflows/submit-dependencies.yml

I think I know why our dependency submission action is failing (example [here](https://github.com/DataBiosphere/terra-workspace-data-service/actions/runs/5556695260/jobs/10149531709)):
* the new pact libraries from #300 require Java 17
* the dependency submission action was running on Java 11 and thus can't inspect the new pact libraries.
The key line in the error message is "The consumer was configured to find a library for use during runtime, **_compatible with Java 11_**…"
This PR runs the dependency submission action using Java 17.
---
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github …

AJ-1162: use Java 17 for dependency submissions

---

service/build.gradle

This PR addresses proactive dependabot warnings on `com.squareup.okio:okio`.
`com.squareup.okio:okio` is a transitive dependency of `com.squareup.okhttp3:okhttp`.
This PR updates our direct dependency on `com.squareup.okhttp3:okhttp` to latest, then sets a transitive constraint to update `com.squareup.okio:okio` to the version recommended by dependabot.
---
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided …

AJ-1162: update okhttp and okio

---

service/src/main/java/org/databiosphere/workspacedataservice/InstanceInitializerBean.java
service/src/test/java/org/databiosphere/workspacedataservice/InstanceInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/InstanceInitializerCloneTest.java

if the source workspace returns 404 from `/backup/{v}`, we assume the source workspace is too old and does not have that API implemented. In such a case, record a decent error message for the clone job:
> The data tables in the workspace being cloned do not support cloning. Contact the workspace owner to upgrade the version of data tables in that workspace.
Before this PR, the error message was unhelpful:
> 404 NOT_FOUND; nested exception is org.databiosphere.workspacedata.client.ApiException: Not Found
---
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: …

AJ-961: better error message for too-old source workspaces

---

service/src/main/java/org/databiosphere/workspacedataservice/process/LocalProcessLauncher.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BackupRestoreService.java
service/src/test/java/org/databiosphere/workspacedataservice/process/LocalProcessLaunchTest.java

Do not transform the entire stdout or stderr from LocalProcessLauncher into a String. Ensure the out/error streams stay as streams until we need to look at them.
In BackupRestoreService, when checking for the error output, limit the output to 1024 bytes.

AJ-1181: dont materialize process streams

---

service/src/main/java/org/databiosphere/workspacedataservice/service/JsonStreamWriteHandler.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JsonStreamWriteHandlerTest.java

part of AJ-1069 but does not complete that ticket.
While evaluating AJ-1069 as a good ramp-up ticket for new developers, I found an inconsistency in our JSON batch-write API: the `JsonParser` used for batch-write does not fully inherit its configuration from the `ObjectMapper` definition in `JsonConfig`. This PR fixes that, so it inherits features correctly.
I am pushing this PR through to make AJ-1069 easier and more focused on ramp-up instead of digging through ugly Jackson internals.

AJ-1069: JsonStreamWriteHandler features-enabled unit test

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/dao/DataSourceConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/resources/application.properties
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

Combine WDS's two connection pools into one, thereby halving the number of db connections WDS requires. Preserve the capability to stream TSV downloads from Postgres to the end user.
I verified that WDS still uses cursors/streams to query Postgres by setting `-c log_statement=all` on my local Postgres docker image and watching what queries were actually executed. I also verified that the autocommit value was set back to true by cranking up logging levels for `com.zaxxer.hikari.HikariConfig` and `com.zaxxer.hikari`.
I cannot figure out how to unit test the low-level cursor behavior of the JDBC driver. This PR turns on features that are implemented in libraries. I would love to hear ideas on how to test!
High-level changes in this PR:
* add Spring Batch for its `JdbcCursorItemReader`, which …

AJ-1187: WDS only needs one connection pool

---

.github/workflows/publish-docker.yml
service/build.gradle

Reminder:
The terra-helmfile PR merge will then generate a PR in …

[AJ-1193] Move wds-debian from base "blessed" directory

---

service/src/main/resources/application.properties

See https://broadworkbench.atlassian.net/browse/AJ-1186
The default connection pool size for Spring/Hikari is 10.  It's not clear that WDS needs that many connections.  
Some informal testing with different pool sizes under load (greater load than we generally expect to have in real life, ~20 users all uploading files at once), I generally saw no more than 8 connections being used at a time.  (We seemed to hit limits in the relay listener before we hit limits in the DB).  Using only 6 connections seemed to result in only 1-2 pending at a time, leading me to select 7 as a rough estimate of a reasonable max pool size.
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this …

AJ-1186 DB Connection Pool Size

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/DataSourceConfig.java
service/src/main/resources/application.properties

A bit of cleanup after #317 and #313 ...
* Use `spring.datasource.hikari.*` properties instead of `spring.datasource.*` properties. This should have no impact to WDS runtime, but it makes inspection via IntelliJ easier since IntelliJ recognizes `spring.datasource.hikari.*`.
* Change initialization of the NamedParameterJdbcTemplate bean to use Spring-managed injection for its datasource, instead of bypassing injection and calling `mainDb()` directly.
* add logging properties for the Hikari connection pool, but set the properties to defaults; this is a developer convenience for anyone who needs to change them later

AJ-1187: use Hikari properties; bean initialization

---

README.md
service/build.gradle
service/src/test/java/org/databiosphere/workspacedataservice/pfb/PfbParsingTest.java

As a part of the work to publish the java-pfb library, this PR adds a test to prove that the library is correctly published and that we can use the methods from java-pfb in WDS!
Review Request:
-> Does the location of the test make sense?

AJ-1095: Add Java-PFB import and test

---

service/src/main/java/org/databiosphere/workspacedataservice/logging/AvailabilityListener.java
service/src/main/resources/application.properties
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/AvailabilityTest.java

This PR enables Liveness and Readiness built into SpringBoot to enable our app to communicate with K8. 
Listener and tests inspired by: https://github.com/DataBiosphere/jade-data-repo/pull/670
Confirmed this works in a BEE
Sister PR helm file change: https://github.com/broadinstitute/terra-helmfile/pull/4413
-----------------------
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided the action will not fully …

AJ-1078 Enable Liveness and Readiness

---

README.md

The doc as authored results in a failing build because the postgres container isn't running.  Since running the tests is covered later, skipping them here allows the suggested command to run without breakage, and accomplishes the goal to "just build the code."

AJ-1196 Update README.md #running section to run clean

---

service/src/main/resources/application.yml

Clarify why we disable `sql.init.mode`
Followup I missed from prior PR feedback: https://github.com/DataBiosphere/terra-workspace-data-service/pull/324#discussion_r1293874925

AJ-1219: Clarify comment about disabling `sql.init.mode`

---

.github/workflows/release-python-client.yml
client/swagger.gradle

Currently, the WDS Java client's default user agent is `Swagger-Codegen/1.0.0/java`. The Python client's default user agent is a little better, since it includes the WDS version it was published from. For example, `OpenAPI-Generator/0.2.97/python`.
This updates the default user agents for both client libraries to `wds-client/<version>/<language>`. For example, `wds-client/0.2.97/java` for the Java client and `wds-client/0.2.97/python` for the Python client.
The generated client objects allow consumers to override the default user agent.
Note: will conflict with #321.

[AJ-879] Update default user agent for client libraries

---

service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java
service/src/test/java/org/databiosphere/workspacedataservice/DataTypeInfererTest.java

* 33b8d450907e41263976e51b4103e5f4be50e8e9 - Formatting tweaks only to Improve test readability.
* be6595bd41d25820b1426236d965d00c300ae706 - Eliminate a `*` import and include some resources in the commit comment for why.
* 52ef9dfb27ea6db738fab0fc90a75d9d5e3d9a74 - Fix issue that caused null values in relation columns to crash schema infererence.
* 3ab4e01f3a4f8e689979c9c988e392bcaf94d76a - Apply similar fix for multi-relation values too.

AJ-1143: Skip null relation values when determining relation columns.

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java

While working on `DataTypeInferer` I noticed these stanzas of code which cried out for `BiStream` which was designed exactly for this sort of streaming logic.  See https://github.com/google/mug#bistream-streams-pairs-of-objects for many examples.
This commit is pure refactoring and is intended to demonstrate how `BiStream` can be used to simplify complex iterations by using higher-level predicates.
Note, since `BiStream` inherits from the Stream API, it also picks up the `Autocloseable` interface, which triggers some extra warnings which you can safely ignore.  For Intellij, this can be done by adding `BiStream` and `BiStream.from` to the allowlist to ignore these warnings.

AJ-1286: Introduce `BiStream` idioms using `com.google.mug`

---

service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/main/resources/static/swagger/swagger-ui.html

In this PR:
* eliminate the warning about `../` url when generating the swagger client (which also happens at bootRun). The `../` url is a leftover from when WDS was bundled with CBAS and is no longer necessary.
I piggybacked on that fix with a few other swagger UI tweaks. These are my personal opinions; feel free to opine if you disagree!
start with each major section collapsed, making it easier to navigate quickly to the section you care about:
add a filter bar to quickly filter to the main section (aka tag) you care about:
display request durations for each API invocation:
display the `operationId` for each API; these ids become method names in the generated Java and Python clients:

AJ-1090: swagger definition and UI tweaks

---

service/src/test/python/test.py

Adds an explicit sort to the Python `test_relation_record_creation_queryall_and_delete` test.
This feels like an incrementally good change overall, but I'm mostly doing it as prep for #321 so I can validate potential changes to the asc/desc enum.

AJ-1173: add sorting to python test

---

service/src/main/resources/static/swagger/openapi-docs.yaml

This eliminates spurious "allOf with multiple schemas defined. Using only the first one: Job" warnings when generating the Java client.
The issue is described here: https://github.com/OpenAPITools/openapi-generator/issues/11841
I have diff-ed the generated code before and after this PR, and do not see any difference.
```shell
➜  terra-workspace-data-service git:(da_AJ-1173_allOfSchemaNames) ✗ gw :client:openApiGenerate
> Task :client:openApiGenerate
allOf with multiple schemas defined. Using only the first one: Job
allOf with multiple schemas defined. Using only the first one: Job
allOf with multiple schemas defined. Using only the first one: Job
allOf with multiple schemas defined. Using only the first one: Job
allOf with multiple schemas defined. Using only the first one: Job …
```

AJ-1173: clarify 'allOf' composed schema name

---

service/build.gradle

nobody on the team seems to be relying on [devtools](https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/using.html#using.devtools): 
https://broadinstitute.slack.com/archives/C02SJQ0FKHQ/p1693341056309169
so, let's get it out of our stack entirely instead of figuring out how to remove it only from prod.

AJ-1285: remove Spring Boot Dev Tools

---

service/src/main/java/org/databiosphere/workspacedataservice/sourcewds/HttpWorkspaceDataServiceClientFactory.java

Currently WDS during cloning is complaining that "No OAuth2 authentication configured!" - use SetBearerToken instead to fix this. It appears that this is a difference in implementation between jersey library (that we used previously) that didnt cause issues, but is different since we have made the move to okhttp. 
Reminder:
After …

AJ-1322 - Set source wds client token using SetBearerToken

---

CONTRIBUTING.md
scripts/git-hooks/README.md
scripts/git-hooks/pre-commit

Run the following command to pick up all provided hooks (as of this writing, only includes the `pre-commit` hook for applying the style guide).
```
git config core.hooksPath scripts/git-hooks
```

AJ-1289: Add optional `pre-commit` hook to enforce style guide

---

.git-blame-ignore-revs
CONTRIBUTING.md

To enable git to ignore this commit run:
```
$ git config blame.ignoreRevsFile .git-blame-ignore-revs
```
This ignores the large commit produced from merging: https://github.com/DataBiosphere/terra-workspace-data-service/pull/336

AJ-1289: Ignore large reformatting commit from `git blame`

---

service/src/main/java/org/databiosphere/workspacedataservice/leonardo/HttpLeonardoClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sourcewds/HttpWorkspaceDataServiceClientFactory.java

For all our OkHttp-based client libraries (Sam, Leo, WDS), restrict to HTTP 1.1 and disallow HTTP 2.
In scale testing, we have seen intermittent/hard-to-reproduce errors like `okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL`. Previous investigation hinted at HTTP 2 being a culprit here.
We don't need HTTP 2, and I don't anticipate that restricting to HTTP 1.1 will have any repercussions.
See:
* https://github.com/broadinstitute/rawls/pull/2154
* https://github.com/DataBiosphere/cbas/pull/208
* https://broadinstitute.slack.com/archives/C05BYVBM2HE/p1695916806679619

AJ-1357: restrict to HTTP 1.1 for OkHttp clients

---

client/swagger.gradle

More prefactoring work for AJ-1011. This adds validation of our OpenAPI spec to the gradle build.
If the spec is invalid, we'll get a build failure:
Note that we also get non-fatal recommendations on how to clean up the spec!

AJ-1011: add openapi validation to build

---

service/src/main/resources/static/swagger/openapi-docs.yaml

Prefactoring for AJ-1011. In `service/src/main/resources/static/swagger/openapi-docs.yaml`:
* clean up some formatting
* add some code comments
* sort paths first by their tag (Records, Schema, Instances, etc) and second alphabetically
* sort all components alphabetically
A lot of lines of code have changed, but there should be zero functional changes; it's all reordering and formatting. You can view commit-by-commit to see it in smaller chunks.

AJ-1011: openapi cleanup

---

service/src/integrationTest/java/org/databiosphere/workspacedataservice/InstanceInitializerCloneTest.java
service/src/integrationTest/java/org/databiosphere/workspacedataservice/service/RestoreServiceIntegrationTest.java
service/src/test/java/org/databiosphere/workspacedataservice/InstanceInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilderTest.java
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/LogStatementTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/ConcurrentDataTypeChangesTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/DataRepoControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvDownloadTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvInputFormatsTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/leonardo/LeonardoDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java
service/src/test/java/org/databiosphere/workspacedataservice/retry/TransactionRetryTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceNoPermissionSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamExceptionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/PermissionsStatusServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvErrorMessageTest.java
service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java

Tidy up `setUp` and `tearDown` methods and improve test isolation.
* Rename generally to `setUp` and `tearDown`.  This is just for consistency.
* Where possible, prefer `@BeforeEach` and `@AfterEach` over `@BeforeAll` and `@AfterAll`.  This is to improve test isolation within test suites.
* Prefer to do cleanup in `tearDown` rather than pre-emptively in `setUp`.  Tests should be responsible for cleaning up after themselves, rather than other tests.
* Drop the `static` modifier from `private` but non-`final` instance variables in test cases.  This is to make each test manage its own instance state rather than share across invocations within the test file.

Tidy up setup and teardown methods.

---

.gitignore
README.md
service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/controller/ImportController.java
service/src/main/resources/static/swagger/apis-v1.yaml
service/src/main/resources/static/swagger/openapi-docs.yaml

This PR introduces a bunch of concepts to WDS; I'm putting this out for debate and discussion.
Note that this PR does not actually implement a new/async snapshot API yet. I will do that in follow-on PRs; I wanted to get this out for discussion before then.
In this PR:
Or, bump groups of APIs together. We don't have to version all WDS APIs at once. This PR adds a new `importV1` API as a successor to the v0.2 `importSnapshot` API.
In this PR, I've marked the `importSnapshot` API as deprecated and given it a 3-month time to live. Admittedly, this is an easy deprecation since we're not using that API anywhere yet.
And then hand-code implementation classes on top of those interfaces. This forces attention to detail on our OpenAPI spec. Since that spec is used to create our Java and Python …

AJ-1011: setup for async snapshot api

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/InstanceInitializerBean.java
service/src/main/java/org/databiosphere/workspacedataservice/InstanceInitializerConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/distributed/LockConfig.java
service/src/main/resources/liquibase/changelog.yaml
service/src/main/resources/liquibase/changesets/20231003_lock_table.yaml
service/src/test/java/org/databiosphere/workspacedataservice/InstanceInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/InstanceInitializerNoWorkspaceIdTest.java

Currently cloning logic is not replica safe. This is due to the fact that currently if one replica initiates clone mode, another replica will see that and continue on to initialize the default schema. Problem is, cloning expects the default schema to not be created yet. 
This PR takes the first step in cloning replica safety by introducing a Lock that will prevent more than one replica from initiating cloning. Follow up work (in ticket AJ-1363) will refactor the initialization logic so a second replica won't try and create the default schema if cloning is happening. This PR **does not** mean cloning is replica safe yet. 
----------------
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed …

[AJ-1243] Introduce Lock in Cloning

---

service/build.gradle
service/src/main/resources/application.yml

Spun off from #353 and #355
This PR brings Quartz into WDS, but doesn't yet use Quartz for anything. This is a setup PR to make future PRs smaller. In this PR:
* Add the Quartz starter dependency for Spring Boot
* Configure Quartz to run in-memory via `application.yml`
See the code comments for the drawbacks of running Quartz in-memory, as opposed to database-backed. #355 configures Quartz to be database-backed, but there [is debate](https://docs.google.com/document/d/1one0ouQmGC4ymKaPSb0DLHWrf3mewCJ-ZWxBgQcSuTA/edit
) on whether this is a good idea or not, because Quartz can write sensitive data to the db temporarily.
I would like to push this in-memory PR through to unblock async development, while continuing the debate over how to handle sensitive data. We can always adjust Quartz from …

AJ-1011: include in-memory Quartz in WDS

---

README.md
local-dev/run_postgres.sh

Quickly access local postgres prompt.
Usage:
```
./local-dev/run_postgres.sh shell
```

AJ-1359: Wire up `shell` verb for `run_postgres.sh`

---

service/build.gradle

Excludes the autogenerated API interfaces and models from Sonar scans.
These files are created by openapi-generator automatically, and they trigger a bunch of noise in Sonar. We don't need that noise.
See Sonar results on #361 for an example of all the noise.

AJ-1359: exclude generated files from Sonar scans

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresJobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/QuartzSchedulerDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/SchedulerDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportJobInput.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbSchedulable.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/TdrManifestSchedulable.java
service/src/main/java/org/databiosphere/workspacedataservice/jobexec/JobExecutionException.java
service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/JobService.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/Schedulable.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/ImportJobInputTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java

connects the dots and performs async snapshot import via Quartz. Well, as of this PR the import fails because we're not properly passing a token. But you can see that it's trying, and token work will be a follow-on PR ([Slack thread](https://broadinstitute.slack.com/archives/C02SJQ0FKHQ/p1697205316686489))
To test this locally:
1. Export a snapshot from TDR via the [exportSnapshot API](https://jade.datarepo-dev.broadinstitute.org/swagger-ui.html#/snapshots/exportSnapshot) and copy the url to the exported manifest
2. Call WDS's `importV1` API with a payload of `{"type": "TDRMANIFEST", "url": "url-to-manifest-from-previous-step"}` and make note of the jobId it returns
3. Call WDS's `jobStatusV1` API, passing the jobId from the previous step
4. View the WDS logs to see progress of the job …

AJ-1011: snapshot import via Quartz

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/JobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresJobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/TdrManifestQuartzJob.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/PostgresJobDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java

a quickie: tag a bunch of TODO comments with their associated Jira tickets, to make it easier to search the codebase for specific TODOs.
I have not tried to tag all the TODOs in the codebase.

AJ-1011: update TODO comments

---

service/src/main/java/org/databiosphere/workspacedataservice/InstanceInitializerBean.java
service/src/test/java/org/databiosphere/workspacedataservice/InstanceInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/InstanceInitializerNoWorkspaceIdTest.java

This PR makes cloning replica safe by refactoring our initialization logic to follow the flowchart below:
Ultimately, in code `initCloneMode()` returning false will have us create the default schema and returning true has us "do nothing" (ie just start WDS). 
Here is what the logs will look like. 
**Non-Cloning Replica**: 
```
2023-10-11 18:40:51.780  INFO [] [main] o.d.w.InstanceInitializerBean            : Default workspace id loaded as e28ba126-6d7a-4046-993f-a0e73512078b.
2023-10-11 18:40:51.785  INFO [] [main] o.d.w.InstanceInitializerBean            : SourceWorkspaceId found, checking validity
2023-10-11 18:40:51.785  INFO [] [main] o.d.w.InstanceInitializerBean            : Cloning mode enabled, attempting to clone from 5d8e8691-75a1-4c76-99ad-8263d29c58c1 into …
```

[ AJ-1363] Make Cloning/startup multi-replica safe

---

service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilder.java
service/src/main/java/org/databiosphere/workspacedataservice/datarepo/HttpDataRepoClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/jobexec/JobContextHolder.java
service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/leonardo/HttpLeonardoClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/TokenContextUtil.java
service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/main/java/org/databiosphere/workspacedataservice/sourcewds/HttpWorkspaceDataServiceClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/HttpWorkspaceManagerClientFactory.java
service/src/test/java/org/databiosphere/workspacedataservice/jobexec/JobContextHolderTest.java
service/src/test/java/org/databiosphere/workspacedataservice/jobexec/QuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/TokenContextUtilTest.java

Reviewer: this PR has Java threading and `ThreadLocal` fun, please review that carefully as it is easy to get wrong!
In this PR:
* Add `JobContextHolder`, modeled after Spring's `RequestContextHolder`, to allow Quartz jobs to stash a token and allow that token to be retrieved from DAOs, just like we do for http requests
* Add `TokenContextUtil`, to centralize retrieval of auth tokens from either request context or job context
* Modify all REST DAOs, as well as ActivityEventBuilder, to use `TokenContextUtil` instead of their mostly copy/pasted custom logic
* Modify `ImportService` to use the current user's token for use in data import jobs (this will change to be a pet token in later PRs)
* Modify `QuartzJob` to read a token from the job's JobDataMap, stash it in job context, then clear …

AJ-1011: tokens in quartz jobs

---

service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java

[AJ-1373](https://broadworkbench.atlassian.net/browse/AJ-1373)
This PR takes the pet token fetched in https://github.com/DataBiosphere/terra-workspace-data-service/pull/363 and passes it as the auth token for an Import Job.
Reminder: …

AJ-1373 use pet token instead of bearer token for import

---

service/build.gradle

Snappy-java caused a [security vulnerability](https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/38); it was removed from java-pfb in https://github.com/DataBiosphere/java-pfb/pull/14, so this PR updates java-pfb to the version without snappy or its security problems.
Reminder:
After you manually …

AJ-1396 update java-pfb to version without snappy

---

service/src/main/java/org/databiosphere/workspacedataservice/sourcewds/HttpWorkspaceDataServiceClientFactory.java
service/src/test/java/org/databiosphere/workspacedataservice/sourcewds/HttpWorkspaceDataServiceClientFactoryTest.java

#370 mistakenly reverted the fix from #335.
This PR unreverts that, so WDS cloning should work again. Also includes a unit test.

AJ-1396: refix bearer token

---

.github/workflows/publish-pacts.yml
service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java

This is prefactoring work for [AJ-1234](https://broadworkbench.atlassian.net/browse/AJ-1234)
This pairs with https://github.com/broadinstitute/sam/pull/1234, where `sam` also renames its reference from `sam-consumer` to just `sam`.
* See [thread](https://broadinstitute.slack.com/archives/C043YJ40719/p1698068076950019) discussing the `-consumer` and `-provider` suffix anti-pattern.
* See [thread](https://broadinstitute.slack.com/archives/C043YJ40719/p1698241095600099) discussing the recommendation to use the helmchart name.
[AJ-1234]: https://broadworkbench.atlassian.net/browse/AJ-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1234: Use helmchart name for pact identifiers.

---

service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/sourcewds/CloneOlderWdsTest.java

Resolves an error when cloning earlier versions of WDS. The error is `BACKUPERROR (The required field `jobType` is not found in the JSON string`:
And is caused by https://github.com/DataBiosphere/terra-workspace-data-service/pull/358, which added `jobType` as a required field in the `BackupJob` model.
This PR makes `jobType` not required.

AJ-1396: allow cloning earlier versions of WDS

---

service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDao.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/TokenContextUtilTest.java
service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java

*sigh* #386 broke cloning by extracting a reusable function `WorkspaceManagerDao.enumerateResources()`.
This PR fixes that regression by ensuring the auth token is passed properly through `enumerateResources()`, plus unit tests to verify.

AJ-1429 clone failure

---

service/src/main/resources/application-local-cors.yml

When using the `local-cors` profile, WDS configures all controllers to allow CORS requests from any origin.
https://github.com/DataBiosphere/terra-workspace-data-service/blob/2b64d5afc105673c20024bb2a8aa51d88d53a644/service/src/main/java/org/databiosphere/workspacedataservice/controller/ControllerConfig.java#L25-L36
This allows using a local WDS with a local Terra UI.
However, the `status` and `version` endpoints are backed by Spring Boot Actuator and are not configured by this method. Thus, those two endpoints return CORS errors when requested by a local Terra UI.
This adds CORS configuration for Spring Boot Actuator endpoints to the `local-cors` profile.

[AJ-1166] Configure CORS for Actuator endpoints

---

.github/workflows/run-e2e-tests.yaml

Per [Gary's request](https://broadinstitute.slack.com/archives/C0475CH4ZV3/p1698944129546589?thread_ts=1698937206.372489&cid=C0475CH4ZV3), report e2e test failures to qa as well as to the AJ alerts channel

AJ-1428 alert e2e failures to #dsde-qa

---

.github/workflows/publish-pacts.yml

Make `publish_pacts` work with multiple pacts.
This is based on https://github.com/DataBiosphere/terra-workspace-data-service/pull/397
Co-authored-by: ichengchang
Co-authored-by: calypsomatic

AJ-1234: Make WDS publish multiple pacts.

---

service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java

This is the first of several test suites verifying interaction with WSM; this one focuses specifically on `createDataRepoSnapshotReference`.
Is paired with https://github.com/DataBiosphere/terra-workspace-manager/pull/1511

AJ-1234: Add `WsmPactTest`

---

service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java

The actual message differed slightly from expectation, so I've adjusted the regex to allow both forms of pluralization; what matters most is that the conflict was due to something relating to policies (and not one of the other myriad ways a 409 can be returned).

AJ-1234: Relax regex matching conflict message.

---

.github/workflows/run-e2e-tests.yaml

Per Gary's request, reverting this for now - until we can report only when we run this test in staging specifically.

Revert "AJ-1428 alert e2e failures to #dsde-qa"

---

.github/workflows/build-and-test.yml
build.gradle
service/build.gradle

This PR upgrades the [Sonarqube Gradle plugin](https://plugins.gradle.org/plugin/org.sonarqube).
It also switches from calling the `sonarqube` task to calling the `sonar` task, to address deprecation warnings:

AJ-1428: upgrade sonar plugin and task

---

service/src/main/resources/static/swagger/openapi-docs.yaml

Removes 4 models that were not used in our OpenAPI definition.
Gradle output after this PR:
```
> Task :client:openApiValidate
Validating spec /Users/davidan/work/src/terra-workspace-data-service/service/src/main/resources/static/swagger/openapi-docs.yaml
Spec is valid.
```
and before this PR:
```
> Task :client:openApiValidate
Validating spec /Users/davidan/work/src/terra-workspace-data-service/service/src/main/resources/static/swagger/openapi-docs.yaml
Spec has issues or recommendations.
Issues:
Unused model: RequestBodySearch
Unused model: SearchOperator
Unused model: SearchTerms
Unused model: StackTraceElement
Spec is valid.
```

AJ-1428: remove unused OpenAPI models

---

.github/actions/landing-zone-attach/action.yml
.github/workflows/run-e2e-tests.yaml

After chatting more with dev ops, it seems like it would be useful to have a landing zone attach retry immediately after failure. 
Reminder:
After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that this …

AJ-1465 - Add landing zone attach retry to e2e tests

---

.github/workflows/release-python-client.yml

Adjust pip to install wheel in the GAH vs expecting that it will be installed. 
Reminder:
The …

AJ-1482 - Fix python client action for wds python client

---

build.gradle
client/build.gradle
client/swagger.gradle
service/build.gradle

Update dependencies in the `:client` project to match versions in `:service` and/or to use latest versions.
This PR has a bunch of auto-formatter whitespace changes; you may want to ignore whitespace in the diff.

AJ-1463: update client dependencies too

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/DataTypeMapping.java
service/src/test/java/org/databiosphere/workspacedataservice/DataTypeInfererTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

Allow WDS to handle arrays of nulls. There were a couple places we didn't handle those - see code comments inline for explanations.

AJ-1489: handle arrays of nulls in PFB import

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbRecordConverter.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/PfbRecordConverterTest.java

Ticket: [AJ-1479](https://broadworkbench.atlassian.net/browse/AJ-1479)
This is a shallow fix to converting enum values that include special characters, per the pypfb docs: https://github.com/uc-cdis/pypfb/blob/master/docs/detailed_pfb_doc.md#enum
Depends on https://github.com/DataBiosphere/java-pfb/pull/16 which exposes the `convertEnum` function.
The deeper fix is tracked by [AJ-1288](https://broadworkbench.atlassian.net/browse/AJ-1288).
[AJ-1479]: https://broadworkbench.atlassian.net/browse/AJ-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AJ-1288]: https://broadworkbench.atlassian.net/browse/AJ-1288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Decode PFB enums

---

service/src/main/resources/applicationinsights.json

Adds two custom dimensions to application insights, which we can later use for segmenting or analysis. See https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#custom-dimensions for doc on custom dimensions.
The `service.version` and `workspaceId` dimensions in this PR mirror the `release` and `workspaceId` values we use for Sentry: https://github.com/DataBiosphere/terra-workspace-data-service/blob/0d6aab5b92431c3dd0eae90d13bf240fea7a3709/service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java#L54-L55. The name `service.version` is suggested by Azure in the doc link above.
See also https://github.com/broadinstitute/terra-helmfile/pull/4805, which sets the app insights role name.

AJ-1337: add custom dimensions to application insights metrics

---

.github/workflows/tag.yml

if you look at the [tag-job](https://github.com/DataBiosphere/terra-workspace-data-service/pull/431/files#diff-84dff8d1094ca39c02ac0e48d951ca22f4da29c76b50ae517f5bd2d50f94c2f6R27) tasks, you will see that this actually pushes a change into main that bumps the version (like [this](https://github.com/DataBiosphere/terra-workspace-data-service/commit/0d6aab5b92431c3dd0eae90d13bf240fea7a3709)) The rest of the tasks in this action all depend on the tag-job and therefore get the updated tag version. The java client tasks spins at the same time as the tag-job tasks without waiting and checks out the [repo](https://github.com/DataBiosphere/terra-workspace-data-service/blob/main/.github/workflows/publish-java-client.yml#L17), so it is not getting the commit with the updated version therefore …

AJ-1351 - Make java version wait for the version bump to ensure all versions align

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbRecordConverter.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/PfbRecordConverterTest.java

[AJ-1478](https://broadworkbench.atlassian.net/browse/AJ-1478): Respect additional datatypes when parsing PFBs.
Adds support for:
* `fixed`
* `bytes`
[AJ-1478]: https://broadworkbench.atlassian.net/browse/AJ-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1478: Add Avro `fixed` and `bytes` types.

---

.github/workflows/publish-java-client.yml

So the checkout step, if not specified, defaults to the latest [commit ](https://github.com/actions/checkout#checkout-v4)in the default branch (in our case main) at the time of action creation. This means that even though we wait for the version bump to complete, the checkout is done on main prior to the version bump commit. Specifying the branch should make it so it grabs the default commit from main vs the last commit when action is kicked off. 
after more reading, checking this in. ref should do the right thing and no other configuration like fetch-depth should  needed. 
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by …

AJ-1351 - Set specific branch for checkout event

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbRecordConverter.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/PfbStreamWriteHandler.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/SmallBatchWriteTestConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/PfbRecordConverterTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/PfbTestUtils.java
service/src/test/java/org/databiosphere/workspacedataservice/service/PfbStreamWriteHandlerTest.java

[AJ-1478](https://broadworkbench.atlassian.net/browse/AJ-1478): Respect additional datatypes when parsing PFBs.
Main change:
* Add support for Avro `record` type.
Also:
* Use `objectMapper` to stringify `map` attributes, instead of recursively serializing them.
* Test enums using parameterized test.
* Switch to using `GenericRecordBuilder`.
* Make `PfbRecordConverter` a Spring-managed `@Bean`.
[AJ-1478]: https://broadworkbench.atlassian.net/browse/AJ-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for Avro `record` type.

---

.github/workflows/publish-pacts.yml
.github/workflows/tag-0.3.0.yml
.github/workflows/tag.yml

Jira ticket: [QA-2191](https://broadworkbench.atlassian.net/browse/QA-2191)
More details on why we're doing this shifting:
- Create a ledger to trace published contracts through PR and merge commits. 
- To be consistent with Sherlock app versioning
Here's the expected behavior of the `semver` versioning in the context of contract tests
**Multiple Developers and Commits in a PR**
- Multiple developers can collaborate on the same pull request (PR).
- The PR can have multiple commits.
**Continuous Publishing of Contracts**
- WDS contracts from PRs are published to Pact Broker.
- The tagging mechanism is introduced to create a ledger of published contracts in Pact Broker. For PRs, the tag is appended with the commit hash. The contracts will be published using the new tag without hash.
- This …

QA-2191: Shift contract tests versioning to semver

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/AvroRecordConverter.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ParquetRecordConverter.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ParquetStreamWriteHandler.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/PfbRecordConverter.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/TdrSnapshotSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/PfbStreamWriteHandler.java
service/src/main/java/org/databiosphere/workspacedataservice/service/TwoPassStreamingWriteHandler.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/TdrManifestImportTable.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/DataImportException.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/TdrManifestImportException.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/Record.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/PfbQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/PfbRecordConverterTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/TdrManifestExemplarData.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/TdrManifestQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/TdrSnapshotSupportTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/PfbStreamWriteHandlerTest.java
service/src/test/resources/tdrmanifest/azure_small.json
service/src/test/resources/tdrmanifest/tdr_response_with_cycle.json

Highlights:
* bring in the `parquet-avro` library and supporting libraries, which allows reading Parquet files into Avro Java classes
* create new `ParquetRecordConverter`
* factor out a bunch of shared logic from `PfbRecordConverter` and `ParquetRecordConverter` into a new abstract base class `AvroRecordConverter`
* create new `ParquetStreamWriteHandler`, which mirrors `PfbStreamWriteHandler`
* create new `TdrManifestQuartzJob`
* factor out shared logic from `PfbQuartzJob` and `TdrManifestQuartzJob` into `TdrSnapshotSupport`

AJ-1013: TDR snapshot import

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/metrics/MetricsConfig.java
service/src/main/resources/application.yml
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/metrics/MetricsConfigTest.java

[AJ-1500](https://broadworkbench.atlassian.net/browse/AJ-1500)
For prometheus output format and usage, see:
https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#prometheus
Also:
* Allow any metrics starting with `MetricsConfig.ALLOWED_PREFIXES`;
this list currently includes everything enabled out of the box, plus a
`wds` prefix for our custom metrics.
* Deny everything not explicitly allowlisted.  This is to help manage egress cost.
* Add a tag to every gathered metric which includes WDS version.
Note: we're not actually tagging metrics with a workspace ID, as this
would be a high cardinality metric if aggregated globally.
Sample requests while running locally:
```
curl http://localhost:8080/prometheus
curl http://localhost:8080/prometheus?includedNames=jvm_memory_used_ …
```

AJ-1500: Enable Prometheus metrics

---

service/build.gradle

Two quick changes:
* exclude `io.netty` from the hadoop dependencies. This should resolve some Dependabot warnings.
* update TDR client to latest. This resolves a failure due to a model change in TDR responses.
Note: this does not resolve https://broadworkbench.atlassian.net/browse/AJ-1529. It eliminates the TDR error, but the updated TDR client in this PR is still not resilient to future model changes.
---
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when …

AJ-1514: exclude old netty from hadoop; update TDR client

---

service/src/main/java/org/databiosphere/workspacedataservice/service/JsonConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/TdrManifestQuartzJobTest.java
service/src/test/resources/tdrmanifest/extra_properties.json

turns out that AJ-1529 was not a problem with the TDR client; it was a problem with our own JSON parsing. Our `ObjectMapper` was not configured to ignore unknown properties, so when TDR added new properties to the manifest and we tried to parse them into an older version of the model which didn't have those properties, we hit an error.
This PR fixes that by setting `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` to false, and adding a unit test.
The unit test is in `TdrManifestQuartzJobTest` because that's our driving use case, but the setting applies to all JSON parsing.

AJ-1529: json parsing should be resilient to unknown properties

---

service/src/test/java/org/databiosphere/workspacedataservice/dataimport/TdrManifestQuartzJobTest.java

The rebase/merge in #444 lost a test annotation from #447; fixing.

AJ-1529: missing @Test annotation

---

service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilder.java
service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityModels.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/DeleteAttributeRequestException.java
service/src/main/resources/capabilities.json
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java

https://broadworkbench.atlassian.net/browse/AJ-1280
This adds an API that accepts delete requests at `{instanceId}/types/{v}/{type}/{attribute}` and deletes the given attribute from the given record type by dropping the column in the database. It rejects requests to delete the primary key column.

[AJ-1280] Add API for deleting an attribute from a record type

---

service/src/test/java/org/databiosphere/workspacedataservice/sam/MockSamClientFactory.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/MockSamUsersApi.java

This is in response to the following stacktrace printing 252 times in the logs during a full suite test run.  It apparently doesn't cause any test failures, but definitely makes them noisy (when test output is enabled) and distracts from actual issues or real stacktraces that might be happening.
To repro, set the following in build.gradle and rerun `./gradlew test`
```
testLogging {
showStandardStreams = true
}
```
This is a prefactor for tests being added as part of [AJ-1523](https://broadworkbench.atlassian.net/browse/AJ-1523), which was tripping this stacktrace.
```
500 INTERNAL_SERVER_ERROR "Error from Sam.getUserInfo REST target: Cannot invoke "org.broadinstitute.dsde.workbench.client.sam.api.UsersApi.getUserStatusInfo()" because the return value of …
```

Add `MockSamUsersApi`

---

service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/RecordTypeSchema.java
service/src/test/java/org/databiosphere/workspacedataservice/service/model/RecordTypeSchemaTest.java

Addressing @davidangb's [comment](https://github.com/DataBiosphere/terra-workspace-data-service/pull/455#discussion_r1450553757) on #455.
> Thinking out loud: since there's a decent amount of duplication between validateRenameAttribute and validateDeleteAttribute, I'd love to see these encapsulated as methods of RecordTypeSchema. ...

[AJ-1282] Refactor edit attribute validation

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/AvroRecordConverter.java

Won't do [AJ-1537](https://broadworkbench.atlassian.net/browse/AJ-1537).
From ticket comment:
>We encountered raw bytes in the test data we were using, but when adjusting the test data to remove the synthetic data that included the wide variety of potential datatypes, and only testing with the unadulterated V2F data, the weird types didn’t occur naturally.  Thus for the time being we’ll close this ticket as won't-do until we have reason to believe the current display is problematic for real use cases.
[AJ-1537]: https://broadworkbench.atlassian.net/browse/AJ-1537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove references to closed Jira ticket.

---

service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestUtils.java

This encapsulates all the `@Autowired` fields required for `buildPfbQuartzJob`, intended to lower the resistance the tests provide when modifying the `PfbQuartzJob` constructor.
Inspired by https://github.com/DataBiosphere/terra-workspace-data-service/pull/461#discussion_r1457949165 and done as a prefactor for the changes needed by [AJ-1441](https://broadworkbench.atlassian.net/browse/AJ-1441).
[AJ-1441]: https://broadworkbench.atlassian.net/browse/AJ-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extract `PfbTestUtils`

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/RecordTypeSchema.java
service/src/test/java/org/databiosphere/workspacedataservice/service/model/RecordTypeSchemaTest.java

Small refactor to add a more convenient API for getting a specific attribute's schema.

[AJ-1279] Add RecordTypeSchema.getAttributeSchema

---

service/src/main/java/org/databiosphere/workspacedataservice/service/model/DataTypeMapping.java
service/src/test/java/org/databiosphere/workspacedataservice/service/model/DataTypeMappingTest.java

For data type conversion, it's sometimes useful to check if a DataTypeMapping is `<type>` or `ARRAY_OF_<type>`. For example, `STRING` or `ARRAY_OF_STRING`. To make this more convenient, this adds a `getBaseType` method to DataTypeMapping. For array types, this returns the element type. For non-array types, it returns the type itself.
Since this is similar to the inverse of the existing `DataTypeMapping.getArrayTypeForBase`, I refactored it as well so that both methods use the same type to array type mapping, which makes it easier to keep them in sync if new types are added.

[AJ-1279] Add DataTypeMapping.getBaseType method

---

.github/actions/landing-zone-attach/action.yml
.github/workflows/run-e2e-tests.yaml

Reminder:
The terra-helmfile PR merge will then generate a PR in …

Update LZ input

---

service/src/main/java/org/databiosphere/workspacedataservice/service/model/AttributeSchema.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/model/AttributeSchemaTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/model/RecordTypeSchemaTest.java

Addressing @jladieu's comment here: https://github.com/DataBiosphere/terra-workspace-data-service/pull/463#discussion_r1459406188.
In tests, AttributeSchema is frequently instantiated with a null value for `relatesTo` and occasionally with a null value for `datatype`. This adds alternate constructors that allow omitting null values and also allow passing a DataTypeMapping instead of a string for the `datatype` argument. This clarifies the meaning of the second argument and reduces the chance of a typo causing a test failure due to an invalid data type.

[AJ-1279] Add alternate constructors for AttributeSchema

---

.vscode/settings.json

As part of enforcing consistent formatting, we have VS Code configured to have the [Spotless Gradle extension](https://marketplace.visualstudio.com/items?itemName=richardwillis.vscode-spotless-gradle) fix issues on save.
The November 2023 update to VS Code changed the format of this setting.
https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto
This updates the setting to the new format so that it doesn't become noise in another PR.

Update VS Code formatting setting

---

service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/metrics/ObservationConfig.java

This intends to make the default `ObservationRegistry` automatically wired up to the same `MeterRegistry` provided by springboot.

Add `ObservationConfig`

---

build.gradle

Upgrade Spring Boot 3.2.1 -> 3.2.2, which includes an upgrade to Spring Framework 6.1.3.
Release notes: https://github.com/spring-projects/spring-boot/releases/tag/v3.2.2
Should resolve a Dependabot issue.

AJ-1533: Spring Boot 3.2.2 / Spring Framework 6.1.3

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

Following up on https://github.com/DataBiosphere/terra-workspace-data-service/pull/472#discussion_r1465451372...
This adds tests that show the SQL expression generated for each attribute data type conversion.

[AJ-1279] Add tests for SQL expressions for data type conversions

---

service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

This is maintenance cleanup/refactoring: [AJ-1533](https://broadworkbench.atlassian.net/browse/AJ-1533), followup from https://github.com/DataBiosphere/terra-workspace-data-service/pull/476#discussion_r1473077717
Clean up `RecordDaoTest`
* Get rid of unnecessary `new HashMap<>(...)` throughout.
* Prefer `RecordAttributes.empty()` to `new RecordAttributes(Map.of())`.
* Prefer `Collections.emptyMap()` to `Map.of()`.
Note: `Collections.emptyMap()` and `Map.of()` are not equivalent, see: https://stackoverflow.com/questions/46404933/map-of-vs-collections-emptymap
While arguably `Map.of()` is preferred where possible, I think `emptyMap()` is more readable and in tests I think readability matters more unless `Map.of()`'s behavior is explicitly relevant to what's being tested.
[AJ-1533]: …

Clean up `RecordDaoTest`

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresBackupDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresCloneDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresJobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresRestoreDao.java
service/src/main/java/org/databiosphere/workspacedataservice/generated/GenericJobServerModel.java
service/src/main/java/org/databiosphere/workspacedataservice/generated/JobV1ServerModel.java
service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/InstanceId.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/job/Job.java
service/src/main/resources/liquibase/changelog.yaml
service/src/main/resources/liquibase/changesets/20240131_add_instance_to_job.yaml
service/src/main/resources/static/swagger/apis-v1.yaml
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockBackupRestoreDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCloneDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/PostgresJobDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/InstanceIdTest.java

* Add an `instance_id` column to the `sys_wds.job` table
* When saving an async job to the `sys_wds.job` table, persist the instance id to the new `instance_id` column
* Add `instanceId` to the `JobV1` model in swagger and our clients. Since this is additive, and not required, it should be a non-breaking change. Please check my assumption here!
* Add a new `InstanceId` model class which wraps UUID. How do folks feel about this? I think it could be good to start using this in more places - as well as add `WorkspaceId` and `JobId` classes

AJ-1561: Associate import jobs with their containing instance

---

service/src/main/java/org/databiosphere/workspacedataservice/metrics/MetricsConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordService.java
service/src/test/java/org/databiosphere/workspacedataservice/metrics/MetricsConfigTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordServiceTest.java

Ticket [AJ-1548](https://broadworkbench.atlassian.net/browse/AJ-1548): Standardize tags for metrics.
* Tags describing generic non-wds specific concepts don't need a `wds` prefix, so we drop the `wds_` prefix from `wds_version`.
* All services should provide a `service` tag.  This allows aggregation and breakdown by service dimensions.
* Custom metrics should be prefixed with `wds`.
* High cardinality labels should be annotated as such to prevent combinatorial explosion.
[AJ-1548]: https://broadworkbench.atlassian.net/browse/AJ-1548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1548: Update custom metrics

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java

After moving past the basic data types, it's become clear that it's simpler and clearer to explicitly list supported data type conversions vs assuming that any supported data type can be converted to any other supported data type and listing exceptions to that.

[AJ-1279] Refactor check for supported data type conversion

---

service/src/test/java/org/databiosphere/workspacedataservice/controller/CapabilitiesControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/CorsLiveMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/CorsLocalMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/ImportControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/MockMvcTestBase.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java

Use `{to,from}Json` in MVC tests.
This shorthand intends to eliminate some of the clumsy and repetitive interaction with `ObjectMapper` and `MvcResult`.
Context:  https://github.com/DataBiosphere/terra-workspace-data-service/pull/479#discussion_r1476545183
This is opportunistic maintenance / refactoring to test code only: [AJ-1533](https://broadworkbench.atlassian.net/browse/AJ-1533)
[AJ-1533]: https://broadworkbench.atlassian.net/browse/AJ-1533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use `{to,from}Json` in MVC tests.

---

service/src/main/java/org/databiosphere/workspacedataservice/service/InstanceService.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/InstanceId.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/WorkspaceId.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceNoPermissionSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceNoWorkspaceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamExceptionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceTest.java

Create a new method - `InstanceService.getWorkspaceId()` - which returns the proper workspace to use when authenticating to an instance. As compared to https://github.com/DataBiosphere/terra-workspace-data-service/pull/489, this PR makes no changes to the db. Instead, it relies heavily on assumptions which are _currently_ safe:
* in Azure, we deploy WDS per-workspace and set a `$WORKSPACE_ID` value for each deployment
* in the upcoming cWDS, since data tables will continue to be powered by Rawls, we can assume `instanceId=workspaceId`.
I really want to break that last assumption, but I don't want to break it at the expense of convoluted code which could incur bugs. So, here's a simple solution.

AJ-1591: no-db solution for instance-to-workspace association

---

service/src/main/resources/logback-spring.xml

Registers a no-op logback status listener to prevent the ~75 lines of logback configuration details that are logged at every startup.
See https://logback.qos.ch/manual/configuration.html#dumpingStatusData
This eliminates the log lines that include, for instance:
```
10:08:05,572 |-INFO in ch.qos.logback.classic.util.ContextInitializer@40258c2f - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
10:08:05,574 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
10:08:05,574 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
10:08:05,574 |-INFO in ch.qos.logback.classic.util.ContextInitializer@40258c2f - …
```

AJ-1556: quiet down logback status during startup

---

build.gradle
service/build.gradle

Maintenance Ticket: https://broadworkbench.atlassian.net/browse/AJ-1556
Finding: https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/65
CVE: https://nvd.nist.gov/vuln/detail/CVE-2023-51074
[AJ-1556]: https://broadworkbench.atlassian.net/browse/AJ-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1556 Bump `json-path` to 2.9.0 for dependabot.

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/recordstream/TsvStreamWriteHandler.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java

This is prefactoring for [AJ-1563](https://broadworkbench.atlassian.net/browse/AJ-1563).  The primary key isn't really optional once batch writing has begun, so we resolve the optional earlier in the callstack for JSON stream and TSV stream.
[AJ-1563]: https://broadworkbench.atlassian.net/browse/AJ-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1563 Make primaryKey non-optional during batch write.

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

Currently, WDS supports inserting records with attributes that differ only in case. For example, a record with two attributes: "Value" and "value". Such records are stored correctly in the database, but when queried through WDS, the same value will be returned for both attributes.
For example, a record inserted as `{"value": "foo", "Value": "bar"}` would be returned as `{"value": "foo", "Value": "foo"}`.
This is because of an issue in RecordRowMapper. It gets column values from the ResultSet by column name.
From [java.sql.ResultSet's documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/ResultSet.html):
> Column names used as input to getter methods are case insensitive. When a getter method is called with a column name and several columns have the same name, …

[AJ-1605] Make RecordRowMapper sensitive to attribute case

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/recordstream/PrimaryKeyResolver.java
service/src/main/java/org/databiosphere/workspacedataservice/recordstream/StreamingWriteHandlerFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/recordstream/TsvStreamWriteHandler.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/DataImportException.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/TdrManifestImportException.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/SmallBatchWriteTestConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java

This is prefactoring for [AJ-1563](https://broadworkbench.atlassian.net/browse/AJ-1563). 
Pulling the creation of `StreamingWriteHandler` out to a factory makes it simple enough to create format-specific subclasses at each callsite.
This simplifies `BatchWriteService` by eliminating its concern about to handle the particulars of each format of input.
[AJ-1563]: https://broadworkbench.atlassian.net/browse/AJ-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extract `StreamingWriteHandlerFactory`

---

service/src/main/java/org/databiosphere/workspacedataservice/InstanceInitializerBean.java

My guess it was left from the artifact of us hoping to save the blob into source container - but at this time we do everything in the destination to ensure the user indeed has write access to the blob container. 
Reminder: …

AJ-1556 - Correct misleading error message about cloning

---

service/src/main/java/org/databiosphere/workspacedataservice/service/model/RelationCollection.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

Tiny developer experience improvement I wished for in #503.
Several RecordDao tests an empty RelationCollection constructed with `new RelationCollection(Collections.emptySet(), Collections.emptySet())`. This adds a `RelationCollection.empty()` shortcut for that.

[AJ-1605] Add helper to create empty RelationCollection

---

service/src/integrationTest/java/org/databiosphere/workspacedataservice/startup/InstanceInitializerCloneTest.java
service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/java/org/databiosphere/workspacedataservice/config/InstanceProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/config/TenancyProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/config/TwdsProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/startup/InstanceInitializer.java
service/src/main/java/org/databiosphere/workspacedataservice/startup/InstanceInitializerBean.java
service/src/main/java/org/databiosphere/workspacedataservice/startup/InstanceInitializerConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/startup/StartupConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/config/TenancyPropertiesControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/config/TenancyPropertiesDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/config/TenancyPropertiesNoProfileTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/InstanceInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/InstanceInitializerNoWorkspaceIdTest.java

Some more prefactoring to help out eventually with #489 
In this PR:
* create a new "startup" package
* move InstanceInitializer* classes into the startup package
* expand our ConfigurationProperties classes to include the top-level `twds` property hierarchy and, importantly, the `twds.instance.workspace-id` property (which is populated from the `$WORKSPACE_ID` env var)
* add a new `StartupConfig` class in the startup package, which is responsible for performing some on-startup validations including validating the `twds.instance.workspace-id` property
NOT in this PR to save scope:
* I did not attempt to consolidate InstanceInitializer stuff into StartupConfig, but I think that would be possible if we wanted to do it
* I did not attempt to update any other classes that read from or require …

AJ-1591: startup validation

---

service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java
service/src/test/java/org/databiosphere/workspacedataservice/service/DataTypeInfererTest.java

This is prefactoring for [AJ-1563](https://broadworkbench.atlassian.net/browse/AJ-1563).  Some of the internal APIs used by `BatchWriteService` can be tightened up with a little bit of refactoring in internal method signatures.
The commits are self-contained and might be easier to review individually.
[AJ-1563]: https://broadworkbench.atlassian.net/browse/AJ-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1563 Clean up internal APIs

---

.github/workflows/submit-dependencies.yml

The action we were using for dependency submission - https://github.com/marketplace/actions/gradle-dependency-submission - is deprecated. This switches us to use the recommended solution which is provided directly by gradle.
I manually kicked off the action in this PR at https://github.com/DataBiosphere/terra-workspace-data-service/actions/runs/7889889650/job/21530809619 and saw it succeed.

AJ-1556: switch to gradle-maintained dependency submission

---

.github/workflows/build-and-integration-test.yml
.github/workflows/build-and-test.yml
.github/workflows/publish-docker.yml
.github/workflows/publish-java-client.yml
.github/workflows/publish-pacts.yml
.github/workflows/release-python-client.yml
.github/workflows/run-e2e-tests.yaml

Cleans up our GHAs. In this PR:
1. Update `actions/setup-java` to `v4` wherever it is out of date
2. Update `actions/checkout` to `v4` wherever it is out of date
3. Add `gradle/actions/setup-gradle@v3` wherever we use gradle. See https://github.com/marketplace/actions/build-with-gradle for more info; this action was not available when 
4. Remove `setup-java`'s gradle cache in favor of the one in `setup-gradle`
5. Remove explicit caching of gradle stuff via `actions/cache` in favor of the one in `setup-gradle`
6.  Change "Upload Test Reports" steps to only upload reports if tests failed, to save time … does anyone look at these?

AJ-1556: streamline github workflows

---

.github/workflows/publish-app-version.yml
.github/workflows/publish-docker.yml
.github/workflows/publish-version.yml
.github/workflows/tag.yml

https://broadworkbench.atlassian.net/browse/AJ-1618
A bit of "prefactoring" for AJ-1618... This splits the creation of a terra-helmfile PR out of the publish-docker workflow into a separate publish-version workflow (suggestions for a better name welcome). This refines publish-docker to its stated purpose ("Publish Docker Images to GCR and ACR") and limits the BroadBot token to a smaller workflow.
The intent is to then add a second job to the publish-version workflow to notify Sherlock of a new cWDS version.

[AJ-1618] Split terra-helmfile PR out of publish-docker workflow

---

.github/workflows/publish-app-version.yml
.github/workflows/tag.yml

https://broadworkbench.atlassian.net/browse/AJ-1420
Running the `tag` workflow asks for the ID of a ticket. It uses that JIRA ticket ID to create a PR to terra-helmfile.
Currently, if no valid ticket ID is found, the `find-jira-id` step outputs "missing". If the terra-helmfile PR step sees that the JIRA ID is "missing", it prints a message and exits cleanly, which results in the job showing as successful.
This changes it so that if no ticket ID is found, the `find-jira-id` step fails, which would make the terra-helmfile PR job show as failed.
It also changes the default placeholder for the JIRA ID input field to "AJ-###".

[AJ-1420] Fail terra-helmfile PR job if no JIRA ticket provided

---

.github/dependabot.yml

https://broadworkbench.atlassian.net/browse/AJ-1635
Seeing that we've accumulated several Dependabot alerts, this sets up automated Dependabot updates using the same configuration that we use for [DataBiosphere/java-pfb](https://github.com/DataBiosphere/java-pfb/blob/main/.github/dependabot.yml).

[AJ-1635] Configure Dependabot updates

---

.github/workflows/publish-app-version.yml

https://broadworkbench.atlassian.net/browse/AJ-1618
Add jobs to the `publish-app-version` workflow (run as part of the `tag` workflow) to report a new cWDS version to Sherlock and deploy it to dev.
Followed instructions in Google Doc linked from ticket.

[AJ-1618] Report new cWDS version to Sherlock and deploy to dev on tag

---

service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvDownloadTest.java

`getStatusCodeValue()` is deprecated.
Maintenance/cleanup.  Eliminates this error:
```
Note: .../path/to/TsvDownloadTest.java uses or overrides a deprecated API.
```

AJ-1556 Prefer `getStatusCode()`.

---

service/build.gradle

I noticed we hadn't updated java-pfb in a while, it's been getting a number of security updates that we probably want to include.
Should we have a better process for keeping java-pfb up-to-date?  Can/Should we tie it to a major version instead of something specific?
Reminder:
After you manually trigger the github action (and it …

AJ-1556 update java-pfb

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RecordSinkFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/WdsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsource/ParquetRecordSource.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsource/PfbRecordSource.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsource/RecordSource.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordService.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java

This is another round of refactoring to simplify the internal interfaces of `BatchWriteService` in prep for making some more tweaks to support [AJ-1589](https://broadworkbench.atlassian.net/browse/AJ-1589).
For easiest review, I recommend scanning the commits individually.
These commits largely attempt to:
- shrink the size of method argument lists the `RecordSink` API to eliminate cases where implementation classes just end up ignoring the arguments because they're not relevant
- shrink the overall size of `consumeWriteStream` to get it a little bit closer to fitting on a page.
[AJ-1589]: https://broadworkbench.atlassian.net/browse/AJ-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1589 Simplify `BatchWriteService` internal APIs.

---

service/src/test/java/org/databiosphere/workspacedataservice/dao/QuartzSchedulerDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceDataPlaneTest.java

add `@DirtiesContext` to more unit tests to ensure we don't create too many `DataSource` beans and therefore run out of Postgres connections
Out of scope: removing `@DirtiesContext` from any tests that don't need it. This could improve test timing, but I would like to do that work in a later PR.

AJ-1649: add @DirtiesContext to tests that need it

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/DataTypeMapping.java
service/src/main/java/org/databiosphere/workspacedataservice/tsv/TsvDeserializer.java
service/src/test/java/org/databiosphere/workspacedataservice/TestUtils.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/model/DataTypeMappingTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvJsonArgumentsProvider.java

https://broadworkbench.atlassian.net/browse/AJ-1611
Currently, WDS does not support top level arrays in JSON fields. This adds support for them by implementing an `ARRAY_OF_JSON` type.
Replacement for #508 based on https://github.com/DataBiosphere/terra-workspace-data-service/pull/508#issuecomment-1941879831.

[AJ-1611] Support top level arrays in JSON fields

---

build.gradle
service/build.gradle

Addresses a critical security vulnerability _which we are not vulnerable to_ by updating the postgres dependency from 42.6.0 to 42.6.1.
> SQL injection is possible when using the non-default connection property preferQueryMode=simple in combination with application code that has a vulnerable SQL that negates a parameter value.
> There is no vulnerability in the driver when using the default query mode. Users that do not override the query mode are not impacted.
But, let's upgrade anyway to stay on top of it.

AJ-1649: postgres dependency to 42.6.1

---

service/src/integrationTest/java/org/databiosphere/workspacedataservice/service/BackupRestoreServiceFailureIntegrationTest.java
service/src/integrationTest/java/org/databiosphere/workspacedataservice/service/RestoreServiceIntegrationTest.java
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilderTest.java
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/LogStatementTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/SmallBatchWriteTestConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsource/JsonRecordSourceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/SamDaoInvalidWorkspaceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordRequestTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordResponseTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvErrorMessageTest.java

Per Sonar java:S5786: JUnit5 test classes and methods should have default package visibility

AJ-1629: Drop unneeded `public` modifier from tests.

---

service/src/test/java/org/databiosphere/workspacedataservice/common/ConfigurationExceptionDetector.java

This is a followup test bugfix to [AJ-1629](https://broadworkbench.atlassian.net/browse/AJ-1629).
Specifically, the `ConfigurationExceptionDetector` would throw a `NullPointerException` for test failures where the actual value was `null`.  This should prevent that.
[AJ-1629]: https://broadworkbench.atlassian.net/browse/AJ-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1629 Bugfix `ConfigurationExceptionDetector`

---

service/src/main/java/org/databiosphere/workspacedataservice/service/RecordService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/ConflictingPrimaryKeysException.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributes.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java

PUT and PATCH requests to `/{instanceId}/records/{version}/{recordType}/{recordId}` specify the record's primary key value in the URL via the `recordId` path parameter and, for PUT requests, the `primaryKey` query parameter. However, they may also specify the primary key value in the attributes in the request body.
Currently, WDS doesn't handle this consistently.
- Creating a new record, whether or not the two primary key values match, the request succeeds.
- Updating an existing record, whether or not the two primary key values match, results in an SQL error.
This updates that endpoint to require that, if a primary key value is specified in the request body, it must match the one in the URL. It they do match, the request now succeeds instead of producing an SQL error.

[AJ-1652] Handle primary keys specified in request body

---

.github/workflows/run-e2e-tests.yaml

This should address intermittent errors in our e2e tests. We just had one last night, and the error message was:
```
--name: "wds-8017616954-1-dev," is not a valid environment name: environment name
must match regular expression \\A[a-z][a-z0-9]*(-[a-z0-9]+)*\\z"
```
if you look very carefully at the error message, you'll see that the name `"wds-8017616954-1-dev,"` _has a trailing comma_ which makes it invalid.
The reason this is so intermittent is that it only happens in the retry case of creating a bee.

AJ-1649: remove extraneous comma

---

service/src/test/java/org/databiosphere/workspacedataservice/common/TestBase.java

Filing this under maintenance as it's independent of any active spring work [AJ-1649](https://broadworkbench.atlassian.net/browse/AJ-1649).
The primary offender was `CollectionServiceSamExceptionTest` which would take upward of 30 seconds to complete.  However, the intent of doing this in the base class is to bake in the intent more broadly to hopefully prevent future regressions.
Before:
BUILD SUCCESSFUL in 2m 53s
After:
BUILD SUCCESSFUL in 2m 18s
[AJ-1649]: https://broadworkbench.atlassian.net/browse/AJ-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1649 Limit impact of retries on test runtime.

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/CapabilitiesController.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/CloningController.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/ImportController.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/JobController.java
service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/test/java/org/databiosphere/workspacedataservice/annotations/AnnotatedApisTest.java

Ticket: https://broadworkbench.atlassian.net/browse/AJ-1562
This PR adds `@DataPlane` and or `@ControlPlane` to our `@RestController`s and adds a test to make sure at least one of those is on all of our `@RestController`s
-----------------------
Reminder:
After you manually trigger the github action (and it completes with no …

Enforce Platform for @RestControllers

---

build.gradle
service/build.gradle

This supersedes #578.
Update Spring Boot 3.2.2 -> 3.2.3. See:
* https://spring.io/blog/2024/02/22/spring-boot-3-2-3-available-now
* https://github.com/spring-projects/spring-boot/releases/tag/v3.2.3.
Because Spring Boot updated dependencies in this release, we can remove some of our overrides.
I did not see anything else in the release notes that needs attention.

AJ-1649: update to Spring Boot 3.2.3

---

service/build.gradle

* Bump org.webjars.npm:swagger-ui-dist from 5.11.7 to 5.11.8; supersedes #579
* Bump com.google.mug:mug from 6.6 to 7.1; supersedes #576
* Bump com.azure:azure-identity-extensions from 1.1.12 to 1.1.13; supersedes #575
* remove com.azure:azure-identity as a direct dependency, since azure-identity-extensions pulls it in transitively

AJ-1649: dependency updates

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/JobController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/JobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresJobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/JobService.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceDataPlaneTest.java

https://broadworkbench.atlassian.net/browse/AJ-1638
Currently, listing jobs without providing a `statuses` query parameter results in a 500 errors. This fixes that so that the query parameter is not required.
This also refactors `JobDao.getJobsForCollection` to make the `statuses` argument an `Optional`. I think that more clearly represents the intent of an optional statuses filter vs using an empty list to mean return all statuses.

[AJ-1638] Do not require statuses query parameter for list jobs endpoint

---

service/src/main/java/org/databiosphere/workspacedataservice/startup/StartupConfig.java
service/src/main/resources/application.yml

[AJ-1629](https://broadworkbench.atlassian.net/browse/AJ-1629): When starting WDS without a data-plane or control-plane profile, crash with a message explaining that they are needed, rather than letting Spring fail due to bean misconfiguration a bit later on.
To cause error:
```
./gradlew bootRun
```
Expect crash with stacktrace starting with:
`org.databiosphere.workspacedataservice.config.ConfigurationException: This deployment requires at least one of the following active profiles: [data-plane, control-plane]`
To make error not happen:
```
./gradlew bootRun --args='--spring.profiles.active=data-plane'
```
[AJ-1629]: https://broadworkbench.atlassian.net/browse/AJ-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1629: Fail with explanation on missing profile.

---

service/src/main/resources/static/swagger/apis-v1.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerTest.java

Tweak swagger-ui so it generates the `statuses` parameter using a single comma-delimited value instead of multiple duplicate query params.
This *only* affects the urls that swagger-ui generates. It doesn't change what's allowed by the API, as illustrated by unit tests. But since end users sometimes rely on swagger-ui for API documentation, it's good to give them the structure we prefer.
Before:
After:

AJ-1560: statuses param

---

.github/workflows/submit-dependencies.yml

The cache in the `setup-java` action is redundant and conflicts with caches from `dependency-submission`. Remove it.
I hypothesize this out-of-date cache is giving us false positive Dependabot warnings. Hopefully by removing it our warnings clear up.
I was able to see that the `dependency-submission` action is reporting stuff simply because it's on the classpath - hypothesis is that a stale cache left stuff on the classpath that is not actually in our current list of dependencies.

AJ-1649: dependency submission should not use setup-java cache

---

service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamClientFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/TokenContextUtil.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/package-info.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/BearerToken.java
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilderTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/MockSamClientFactory.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/MockStatusApi.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/TokenContextUtilTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceNoPermissionSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamExceptionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/PermissionsStatusServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/BearerTokenTest.java

Prefactor for [AJ-1633](https://broadworkbench.atlassian.net/browse/AJ-1633)
* Declare the package as `@NonNullApi`; this will make the IDE provide warnings to guide clients to deal with null-safety.
* Make all methods expect a `BearerToken` rather than a String.
* For non-authenticated usages, it's still possible to pass in `BearerToken.empty()`.
* Require a `BearerToken` on the `getStatusApi` call, even though it's not needed.  This is for consistency.
Next steps are to propagate this strong typing upward into the `SamDao` and friends, all in service to making it easier to further refactor & refine to wire through a `WorkspaceId` for auth purposes.
[AJ-1633]: https://broadworkbench.atlassian.net/browse/AJ-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

AJ-1633: Strengthen `SamClientFactory` API typing.

---

service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilder.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/MisconfiguredSamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/SamDaoInvalidWorkspaceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceDataPlaneTest.java

Prefactors for [AJ-1633](https://broadworkbench.atlassian.net/browse/AJ-1633), broken into discrete commits for easier review (one per bullet).
* The single `String` parameter of `hasWriteWorkspacePermission` was named as though it were an auth token, but all places (except one) where it was used (in tests and prod) it was being treated as a workspaceId.  This clarifies the parameter name, and wires it through correctly to be used for the auth check.
* Strengthen `SamDao` API typing by requiring a `BearerToken` instead of a `String` for `token`.
* Strengthen `SamDao` API typing by requiring a `WorkspaceId` instead of a `String` for `workspaceId`.
[AJ-1633]: https://broadworkbench.atlassian.net/browse/AJ-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

AJ-1633: Make `SamDao` API require and use stronger types.

---

.github/workflows/submit-dependencies.yml

This change _should_ tell Dependabot to only alert on dependencies in the `runtimeClasspath` - i.e. it won't alert on build-time dependencies, test dependencies, etc.
Is this what we want? Would you prefer to see all dependencies in the Dependabot list?
Caveat: because dependency submission only works on the `main` branch, I can't test this 100% until it's merged. But, from looking at debug logs on manual GHA runs, I am hopeful this helps.

AJ-1649: Dependabot only considers the runtime classpath

---

service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceGetWorkspaceIdTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceDataPlaneTest.java

[AJ-1630](https://broadworkbench.atlassian.net/browse/AJ-1630): In the data-plane, when `twds.tenancy.allow-virtual-collections` is false, `CollectionService` should throw an error if a collection is missing.
[AJ-1630]: https://broadworkbench.atlassian.net/browse/AJ-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1630: Throw error on missing collection

---

service/src/main/resources/static/swagger/cwds-api-docs.yaml

[AJ-1668](https://broadworkbench.atlassian.net/browse/AJ-1668)
swagger-ui for cwds does not pop up a dialog to enter your bearer token. This PR fixes that.
[AJ-1668]: https://broadworkbench.atlassian.net/browse/AJ-1668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1668: cwds openapi spec needs securitySchemes

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresJobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamAuthorizationDaoFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/main/resources/application-local.yml
service/src/main/resources/logback-spring.xml

[AJ-1634](https://broadworkbench.atlassian.net/browse/AJ-1634)
Multiple logging-related changes in this PR:
1. Reduce logging volume from DEBUG to INFO most everywhere
2. Configure `DispatcherServlet` to continue to log at DEBUG so we get request URLs and response codes
3. Elevate a couple log messages to INFO from DEBUG so they're still visible
4. Reorganize `logback-spring.xml` to reduce duplication and nesting
5. When running with the `local` profile, re-enable the default Spring boot color-coded logs for developer goodness
NOT in this PR: filtering out /status/liveness and /status/readiness from the logs. This is somewhat involved, and I hope to tackle that in a follow-on PR. Is this worth doing?
`SPRING_PROFILES_ACTIVE=dev,control-plane gw bootRun`: …

AJ-1634: reduce log volume, refactor logging config

---

service/src/main/resources/application.yml

[AJ-1565](https://broadworkbench.atlassian.net/browse/AJ-1565)
Configure Quartz to attempt to wait for jobs to complete before WDS shuts down. This does not fully guarantee that jobs in flight will succeed.
When shutting down a pod, k8s will first send a SIGTERM. WDS will receive that, and after this PR will try to finish out Quartz jobs before going down. However, k8s will only wait a certain amount of time and then send a SIGKILL, which will interrupt anything in flight.
To more fully complete AJ-1565, we probably want to (in a separate PR):
[AJ-1565]: https://broadworkbench.atlassian.net/browse/AJ-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1565: wait for Quartz jobs to complete on shutdown

---

service/src/main/java/org/databiosphere/workspacedataservice/pubsub/ImportPubSub.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/PubSub.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/test/java/org/databiosphere/workspacedataservice/pubsub/ImportPubSubTest.java
service/src/test/java/org/databiosphere/workspacedataservice/pubsub/MockPubSub.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java

This is a PR into #596, not into `main`.
The pubsub library works in futures, not in synchronous calls. This is why tests look like they run forever. This PR handles the future and waits for it to complete, turning it into a synchronous call.
Note that the `ImportPubSubTest` is now failing, because publishing fails. Previously we never got the notification that publishing was failing.

AJ-1586: pubsub needs to handle futures

---

service/build.gradle

https://broadworkbench.atlassian.net/browse/DC-839
With the [Spring Boot 3 Upgrade](https://github.com/DataBiosphere/jade-data-repo/pull/1581) for data repo, we're switching back to only publishing to one Jakarta backed client. This PR moves your references to the jakarta client back to the main data repo client and bumps to the latest version. This is an effort to alleviate any confusion around upgrading past the last supported datarepo-jakarta-client version.
____
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/wor …

DC-839: Move references back to datarepo-client; Upgrade to latest

---

service/src/main/java/org/databiosphere/workspacedataservice/config/TenancyProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamAuthorizationDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamAuthorizationDao.java
service/src/main/java/org/databiosphere/workspacedataservice/sam/SamAuthorizationDaoFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/main/resources/application-control-plane.yml
service/src/main/resources/application-data-plane.yml
service/src/main/resources/application.yml
service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDaoConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/MockSamAuthorizationDao.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceGetWorkspaceIdTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceNoPermissionSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamExceptionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerNoWorkspaceIdTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvErrorMessageTest.java

For [AJ-1633](https://broadworkbench.atlassian.net/browse/AJ-1633), branch based off https://github.com/DataBiosphere/terra-workspace-data-service/pull/594
* Stop checking `delete` workspace permission to determine if it's ok to delete a collection, instead check `write` workspace.
* Eliminate redundant `SamAuthorizationDao` methods which are subsumed by `SamAuthorizationDao#hasWriteWorkspacePermission`
* Adjust `SamPactTest` to no longer verify `delete` interaction and instead verify previously untested `read` interaction.
* Adjust a bunch of tests which were verifying the safety check behavior which is now removed.
* This allows wiring up `deleteCollection` to correctly look up the `WorkspaceId` for the collection and then check for `write` permission.
* Add …

AJ-1633: Finish wiring up `deleteCollection`

---

README.md
scripts/render-config.sh
service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
service/src/main/resources/application-alpha.yml
service/src/test/java/org/databiosphere/workspacedataservice/SentryInitializerTest.java

https://broadworkbench.atlassian.net/browse/AJ-1681
The alpha environment has been/is being removed; we don't need config for it anymore.
Reminder:
After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that …

AJ-1681 remove alpha

---

service/src/main/java/org/databiosphere/workspacedataservice/config/DataImportProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
service/src/main/resources/application-control-plane.yml
service/src/main/resources/application-data-plane.yml
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/jobexec/QuartzJobTest.java

When Rawls checks cWDS for status of a given import job, cWDS reports it has succeeded, so Rawls won't write anything.  This PR leaves cWDS jobs in RUNNING so Rawls will see them as safe.
In this PR:
* adds a new `twds.data-import.succeed-on-completion` property, set to `true` in the data plane and `false` in the control plane
* pipes the property through the `DataImportProperties` config class
* used IntelliJ to restructure/reformat the `DataImportProperties` class
* reads the `DataImportProperties.isSucceedOnCompletion()` inside `QuartzJob`, and only mark the job as `SUCCESS` when true
_NOT_ in this PR:
* awaiting/reading a pub/sub message from Rawls, so we can finally mark the job as succeeded. After this PR, jobs will seem to stay in running forever according to WDS, but at least …

AJ-1687: control-plane import jobs should stay running after they finish in quartz

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/WsmSnapshotSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/SearchRequest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/WdsSnapshotSupportTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobDataPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java

This is cleanup in prep for making changes to `BatchWriteService` and `RecordSink` to only write one file out to storage at the end of an entire batch for [AJ-1669](https://broadworkbench.atlassian.net/browse/AJ-1669).
Eliminates most compiler warnings about nullability, as well as other minor syntax issues in these classes and all their adjacent collaborators.
The process I took to end up with this scope is as follows:
1) I started at `RawlsRecordSink` and `BatchWriteService` and fixed warnings there.
2) Nullability problems can be fixed locally but need to be traced upward/downward to ensure they are fixed at the root, so I searched backward for references to these two classes and fixed warnings in those files.
3) I opportunistically fixed other easy warnings in touched files, but left …

AJ-1669: Fix warnings near `BatchWriteService`

---

service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkFactory.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/MockSamUsersApi.java

In prep for making changes for [AJ-1669](https://broadworkbench.atlassian.net/browse/AJ-1669), improve E2E test coverage for PFB imports in cWDS:
* Verify PubSub message publishing.
* Verify GCS text storage.
* Use the contents of the GCS text instead of the `jsonConsumer` to do all the existing verifications on JSON content.
* Get rid of `jsonConsumer` which existed only to verify the JSON and is no longe needed.
[AJ-1669]: https://broadworkbench.atlassian.net/browse/AJ-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1669: Improve PFB E2E test coverage.

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java

For [AJ-1669](https://broadworkbench.atlassian.net/browse/AJ-1669): this makes an entire import job use the same `RecordSink` instance for all batches.  The goal here is to make the `RawlsRecordSink` capable of handling the entire import job with a single GCS file & pubsub, rather than triggering a new file & pubsub message for each batch.
In a subsequent change, the `RecordSink` will be given an additional method to finalize the import, which is what will be called at the very end of a batch to do all the post-processing.
[AJ-1669]: https://broadworkbench.atlassian.net/browse/AJ-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1669: Reuse `RecordSink` for full import.

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/WdsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java

For [AJ-1669](https://broadworkbench.atlassian.net/browse/AJ-1669): this provides a callback hook that can be used to perform any necessary steps _after_ all batches are complete.  Its intended use is to allow `RawlsRecordSink` to finish writing to the underlying GCS Storage, and send a pubsub message downstream just once after all batches are complete.
Right now it is basically a no-op, but it could be used at this point to consolidate the activity logging logic, for example.
[AJ-1669]: https://broadworkbench.atlassian.net/browse/AJ-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1669: Add `finalizeBatchWrite` to `RecordSink`

---

service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/MDCServletRequestListener.java

Persist the MDC requestId into Quartz job context. Within the Quartz job, retrieve the id from context and put it into the new thread's MDC.
This screenshot of local logs shows the same requestId across threads. In the highlighted rectangle, the first column is the thread name and the second is the request id:
compare to a screenshot from before this PR:

AJ-1670: MDC requestId for Quartz jobs

---

.github/workflows/publish-docker.yml

followup to #626. This PR:
* runs `publish-docker` on pushes to main, so we have docker images and Beehive/Sherlock knowledge of each commit to main
* updates two very outdated `google-github-actions` actions to latest versions

AJ-1666: publish on push to main; update out-of-date actions

---

service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/storage/GcsStorage.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java

In the pubsub message that cWDS sends to Rawls, we must include the bucket name as well as the file path.

AJ-1586: send full bucketname + file in pubsub message

---

.github/dependabot.yml

A couple of times now, I've noticed @davidangb and @jladieu combine multiple Dependabot updates into one PR. Instead of doing that manually, we can have Dependabot do it for us.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

[AJ-1635] Configure Dependabot to group minor and patch version updates

---

service/src/main/java/org/databiosphere/workspacedataservice/service/model/DataTypeMapping.java

The default *[search path](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH)* for Postgres db connections is `"$user", public`. This means that anytime we use _unqualified_ names in a SQL statement, Postgres will look for those objects in the `public` schema and in a schema named after the current user (which in our case doesn't exist).
When WDS creates a new table for a user, it issues a statement like:
```
create table "some-uuid"."mytable" (id text primary key, myfile file);
```
This creates two columns:
* a column named "id" of type "text", which is the primary key
* a column named "myfile" of type "file"
The "text" type is a built-in Postgres type. The "file" type is a custom WDS type, which is created in our first Liquibase changeset …

AJ-1695: (take 2) add public. qualifier to file/relation types

---

.github/workflows/publish-app-version.yml

https://github.com/DataBiosphere/terra-workspace-data-service/pull/626 removed the `cwds-report-to-sherlock` job from [publish-app-version.yml](https://github.com/DataBiosphere/terra-workspace-data-service/pull/626/files#diff-1ac4fd7604e5ec940e6c79797149bd0b58599ff0d613e65f55bbb83a4e1b32fd) but forgot to remove `needs: cwds-report-to-sherlock` from the following job.
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is …

AJ-1681 Remove extraneous 'needs' from GHA job

---

.github/workflows/release-python-client.yml
service/src/main/java/org/databiosphere/workspacedataservice/config/DataImportProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportSourceValidator.java
service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/ImportControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/ImportSourceValidatorTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobDataPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java

https://broadworkbench.atlassian.net/browse/AJ-1588
Per security requirements, we can't import from arbitrary URLs. This restricts import URLs to HTTPS URLs pointing to files in GCS buckets, Azure blob storage containers, or S3 buckets. Additional allowed import services can be configured.
One complication is that some import tests use a file URL for a local resource. I added another configuration option (to be used only in tests) to allow different URL schemes (file for some unit tests and http for client tests).

[AJ-1588] Validate URLs for file imports

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/WdsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/TypeMismatchException.java
service/src/main/java/org/databiosphere/workspacedataservice/storage/GcsStorage.java
service/src/main/java/org/databiosphere/workspacedataservice/storage/GcsStorageConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkPrefixingTest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/storage/GcsStorageConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/storage/GcsStorageTest.java

For [AJ-1669](https://broadworkbench.atlassian.net/browse/AJ-1669): Rather than writing a Blob for every batch and every record type, record all writes for a whole batch into one Blob and send a single Pubsub message.
The PR currently contains 4 commits.  3 prefactoring & 1 actual change.
The prefactorings are done up front to ease review and reduce the footprint of the final actual change.
Each commit has a description to explain intent and is intended to be easier to review than the whole, so I recommend taking a look at each separately.
[AJ-1669]: https://broadworkbench.atlassian.net/browse/AJ-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1669: Write and publish only once.

---

.github/workflows/publish-docker.yml

On Dependabot PRs, this workflow fails to login to ACR because the username and password are stored in secrets that are not accessible to Dependabot.

[AJ-1681] Skip publishing Docker image on Dependabot PRs

---

service/src/main/java/org/databiosphere/workspacedataservice/service/BackupRestoreService.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BackupRestoreServiceTest.java

The default *[search path](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH)* for Postgres db connections is `"$user", public`. This means that anytime we use _unqualified_ names in a SQL statement, Postgres will look for those objects in the `public` schema and in a schema named after the current user (which in our case doesn't exist).
When WDS creates a new table for a user, it issues a statement like:
```
create table "some-uuid"."mytable" (id text primary key, myfile file);
```
This creates two columns:
* a column named "id" of type "text", which is the primary key
* a column named "myfile" of type "file"
The "text" type is a built-in Postgres type. The "file" type is a custom WDS type, which is created in our first Liquibase changeset …

AJ-1695: reset Postgres search path to default after clone/restore

---

service/src/main/java/org/databiosphere/workspacedataservice/config/DataImportProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/PubSubConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/storage/GcsStorage.java
service/src/main/java/org/databiosphere/workspacedataservice/storage/GcsStorageConfig.java
service/src/main/resources/application-control-plane.yml

In office hours today, we discovered that the GCP PubSub library has its own project ID configuration and WDS fails to start if that configuration is not provided.
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pfbQuartzJob' defined in file [/Users/nwatts/workspace/terra-workspace-data-service/service/build/classes/java/main/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'rawlsRecordSinkFactory' defined in file [/Users/nwatts/workspace/terra-workspace-data-service/service/build/classes/java/main/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkFactory.class]: Unsatisfied dependency expressed …
```

[AJ-1709] Configure project ID for PubSub

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/PubSubController.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/JobStatusUpdate.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/PubSubMessage.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/PubSubRequest.java
service/src/main/java/org/databiosphere/workspacedataservice/service/JobService.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/PubSubControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceControlPlaneTest.java

https://broadworkbench.atlassian.net/browse/AJ-1687
An import isn't complete until Rawls finishes importing the entities JSON file written by CWDS. Currently, when it is done, it notifies import service of the final job status via PubSub ([code](https://github.com/broadinstitute/rawls/blob/44f717ce2b7d076aebf577b64377c7c56e4e11f3/core/src/main/scala/org/broadinstitute/dsde/rawls/monitor/AvroUpsertMonitor.scala#L341-L344)). We want a similar set up for CWDS. This adds a handler for those PubSub messages.
See https://cloud.google.com/pubsub/docs/push#receive_push for the PubSub request format.
Adapted from import service: https://github.com/broadinstitute/import-service/blob/a818658d0850818804235c5dc7f239c0de95c8cf/app/status.py#L55-L106
Still to do here is authentication for the PubSub …

[AJ-1687] Add handler for PubSub messages from Rawls

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/PubSubController.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/JobStatusUpdate.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/ValidationException.java

https://broadworkbench.atlassian.net/browse/AJ-1687
Trying to figure out why CWDS is failing to parse the PubSub message. This attempts to:
- Throw a ValidationException if the PubSub message can't be parsed. This will have the endpoint return a successful status code and avoid retrying the message.
- Log the message that couldn't be parsed.

[AJ-1687] More logging for errors handling PubSub message

---

service/src/main/java/org/databiosphere/workspacedataservice/rawls/BearerAuthRequestInitializer.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsApi.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsClient.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsClientConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/common/TestBase.java
service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/rawls/RawlsClientRetryTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceControlPlaneTest.java

This PR changes the WDS-to-Rawls connection from using `RestTemplate` to a declarative proxy powered by `RestClient` and adds Prometheus observability.
`RestClient` is a modern and fluent replacement for `RestTemplate`; see https://spring.io/blog/2023/07/13/new-in-spring-6-1-restclient and https://docs.spring.io/spring-framework/reference/integration/rest-clients.html.
`RestClient` supports observability via Prometheus; see https://docs.spring.io/spring-framework/reference/integration/observability.html#observability.http-client.restclient. (`RestTemplate` supports it too).
Additionally, this PR changes our WDS-to-Rawls connection from imperative method invocations on `RestClient`/`RestTemplate` to a declarative HTTP interface; see …

AJ-1680: use RestClient and Spring-generated api proxy

---

build.gradle

https://spring.io/blog/2024/03/21/spring-boot-3-2-4-available-now
I checked all our overridden dependencies, in `constraints` and `dependencyManagement` blocks, and none of them can be removed.

AJ-1708: Spring Boot to 3.2.4

---

service/src/main/resources/application-control-plane.yml
service/src/main/resources/application.yml

https://broadworkbench.atlassian.net/browse/AJ-1686
When WDS starts up, the Spring GCP framework looks for application default credentials, which it can't find because it's not running in GCP. This results in log noise from exceptions thrown at startup.
This disables auto configuration by default and enables it only on the control plane where CWDS is running in GCP.
https://googlecloudplatform.github.io/spring-cloud-gcp/5.1.0/reference/html/index.html#configuration
To test locally, make sure you don't have application default credentials set up: `gcloud auth application-default revoke`.

[AJ-1686] Enable GCP auto configuration only in the control plane

---

service/src/main/java/org/databiosphere/workspacedataservice/pubsub/ImportPubSub.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/PubSubConfig.java

https://broadworkbench.atlassian.net/browse/AJ-1687
More tidying of PubSub config as part of AJ-1687...
This tweaks the configuration for the PubSub topic for CWDS to notify Rawls of an import.
Currently, ImportPubSub constructs a fully qualified topic name from CWDS's GCP project and the configured short topic name. However, this is unnecessarily complex.
It assumes that CWDS and the topic are in the same project. Because they are, we can use the short topic name instead of the fully qualified name. And if they were not, this change would allow us to configure CWDS using a fully qualified topic name.

[AJ-1687] Decouple CWDS project and Rawls notification topic

---

service/src/main/java/org/databiosphere/workspacedataservice/pubsub/PubSubConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/pubsub/MockPubSub.java
service/src/test/java/org/databiosphere/workspacedataservice/pubsub/MockPubSubConfig.java

https://broadworkbench.atlassian.net/browse/AJ-1687
Prefactoring for AJ-1687...
We currently use a stub `PubSub` in tests. To do this, several tests configure the `spring.cloud.gcp.pubsub.enabled` property to `false` and PubSub config swaps out the implementation of `PubSub` based on that property.
Since this is only done for tests, this moves the stub PubSub and the Configuration that creates it into the test package and renames it from `Noop` to `Mock`, which aligns with other similar things like `MockSamResourcesApi`, etc.

[AJ-1687] Update PubSub configuration for tests

---

README.md
service/src/main/resources/application-control-plane.yml

We get the GCP project in which CWDS is running through Spring Cloud GCP's `ProjectIdProvider`. It has several sources it can get the project ID from: https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/current/reference/html/#project-id.
Currently, we short circuit that by setting `spring.cloud.gcp.project-id` based on the `SERVICE_GOOGLE_PROJECT` environment variable.
Alternatively, we can lean into Spring Cloud GCP's project discovery and let it find the project from the environment in live environments. This would allow us to remove the `SERVICE_GOOGLE_PROJECT` environment variable.
When we do want to set the project via an environment variable, such as in local development, Spring Cloud GCP automatically looks at `GOOGLE_CLOUD_PROJECT`.

[AJ-1717] Simplify GCP project configuration

---

service/src/main/java/org/databiosphere/workspacedataservice/config/TwdsProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresJobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/FileDownloadHelper.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportDetails.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/JobStatusUpdate.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkFactory.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobDataPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestUtils.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkFactoryTest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkPrefixingTest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java

[AJ-1716](https://broadworkbench.atlassian.net/browse/AJ-1716) Snapshot imports fail in the control plane with no logged error
The root cause is that the TDR import job set `ImportDetails.jobId` to `null`, but `RawlsRecordSink` required the jobId to be non-null.
Along the way to fixing that, I also:
* added logging into the `JobDao.fail()` methods to ensure we log job errors
* changed how we retrieve the end user's email address, so we never request it in the data plane and don't request it until we absolutely need it in the control plane; added unit tests for this
* tweaked constructors of `ImportDetails` to make it less easy to insert bad data
* cleaned up some IntelliJ warnings
[AJ-1716]: https://broadworkbench.atlassian.net/browse/AJ-1716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

AJ-1716: TDR snapshot import to cWDS fails

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/FileDownloadHelper.java

Discovered during AJ-1716; does not resolve that ticket.
We never cleaned up the temp directories we created while importing TDR snapshots.
The previous code's javadoc says:
> If the file is a directory then the directory must be empty.
So, I'm switching the code from using `java.nio.file.Files` to `org.apache.commons.io.FileUtils`, which knows how to delete a non-empty directory.

AJ-1716: delete non-empty temp dir

---

.github/workflows/publish-pacts.yml

https://broadworkbench.atlassian.net/browse/AJ-1570
For control plane apps, such as (c)WDS now is, we should automatically find out if our contract tests passed or failed.  This adds the `can-i-deploy` step to the `publish-pacts` workflow, which will verify contract tests against deployed versions of the services under contract.
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided the action will not fully …

AJ-1570 Add can-i-deploy step to GHA

---

service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java

[AJ-1587](https://broadworkbench.atlassian.net/browse/AJ-1587): While trying to understand the job counts dashboard, I was confused by what metrics I could be able to count on, and wanted a way to document them.  I thought a unit test to capture expectations of what appears in the Prometheus scrape for this would be a helpful start.
[AJ-1587]: https://broadworkbench.atlassian.net/browse/AJ-1587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1587: Clarify job metrics with unit test.

---

README.md

CWDS needs to be configured with a bucket to write Rawls JSON to. Currently, this is not mentioned in the readme, making it more difficult to run CWDS locally.

Add SERVICE_GOOGLE_BUCKET env variable to readme

---

.github/workflows/publish-docker.yml

https://broadworkbench.atlassian.net/browse/AJ-1708
This workflow is still running and failing on Dependabot PRs. For example: #679.
https://github.com/DataBiosphere/terra-workspace-data-service/actions/runs/8420039149/job/23053921543?pr=679
#658 failed to disable this workflow because the `branches-ignore` filter operates on the branch that the PR is targeting (`main` for Dependabot PRs), not the source branch.
`github.actor` is the documented way to identify a Dependabot PR.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events

[AJ-1708] Skip publish Docker workflow on Dependabot PRs

---

service/src/main/java/org/databiosphere/workspacedataservice/rawls/NamedDataRepoSnapshot.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsClient.java
service/src/test/java/org/databiosphere/workspacedataservice/rawls/RawlsClientTest.java

https://broadworkbench.atlassian.net/browse/AJ-1705
Part 1 of [AJ-1705](https://broadworkbench.atlassian.net/browse/AJ-1705)...
When we link snapshots via WSM, we specify "REFERENCE" for cloning instructions and "policy" for purpose.
https://github.com/DataBiosphere/terra-workspace-data-service/blob/be53253095d079e52b12b7631663404485e8c861/service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDao.java#L41-L77
This passes those same arguments when linking snapshots via Rawls.
Support for these options was added to Rawls in https://github.com/broadinstitute/rawls/pull/2790.
[AJ-1705]: https://broadworkbench.atlassian.net/browse/AJ-1705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AJ-1705] Specify cloning instructions and purpose when linking snapshots through Rawls

---

service/src/main/java/org/databiosphere/workspacedataservice/config/DataImportProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/PubSubConfig.java
service/src/main/resources/application-control-plane.yml

Currently, the configuration for the PubSub topic used to notify Rawls of available imports is mixed in with the Spring Cloud GCP configuration.
Since this configuration is WDS-specific, it should be in the WDS configuration. This also removes the `@Value` in `PubSubConfig` and accesses the value through `DataImportProperties`.

[AJ-1741] Move Rawls notification topic to WDS config

---

smoke_test/README.md
smoke_test/smoke_test.py
smoke_test/tests/authenticated/cwds_job_listing_tests.py
smoke_test/tests/cwds_smoke_test_case.py

* accept a workspace id on the command-line when running smoke tests
* use the workspace id in the job-listing test, so that test does something useful
In support of this, I have created a "cwds-smoketest-do-not-delete" workspace in the dev env to use for smoke tests. Before this rolls out to staging and prod I will create workspaces there too.

AJ-1573: smoke tests add workspace_id CLI argument; use it in the job-listing test

---

README.md
service/src/main/resources/application-control-plane.yml

It occurred to me yesterday, we shouldn't have local CWDS' pulling messages from the same subscription as dev, since that could prevent dev from receiving messages for imports in the dev environment and updating its database accordingly.
It's probably also worthwhile to remove the default configuration for the subscription name to help avoid this, but that will require a change to terra-helmfile.

[AJ-1742] Use dedicated subscription for local CWDS

---

service/src/test/java/org/databiosphere/workspacedataservice/annotations/WithTestObservationRegistry.java
service/src/test/java/org/databiosphere/workspacedataservice/common/TestObservationRegistrySetupExtension.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/jobexec/QuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/observability/TestObservationRegistryConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordServiceTest.java

In prep for introducing additional metrics in for [AJ-1726](https://broadworkbench.atlassian.net/browse/AJ-1726): Adds a `@WithTestObservationRegistry` to DRY up a bunch of the boilerplate involved with doing metric testing.
Specifically:
- Tests can directly `@Autowire TestObservationRegistry` instead of having to cast it.
- Tests don't need to manage teardown of the various meter and observation registries.
[AJ-1726]: https://broadworkbench.atlassian.net/browse/AJ-1726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1726: Streamline metric testing

---

service/src/main/java/org/databiosphere/workspacedataservice/retry/RestClientRetry.java
service/src/test/java/org/databiosphere/workspacedataservice/leonardo/LeonardoDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java
service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java
service/src/test/java/org/databiosphere/workspacedataservice/retry/RestClientRetryTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java

[AJ-1727](https://broadworkbench.atlassian.net/browse/AJ-1727): Add `wds.outbound` observation
This will measure count & latency for outbound requests, using the `loggerHint` as a label.
[AJ-1727]: https://broadworkbench.atlassian.net/browse/AJ-1727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AJ-1727 Measure outbound requests in `RestClientRetry`

---

.github/actions/create-bee/action.yml

Per [this slack thread](https://broadinstitute.slack.com/archives/C0DSD41QT/p1712771051205049), the `default-versions-only: true` parameter will be needed on bee-create workflows (since we don't use `custom-versions-json`)
Reminder: …

AJ-1743 Update bee-create

---

.github/workflows/build-and-test.yml

Had the name of the step wrong, so maybe that's why it's not bumping as expected.
Reminder:
After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that merged …

AJ-1697 Fix copy-paste error

---

.github/workflows/publish-pacts.yml

`can-i-deploy` doesn't need to run on the bump commit, since the exact same code was just verified.  It fails because it doesn't receive a version parameter, which isn't present in the bump commit, since it's not a PR event.  This uses the bump-check action to avoid re-running contract tests on commits that are only bumping the version.
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag-and-publish.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided the …

AJ-1697 Add bump-check to publish_pacts

---

service/src/main/resources/application.yml

AJ-1671
The redirect from `/` to `/swagger/swagger-ui.html` was not working in BEEs; cWDS got confused about to where it should redirect because of proxies in BEEs.
This PR tells Tomcat to use relative urls when issuing redirects, which fixes the issue. I tested by running locally and by deploying this PR to my BEE: https://cwds.davidan-cool-bee-name.bee.envs-terra.bio/

AJ-1671: Tomcat should use relative redirects

---

.github/workflows/publish-docker.yml

When publishing docker images / reporting to Sherlock on PRs, use the SHA from the latest PR commit instead of the SHA or the merge commit. This makes it much easier to correlate image tags/Sherlock versions with your PR.
Check out the actions that ran on this PR, especially `report-to-sherlock`, and compare to the list of commits in this PR.

AJ-1776: use real commit SHA for tagging PR builds

---

.github/workflows/build-and-test.yml

The docker job refers to the output of `tag.yml` for its new tag, but the output of `tag.yml` is `new-tag` NOT `new_tag` 
Reminder:
After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that …

AJ-1776 Fix typo in GHA

---

.github/dependabot.yml

https://broadworkbench.atlassian.net/browse/AJ-1782
Automatically tag Dependabot PRs with the permanent Jira ticket for WDS dependency updates.

[AJ-1782] Automatically tag Dependabot PRs with ticket

---

.github/dependabot.yml

https://broadworkbench.atlassian.net/browse/AJ-1782
This configures Dependabot to automatically update third party GitHub Actions used in workflows.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#github-actions

[AJ-1782] Configure Dependabot to update GitHub Actions

---

.github/workflows/auto-approve-dependabot-prs.yml

https://broadworkbench.atlassian.net/browse/AJ-1692
Have Dependabot auto approve its PRs so that only one human is needed to meet the two thumbs requirement.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request

[AJ-1692] Auto approve Dependabot PRs

---

.github/dependabot.yml

https://broadworkbench.atlassian.net/browse/AJ-1782
Workflows using these actions failed when one was updated, but not the other. This configures Dependabot to update them as a group.

[AJ-1782] Group updates to artifact actions

---

.github/dependabot.yml

https://broadworkbench.atlassian.net/browse/AJ-1639
Experimenting to see if we can have Dependabot update java-pfb in WDS.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/guidance-for-the-configuration-of-private-registries-for-dependabot

[AJ-1639] Configure Dependabot to update java-pfb

---

.github/workflows/publish-pacts.yml
service/src/test/java/org/databiosphere/workspacedataservice/pact/RawlsPactTest.java

https://broadworkbench.atlassian.net/browse/AJ-1786
First step in creating separate Pacticipants for WDS and CWDS.
The Pact with Rawls is only applicable to CWDS, WDS talks directly to WSM. This changes the consumer to "cwds" for the Rawls Pact.
With the new "cwds" Pacticipant, we also need to run `can-i-deploy` for CWDS. This changes the `publish-pacts.yml` workflow to run `can-i-deploy` for each Pacticipant.

[AJ-1786] Change consumer Pacticipant name to cwds for Rawls Pact

---

service/build.gradle
service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java
service/src/test/java/org/databiosphere/workspacedataservice/pact/TdrPactTest.java

https://broadworkbench.atlassian.net/browse/AJ-1786
Pacts are between services. Since the WDS repository now contains two services (WDS and CWDS), we want to publish Pacts for both of those.
Some Pacts are the same for WDS and CWDS. Both services have the same interactions with Sam and DataRepo. For those, we want to use one Pact consumer test to publish a Pact for both services.
To accomplish that, this replaces the hard coded `wds` consumer name with a consumer name from an environment variable. The Pact tests are run twice: once with the consumer name set to `wds` and once with it set to `cwds`. All of the resulting Pacts will be published to the Pact broker.

[AJ-1786] Generate Pacts for both WDS and CWDS

---

.github/workflows/publish-pacts.yml

The `locate-pacts` step finds all Pact JSON files and outputs them as a JSON serialized.
This simplifies the JSON serialization by using `jq` instead of string concatenation to build JSON.
It also removes some labels/comments about base 64 encoding, since the `locate-pacts` step does not encode the Pact files.

[AJ-1793] Simplify JSON serialization in publish pacts workflow

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonSchedulable.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/package-info.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/generated/ImportRequestServerModel.java
service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/main/resources/static/swagger/apis-v1.yaml
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/package-info.java
service/src/test/java/org/databiosphere/workspacedataservice/jobexec/QuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java

Some small no-op / skeletal implementations to lay the groundwork for the `RAWLSJSON` format, which will be used to support async TSV in cWDS.

AJ-1700: Initial scaffolding for cWDS support of `RAWLSJSON`

---

.github/workflows/publish-app-version.yml

Updates the GHA which creates a PR in terra-helmfile on release to reflect the chart changes in https://github.com/broadinstitute/terra-helmfile/pull/5445.

AJ-1789: separate applicationVersion setting in helm chart

---

service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvBatchTypeDetectionTest.java

WDS would read the first _batch_ of records from a TSV upload (or other input!), infer a schema based on the contents of those records, and then use that schema for the remainder of the batches. The batch size is relatively large, at 5000 records, defined [here](https://github.com/DataBiosphere/terra-workspace-data-service/blob/d8212da81efe1e1934a9f84e73ba72f7668c6f1f/service/src/main/resources/application.yml#L126).
However, this means that if a record in any batch later than the first has a conflicting datatype, the upload will fail. For instance, if the first 5000 records have integers in a given column but the 5001st record has a string, we'll hit an error trying to insert a string into a number column.
We now infer schema on every batch. This trades performance for correctness - it's …

AJ-1628: TSV uploads detect datatypes across batches

---

.github/workflows/run-e2e-tests.yaml

`attach-billing-project-to-landing-zone` expects the given `run-name` to end with the calling workflow's run ID and run attempt.
https://github.com/broadinstitute/terra-github-workflows/blob/8463d2aeaff46ed6b37af851e5a24d9810b075f1/.github/workflows/attach-billing-project-to-landing-zone.yaml#L121-L123
Adding a `-retry` suffix to the `run-name` causes the workflow to fail.
See https://broadinstitute.slack.com/archives/C031KGQUVB4/p1713867565816199 for an example.

[AJ-1800] Fix run name for attach-billing-project-to-landing-zone retry

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportValidator.java
service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/ImportValidatorTest.java

In preparation for a couple of changes to import validation, expand the current `ImportSourceValidator` to an `ImportValidator` that considers the full import request instead of only the URL.

[AJ-1798] Refactor import validation to consider the full request vs only the URL

---

service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrTestSupport.java

Planning to add `RawlsJsonTestSupport` as part of a larger PR, but I wanted to get this cleanup in place so that the various `TestSupport` classes maintain a consistent implementation.

AJ-1700: Minor cleanup of tes support classes

---

.github/workflows/release-python-client.yml
service/src/main/java/org/databiosphere/workspacedataservice/config/DataImportProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidator.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportValidator.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportValidatorConfiguration.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/NoopImportValidator.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidatorTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/ImportValidatorTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobDataPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobE2ETest.java

https://broadworkbench.atlassian.net/browse/AJ-1798
By default, `ImportValidator` only allows HTTPS import URLs. Attempts to import from URLs with other schemes are rejected with a 400 response.
However, `ImportValidator` can be configured to accept other schemes via the `twds.data-import.allowed-schemes` property. This is used only for tests, to allow a few e2e tests to import test fixtures from file URLs and to allow a Python test to import from an HTTP URL.
However, there is some risk that a misconfiguration would allow users to import file URLs, potentially giving them access to data on the server. To remove that risk, this PR removes the `twds.data-import.allowed-schemes` property.
e2e tests now use a `MockBean` annotation to skip `ImportValidator`'s validation entirely.
To support …

[AJ-1798] Remove data-import.allowed-schemes configuration

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidator.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidatorTest.java

https://broadworkbench.atlassian.net/browse/AJ-1798
Unlike the other import types, Rawls JSON import URLs will be `gs://` URLs. `ImportValidator` must accept those URLs.

[AJ-1798] Support gs:// URLs for Rawls JSON imports in ImportValidator

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/leonardo/LeonardoDao.java
service/src/test/java/org/databiosphere/workspacedataservice/leonardo/LeonardoDaoTest.java

Reverts DataBiosphere/terra-workspace-data-service#755

Revert "[AJ-1782]: Bump org.broadinstitute.dsde.workbench:leonardo-client_2.13 from 1.3.6-22ee00b to 1.3.6-9996462-SNAP"

---

.github/dependabot.yml

At least by default, Dependabot doesn't seem to handle updates to Terra client libraries since the version identifiers include git revisions. This configures Dependabot to ignore updates to those client libraries.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore

[AJ-1782] Configure Dependabot to ignore Terra client libraries

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/JobController.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerTest.java

For the `jobsInInstanceV1` API, which lists jobs within a given collection:
* If the user specifies an invalid status value, return 400 BadRequest instead of 500 Internal Server Error. This prevents spurious Sentry issues.
* If the user specifies an empty status value - `?status=` - treat it the same as if they specified no param at all and return all jobs

AJ-1810: better handling of ?statuses= param for job listing

---

.github/workflows/build-and-test.yml
.github/workflows/publish-docker.yml

https://broadworkbench.atlassian.net/browse/AJ-1811
When cwds reports a non-main version to [sherlock](https://beehive.dsp-devops-prod.broadinstitute.org/charts/cwds/app-versions), it just gives it the git hash, whereas (at least some) [other repos](https://beehive.dsp-devops-prod.broadinstitute.org/charts/rawls/app-versions) have the hash after the version, making it easier to sort.  
Previously, `publish-docker.yml` was called on PRs, lacking the tag, and so used the git hash as a tag.  Now `build-and-test` always calls `tag` and `publish-docker`, and uses the tag result from `tag.yml` to report to sherlock, which does include the version+hash.
Reviewers, please verify that I haven't ruined the tagging/versioning flow. I've mostly convinced myself that it's correct but definitely need a …

[AJ-1811] Report version+hash to sherlock

---

service/src/main/java/org/databiosphere/workspacedataservice/config/DataImportProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidator.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportDetailsRetriever.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportValidatorConfiguration.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/jobexec/JobDataMapReader.java
service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/pubsub/RawlsJsonPublisher.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/WdsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
service/src/main/java/org/databiosphere/workspacedataservice/storage/GcsStorage.java
service/src/main/resources/application-control-plane.yml
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidatorTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestUtils.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonQuartzJobControlPlaneE2ETest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrTestSupport.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/storage/GcsStorageTest.java

This is logic replicated from import-service to just move a given incoming rawls JSON file from its original location to the upsert location and notify Rawls.
Some prefactoring commits which eased implementation can be more easily reviewed on their own.

AJ-1700 Implement `RAWLSJSON` support.

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/SerializationException.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributes.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/attributes/Attribute.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/attributes/JsonAttribute.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/attributes/ScalarAttribute.java
service/src/main/java/org/databiosphere/workspacedataservice/tsv/TsvDeserializer.java
service/src/test/java/org/databiosphere/workspacedataservice/service/DataTypeInfererTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvDeserializerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvJsonArgumentsProvider.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvJsonEquivalenceTest.java

This PR introduces a `JsonAttribute` class into the attribute hierarchy (see #759). TSV uploads now deserialize json columns, and arrays of json, into `JsonAttribute` instead of `Map<String, Object>`.
This is pre-work to supporting arrays-of-arrays. Since `JsonAttribute` can support either a json object or a json array, it is more flexible; the previous `Map<String, Object>` can only support a json object.
However, as prework, there should be no functional changes in this PR; it is only a refactor.

AJ-1748: introduce JsonAttribute

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/rawlsjson/RawlsJsonQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/storage/GcsStorage.java
service/src/test/java/org/databiosphere/workspacedataservice/storage/GcsStorageTest.java

Before this change, the `moveBlob` method would attempt to get the blob based on the original target to return a reference to it.  However, the original `BlobId` used as a reference also contained the original `generation`, and therefore the `getBlob` call would always return `null` and cause an NPE.  Instead, we use the resultant `Blob` from the copy, which has the correct new `generation`, and should actually exist.
Notes about the verifying issue:
- The local mock storage doesn't behave exactly the way the actual/production storage does with regards to existing blobs and how errors are surfaced, so it's not 100% reliable at detecting issues like this.
- In order to reproduce the actual issue I actually temporarily switched over to using the real version of the storage class in the E2E …

AJ-1700: Fix bug while copying `RAWLSJSON` file.

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java
service/src/main/java/org/databiosphere/workspacedataservice/tsv/TsvDeserializer.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvDownloadTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvInputFormatsTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/DataTypeInfererTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvDeserializerTest.java

This supports arrays-of-arrays for TSV upload and our json-based REST APIs. It treats arrays-of-arrays as `ARRAY_OF_JSON`. So, we still get a count of the number of first-level elements, but each first-level element is a opaque json blob; we don't provide any special functionality for the nested structures.
`ARRAY_OF_JSON` _can_ support the following use cases:
* **arrays of json objects**: already supported before this PR.
* **arrays of arrays**: added support in this PR.
* **arrays of mixed types**: _partial_ support in this PR.
* If at least one of the elements of the array is a nested array or object, we treat it as `ARRAY_OF_JSON`. Example: `["one", "two", ["nested", "array"], "three]`
* If none of the mixed types is an array or object, we maintain the current behavior and treat it …

AJ-1748: arrays of arrays in TSV

---

service/src/main/java/org/databiosphere/workspacedataservice/logging/AvailabilityListener.java

We should not log this at `error` level, since `error` level is picked up by Sentry.
k8s can and will shuffle pods around as a normal operation. There are other reasons a pod may shut down, such as app upgrades. These can all generate `REFUSING_TRAFFIC` log messages.

AJ-1818: REFUSING_TRAFFIC is not an error

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/SearchFilter.java
service/src/main/java/org/databiosphere/workspacedataservice/shared/model/SearchRequest.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/GeneratedClientTests.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerSearchFilterTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java

This PR modifies the pre-existing `POST /{instanceid}/search/{v}/{type}` API.
Before this PR, that API accepted a payload of:
```json
{
"offset": 0,
"limit": 10,
"sort": "ASC",
"sortAttribute": "string"
}
```
After this PR, it will accept a payload of:
```json
{
"offset": 0,
"limit": 10,
"sort": "ASC",
"sortAttribute": "string",
"filter": {
"ids": [
"string"
]
}
}
```
That is, it will now accept a `filter` object, which can contain an `ids` array of strings.
Both `filter` and `filter.ids` are optional for backwards compatibility. If you omit them, the API will behave as it previously did.
If you DO specify values in `filter.ids`, it will behave like a SQL `IN` clause, and filter the query results to only those records whose ids match one of the supplied values.
Some functional behaviors: …

AJ-1771: id filter for paginated record query

---

service/src/main/resources/capabilities.json

Followup PR to #771 - add a new key to our capabilities that indicates this WDS supports `filter.ids` in the query API.

AJ-1771: add search.filter.ids to capabilities

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidator.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidatorTest.java

This is a security measure to ensure that a bad actor can't craft a
`RAWLSJSON` URI that hijacks a request for a different workspace.
Paired with orchestration change:
https://github.com/broadinstitute/firecloud-orchestration/commit/16074dd555261e683651c3dfac280912577d49e9

AJ-1812: Require gs:// URIs to match workspaceId

---

service/src/test/java/org/databiosphere/workspacedataservice/GeneratedClientTests.java

A little pre-work towards the goal of update our openapi-generator version in #780.
In that other PR, I have worries that the openapi-generator update changes how users of the client would access `RecordAttributes`. This PR adds a test against the client code that uses `RecordAttributes`. I plan to merge this test and then rebase the other PR on top of this and see if the test breaks.

AJ-1782: add generated client test that uses RecordAttributes

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidator.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportValidatorConfiguration.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/ProtectedDataSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/RawlsProtectedDataSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/WsmProtectedDataSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/policy/PolicyUtils.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsApi.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsClient.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsWorkspaceDetails.java
service/src/test/java/org/databiosphere/workspacedataservice/annotations/AnnotatedApisTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidatorTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/RawlsProtectedDataSupportTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/WsmProtectedDataSupportTest.java
service/src/test/java/org/databiosphere/workspacedataservice/policy/PolicyUtilsTest.java

(C)WDS is configured to require a "protected workspace" for imports from BioData Catalyst. "Protected workspace" means a workspace that has additional security monitoring enabled and would be allowed to import data that has a "protected data" policy.
Currently, CWDS determines if a workspace is protected by checking if the workspace has a protected data policy. That works for Azure workspaces, but not for GCP workspaces. For GCP workspaces, the only indication that the workspace is protected is the name of the GCS bucket. For workspaces with additional security monitoring enabled, the bucket name starts with "fc-secure-" instead of "fc-".
To get the bucket name, CWDS has to get the workspace details from Rawls. However, for WDS, we don't want to involve Rawls and since we're only dealing …

[AJ-1777] Fix check for protected workspace

---

.github/workflows/tag-and-publish.yml
.github/workflows/tag.yml

The latest (0.4.0) version of bumper supports a `FORCE_WITHOUT_CHANGES` config flag.
This should allow our tag-and-publish release workflow to properly bump the minor version of a release, instead of the patch version.

AJ-1819: update to latest bumper, use FORCE_WITHOUT_CHANGES for releases

---

.github/release-drafter-config.yml

Now that we bump the minor (not patch) version on releases, we need to change the default bump for our draft release notes.

AJ-1819: release drafter default bump should be minor

---

service/src/main/resources/application.yml
service/src/main/resources/static/swagger/openapi-docs.yaml

https://broadworkbench.atlassian.net/browse/AJ-1822
This removes the `diskSpace` section from the `/status` endpoint.
It does so by disabling the default health indicators and explicitly enabling the ones we do want.
https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health
While I was here, I noticed the OpenAPI docs for the status endpoint were significantly out of sync with the actual response. So I updated those as well.

[AJ-1822] Remove disk space from status endpoint

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidator.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidatorTest.java

An import request with a relative URL (for example: `/path/to/file`) causes DefaultImportValidator to throw a NullPointerException when it checks if the URL scheme is allowed for the import type.
This changes DefaultImportValidator to reject all relative URLs.

[AJ-1840] Reject requests to import files from relative URLs

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/ParquetRecordConverter.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/ParquetDataTypesTest.java

This PR branches from, and supersedes, #794. This PR builds on the research, findings, and tests from that other PR but attempts to simplify the implementation.
* when translating TDR snapshots, don't exclude the snapshot's primary key column. End users expect that column and its values to exist.
* In WDS (irrelevant for cWDS), when batch-upserting, ensure the primary key column is a string. We have a few places ([example](https://github.com/DataBiosphere/terra-workspace-data-service/blob/11628f599f958f204a376641637ace93a2c46a7d/service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java#L422)) that require WDS PKs to be a string, so we need to enforce that.
* JSON and TSV APIs create PK columns as string. The TDR and PFB paths didn't do that, and the snapshot used in …

AJ-1844: snapshot import preserves primary key column

---

service/src/main/java/org/databiosphere/workspacedataservice/retry/RestClientRetry.java
service/src/test/java/org/databiosphere/workspacedataservice/retry/RestClientRetryTest.java

* Downgrade error logs to warning.  Eror logs are reported to Sentry via https://docs.sentry.io/platforms/java/guides/logback/; these should only be reported to Sentry when all retry attempts failed.
* Fix bug in test verifying behavior of first attempt, which was looking for an incorrect key, hiding the next bug...
* Fix bug where first attempt is recorded as `retryCount` = 0.  This makes the promQL to detect retries more complicated, so prefer not to count it.

AJ-1848: Fix retryable bugs.

---

service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/JobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresJobDao.java
service/src/main/java/org/databiosphere/workspacedataservice/jobexec/ImportJobUpdater.java
service/src/main/java/org/databiosphere/workspacedataservice/service/JobService.java
service/src/main/resources/application.yml
service/src/test/java/org/databiosphere/workspacedataservice/dao/PostgresJobDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/jobexec/ImportJobUpdaterTest.java

https://broadworkbench.atlassian.net/browse/AJ-1704
This PR sets up a scheduled task to update any import jobs that haven't completed in 6 hours to `ERROR` status.
I chose not to use a lock or Shedlock to deal with updating multiple replicas at once; all we're doing is changing the status from `RUNNING` to `ERROR`, and as far as I can tell interference would just result in updating a job that's already in `ERROR` to still be in error.  I tried this out on my BEE and although I saw all the replicas update at the same time, I didn't see any other problems.
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the …

AJ-1704 Error out stalled jobs

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/WsmProtectedDataSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/snapshotsupport/WsmSnapshotSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/storage/AzureBlobStorage.java
service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/WsmProtectedDataSupportTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java
service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java

Specifically centered around Wsm interaction:
* WsmProtectedDataSupport
* WsmSnapshotSupport
* WorkspaceManagerDao)
* (and tests and immediate neighbors)

AJ-1658: Prefer `WorkspaceId` over `String workspaceId`

---

build.gradle
service/build.gradle
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java

Update to Spring Boot 3.3.0: https://spring.io/blog/2024/05/23/spring-boot-3-3-0-available-now
This will supersede parts of #804.
In this PR:
* the Spring Boot update
* remove our version override for Liquibase, since Spring Boot now includes the version of Liquibase we want (doc at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes)
* updates to unit tests for metrics - looks like the autocollected metrics names changed slightly
I reviewed the rest of WDS's version overrides and do not see anything else that can be removed.
I reviewed the release notes and do not see any7 compatibility issues.
I reviewed the changed metrics keys w/r/t the [cWDS dashboard](https://grafana.dsp-devops.broadinstitute.org/d/m4cmXc0Sk/cwds?orgId=1&refresh=5s) and do not see any …

AJ-1782: spring boot 3.3.0

---

service/src/integrationTest/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerCloneTest.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/CollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/main/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBean.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDao.java
service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvBatchTypeDetectionTest.java

Change signature of `CollectionDao#collectionSchemaExists` to use `CollectionId` instead of `UUID`.

AJ-1658: Prefer `CollectionId`

---

service/src/integrationTest/java/org/databiosphere/workspacedataservice/IntegrationServiceTestBase.java
service/src/integrationTest/java/org/databiosphere/workspacedataservice/service/RestoreServiceIntegrationTest.java
service/src/integrationTest/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerCloneTest.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/CollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BackupRestoreService.java
service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamExceptionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java

Change signature of CollectionDao#listCollectionSchemas to return `List<CollectionId>` instead of `List<UUID>`.

AJ-1658: Prefer `CollectionId` over `UUID`

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/CollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/main/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBean.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/ImportControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerSearchFilterTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceNoPermissionSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamExceptionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorSamTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvBatchTypeDetectionTest.java

Change signature of `CollectionDao#createSchema` to use `CollectionId`
instead of `UUID`.

AJ-1658 Prefer `CollectionId` over `UUID`

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/AvroRecordConverter.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbRecordConverterTest.java

The import in question from HCA contains some attributes which are, at the Avro level, `Array`s of `GenericData$Record`.
In `AvroRecordConverter`, we properly detect these types and serialize them to json.
However, we store that serialized json inside a `String`. Later, when `RawlsRecordSink` puts that string inside an `AddListMember` `Op` and that `Op` is serialized into file (i.e. written to a bucket), the `Op`'s serialization notices all the double quotes within the string and escapes them. Thus, the carefully-serialized json is escaped and loses its json-ness.
The end result causes fatal errors for the HCA import:
* it expected to store an array of json objects, with each object being of a legal size
* instead, it tries to store a single escaped string that concatenates all objects, …

AJ-1857: PFB/Parquet maps and records should not be stringified twice

---

service/build.gradle

Updates `aircompressor` transitive dependency to address CVE-2024-36114

AJ-1868: update aircompressor transitive dep

---

service/build.gradle

Updates `commons-configuration2` transitive dependency to address:
* CVE-2024-29131
* CVE-2024-29133

AJ-1782: update commons-configuration2 transitive dependency

---

service/build.gradle

removes the `bcprov-jdk15on` transitive dependency from the hadoop libraries to address:
* CVE-2024-30172
* CVE-2024-30171
* CVE-2024-29857
* CVE-2023-33201
Validated in my BEE by importing a PFB and a large TSV.

AJ-1782: remove bouncycastle bcprov-jdk15on transitive dependency

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RecordSink.java
service/src/main/java/org/databiosphere/workspacedataservice/recordsink/WdsRecordSink.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java

Before this PR, cWDS would always publish a "start import" pub/sub message to Rawls, even if the import failed early in the process and there was nothing for Rawls to import.
Now, `RecordSink` has a new `success()` method, which the PFB and TDR jobs call as their last step, and pub/sub publishing is contained in that method. The rawlsjson import job already did the right thing w/r/t publishing.
In previous discussion with Josh, we talked about fancy ways to set callback handlers on the RecordSink, or to automatically detect success vs. failure. After getting into the code, that seemed like overkill, and this approach feels pragmatic.
I considered also adding a `failure(Exception e)` method on `RecordSink` to flesh out its API, but … there's nothing to do there, so I ignored it.

AJ-1808: don't publish messages to Rawls if import translation fails

---

docs/WDS Running Python tests locally.md

As prep for #797, this PR reorganizes and significantly edits our documentation for running Python tests locally.
#797 will tweak this readme a bit more to change python/openapi versions, but I wanted to keep that other PR as clean as possible and make most of the edits here.

AJ-1821: update docs for python tests

---

service/src/test/java/org/databiosphere/workspacedataservice/GeneratedClientTests.java

Our Java client tests had no coverage for TSV downloads; this PR adds a simple test.

AJ-1821: Java client test for TSV download

---

service/build.gradle

The new parquet libraries in #831 eliminate the need for an `aircompressor` override.
From the build scan for this PR:

AJ-1782: remove override for aircompressor, now that parquet updated

---

.github/workflows/build-and-integration-test.yml
.github/workflows/build-and-test.yml
.github/workflows/publish-pacts.yml

https://broadworkbench.atlassian.net/browse/AJ-1854
Adds concurrency groups to 3 workflows that run for pull requests.  
Reviewer, please verify that the [github.head_ref](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) is the appropriate group name.  In the case of `publish_pacts.yaml`, this could be blank (if it's on `push` instead of `pull_request`), in which case I use `github.ref`.  (Or should I remove it from running on `push` as well?) 
Updates `build-and-test.yaml` to only run on `pull_request`, not also `push`. 
Todo:
[ ] Update GHA structure diagram to reflect this change.
Verified that concurrent runs were cancelled - I received emails alerting me to cancelled runs as I was committing to this PR.
Reminder:
PRs merged into main will not …

AJ-1854 add concurrency groups to GH workflows

---

.github/workflows/build-and-test.yml

https://broadworkbench.atlassian.net/browse/AJ-1854
https://github.com/DataBiosphere/terra-workspace-data-service/pull/829 updated `build-and-test` to run on all pull requests but only push to main.  This turned out to prevent it from building docker images and reporting to sherlock, since that happens only on push.  This PR reverts to run `build-and-test` on push to all branches.
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag-and-publish.yml. Dont forget to provide a Jira Id when triggering the …

AJ-1854 Run build-and-test on all pushes

---

service/build.gradle

Reverts DataBiosphere/terra-workspace-data-service#833
While #833 worked as expected w/r/t reducing `_APPRESOURCEPREVIEW_` metrics, it also seems to have a regression in that it stops recording http requests into the `AppRequests` table. I'd like to revert the update until I have a chance to investigate that.

Revert "AJ-1782: update app insights library"

---

.github/workflows/run-e2e-tests.yaml

The e2e test was only deleting bees if the input said to, but never had any input.  This changes it to always delete the bee and removes reliance on the non-existent input.
Reminder: …

[AJ-1896] Delete bee from e2e tests

---

build.gradle

Spring Boot 3.3.1 is now available: https://spring.io/blog/2024/06/20/spring-boot-3-3-1-available-now
I reviewed the release notes and didn't see anything that needs attention.

AJ-1782: update to spring boot 3.3.1

---

service/build.gradle

I'm not entirely sure when these constraints became unnecessary, but they are redundant. The versions specified in the (now deleted) constraints are the versions already in use. Discovered while testing #839.
From the [build scan](https://gradle.com/s/gb6xhyr6spqyg) for this PR:

AJ-1782: remove unnecessary dependency constraints

---

service/build.gradle
service/src/main/resources/applicationinsights.json

See https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides#example-suppress-collecting-telemetry-for-health-checks for explanation of the config changes in this PR.
This will reduce our Log Analytics ingestion cost by ignoring liveness/readiness probes.
This PR upgrades the app insights library to 3.5.1:
* greater than or equal to 3.5.0 so [sampling overrides are GA](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.5.0)
* less than 3.5.2 because of https://broadworkbench.atlassian.net/browse/AJ-1897
I deployed the code in this PR to a test workspace. Here's a visualization of the results in Log Analytics:
`AppRequests` table:
`AppDependencies` table:

AJ-1898: stop app insights from instrumenting liveness and readiness probes

---

service/build.gradle

Update azure-identity-extensions to 1.1.17, which transitively updates its dependencies.
This should resolve:
* https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/92
* https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/94

AJ-1782: update azure-identity-extensions to 1.1.17

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/snapshotsupport/SnapshotLinkResult.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/snapshotsupport/SnapshotSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
service/src/main/java/org/databiosphere/workspacedataservice/metrics/ImportMetrics.java
service/src/main/java/org/databiosphere/workspacedataservice/metrics/MetricsConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/metrics/SnapshotsConsideredDistributionSummary.java
service/src/main/java/org/databiosphere/workspacedataservice/metrics/SnapshotsLinkedDistributionSummary.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java

New Prometheus metrics for:
* number of snapshots found in a PFB during import (or in a TDR manifest, which will always be 1)
* number of snapshots actually linked to a workspace during import

AJ-1729: record number of snapshots considered and linked for imports

---

service/src/main/java/org/databiosphere/workspacedataservice/recordsink/WdsRecordSink.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobMultipleBatchTest.java

https://broadworkbench.atlassian.net/browse/AJ-1909
The error occurred when importing a table that has > 5000 rows - i.e. across multiple batches. Our batch size is set to 5000.
This fixes the error and adds a unit test to verify behavior across batches.
Related to #796.

AJ-1909: createOrModifyRecordType should consider primary key

---

.github/workflows/release-python-client.yml
docs/WDS Running Python tests locally.md

https://github.com/DataBiosphere/terra-workspace-data-service/pull/847 upgraded our Java client to use openapi-generator 7.7.0. This PR upgrades the Python client to the same version to keep them in sync.
---
Reminder: …

AJ-1782: upgrade Python client to openapi-generator 7.7.0

---

service/build.gradle

Upgrade `applicationinsights-runtime-attach` to 3.5.3, primarily to incorporate their fix:
> Remove _APPRESOURCEPREVIEW_ custom metric as it is still in preview
as noted in https://github.com/microsoft/ApplicationInsights-Java/releases. See https://github.com/DataBiosphere/terra-workspace-data-service/pull/833 for more details on that fix.
Upgrading to 3.5.3 on its own caused a regression in which http requests to WDS were not being recorded in app insights. I tracked this down to a conflict with `javax.servlet` transitive dependencies. We don't want `javax` in our codebase anyway, so I excluded those transitive dependencies from the hadoop libraries which pull them in.

AJ-1897: upgrade app insights to 3.5.3, exclude javax from hadoop

---

service/build.gradle
service/src/main/java/org/databiosphere/workspacedataservice/controller/GlobalExceptionHandler.java
service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/CollectionControllerMockMvcTest.java

Follow-on PR to #858. Introduces validation for collection names.
We are quite likely to use collection names in URLs in the future. While url-encoding is certainly possible, it feels ok right now to limit collection names to alphanumeric/dash/underscore only.
Instead of writing a custom validation to do this, I'm relying on `spring-boot-starter-validation` and `openapi-generator`. The workflow here is:
1. Define the validation constraint in the OpenAPI spec, [here](https://github.com/DataBiosphere/terra-workspace-data-service/blob/26fda06444c1eb0c421c538f4c84eb8b43f00194/service/src/main/resources/static/swagger/apis-v1.yaml#L309)
2. `openapi-generator` uses this constraint to generate a `@Pattern` annotation on its model, as seen …

AJ-1924: validation for collection names

---

service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/CollectionControllerMockMvcSingleTenantTest.java

When running in single-tenant mode, ensure that callers cannot create a collection outside of the single-tenant workspace.
The existing tests in `CollectionControllerMockMvcTest` run with `twds.tenancy.enforce-collections-match-workspace-id=false`; the new tests in this PR runs with `twds.tenancy.enforce-collections-match-workspace-id=true`, which more accurately models our current single-tenant mode.

AJ-1924: test coverage for single-tenant mode

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/CollectionController.java
service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/CollectionControllerMockMvcTest.java

In this PR:
* Implementation and test coverage for the update-collection v1 collection API. This is the last unimplemented v1 collection API!
* Update summary/description for the deprecated v0.2 instance APIs in the OpenAPI spec
* add `@WriteTransaction` annotation for save/delete methods
Runtime code changes are relatively small, but there's a lot of lines of test coverage.

AJ-1924: update-collection v1 API

---

service/src/main/resources/static/swagger/apis-v1.yaml
service/src/main/resources/static/swagger/cwds-api-docs.yaml
service/src/main/resources/static/swagger/openapi-docs.yaml

part of AJ-1660 but does not complete that ticket.
This turns on bearer security for all APIs in our OpenAPI specs, except for /version, /status, and /capabilities.
It does so by setting a global security setting, then overriding those three public APIs to have no security. This is a bit of a refactor.
To test this, I:
* ran WDS locally and observed the swagger-ui pages
* built and published a snapshot version of the java client from this PR ([here](https://broadinstitute.jfrog.io/ui/native/libs-snapshot-local/org/databiosphere/workspacedataservice-client-okhttp-jakarta/0.13.5-SNAPSHOT/)), then ran unit tests in CBAS using this updated client
* see that Python client tests are passing as part of the checks on this PR
For follow-on PR(s): enforce security in the Java layer for all APIs.

AJ-1660: security for all non-public APIs in OpenAPI spec

---

service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java

Before this PR:
* you could sort by the primary key column by omitting the `sortAttribute` field entirely from the API request payload. Omitting the field caused WDS to impose a default sort attribute, which was the primary key
* sorting by primary key worked in Terra UI, because Terra UI would omit the `sortAttribute` field
* you got an error if you included the `sortAttribute` field and its value was the primary key column.
After this PR:
* you can set the `sortAttribute` field to the primary key column
* omitting the `sortAttribute` field works as before
* Terra UI works as before
This PR is related to #868 - I found this issue while working on that other PR, and the change in this PR helps that other one.

AJ-1945: allow explicit sorting on primary key column

---

service/src/test/java/org/databiosphere/workspacedataservice/annotations/ControlPlaneDeploymentModeTest.java
service/src/test/java/org/databiosphere/workspacedataservice/annotations/DataPlaneDeploymentModeTest.java
service/src/test/java/org/databiosphere/workspacedataservice/annotations/DeploymentModeTestBase.java

Quick maintenance/upkeep fix: I noticed we had two unit tests marked as `@Disabled`, because they kept showing up in my test reports. There's no need for these tests to be disabled. I enabled them, and fleshed out their corresponding argument providers.

AJ-1948: enable previously-disabled tests

---

service/src/integrationTest/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerCloneTest.java
service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilderTest.java
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/LogStatementTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceGetWorkspaceIdTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvErrorMessageTest.java
service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java

follow-on to #871 
* rename `validateAndPermissions()` method which no longer checks permissions
* remove usages of the `mock-sam` profile in tests where it is no longer needed
* add `@DirtiesContext` to a few tests that I noticed needed it while I was adjusting tests
* rename a few test methods to reflect that they no longer test permissions

AJ-1660: mock-sam cleanup

---

service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
service/src/main/java/org/databiosphere/workspacedataservice/search/QueryParser.java
service/src/main/java/org/databiosphere/workspacedataservice/search/WhereClausePart.java
service/src/main/resources/capabilities.json
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoWhereClauseTest.java
service/src/test/java/org/databiosphere/workspacedataservice/search/QueryParserTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceFilterQueryTest.java
service/src/test/resources/searchfilter/README.md
service/src/test/resources/searchfilter/testdata.tsv

Followup to #868 
* report more detailed capabilities so the UI can distinguish individual query features
* filter-by-column is now case-insensitive
* support filtering on array_of_string, number, and array_of_number columns
Still todo:
1. Support boolean, file, relation, date, etc columns
2. It is exact-match only, not substring match or natural language search.
4. It works on a single column only; you can't search for e.g. "column1:foo AND column2:bar".
5. Users cannot search for null
6. The `totalRecords` value in the response of the `queryRecords` API may be considered incorrect. It returns the count of records for the specified record type _ignoring_ any filtering. So, if your filter only finds 1 record out of 100 samples, `totalRecords` will still return 100.

AJ-1238: filter by column enhancements

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/CollectionController.java
service/src/main/java/org/databiosphere/workspacedataservice/generated/CollectionApi.java
service/src/main/java/org/databiosphere/workspacedataservice/generated/CollectionRequestServerModel.java
service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/main/resources/static/swagger/apis-v1.yaml
service/src/test/java/org/databiosphere/workspacedataservice/controller/CollectionControllerMockMvcSingleTenantTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/CollectionControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceFilterQueryTest.java

1. Do not allow callers to specify a collection id when creating a new collection.
2. Do not allow callers to specify a collection id when updating an existing collection. We already ignored such an id, but our OpenApi spec made it look possible.
At the implementation layer, starting in the OpenApi spec `apis-v1.yaml`, this PR changes from using the `Collection/CollectionServerModel` model to a new `CollectionRequest/CollectionRequestServerModel`. The latter does not include an id.
This model change cascades down through the controller, the service, and a bunch of tests. It also allows for removing some business logic around ids and the tests for that logic.
Note that this change does NOT affect our current state of creating a default collection where collectionId=workspaceId on startup. …

AJ-1941: collection id is always auto-generated on creation

---

service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/test/java/org/databiosphere/workspacedataservice/activitylog/LogStatementTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/CollectionControllerMockMvcSingleTenantTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/CollectionControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvErrorMessageTest.java

See https://broadworkbench.atlassian.net/browse/AJ-1682. The A/C for that ticket is to remove `enforce-collections-match-workspace-id` entirely. I don't think that's the right thing to do; I think it's good and fine to leave that config flag in place.
That config flag is only used, via `TenancyProperties`, in two places:
1. When saving a new collection, [here](https://github.com/DataBiosphere/terra-workspace-data-service/blob/76d9479887c5f10b670e4aeb39afdfb238f99f36/service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java#L87-L91).
2. When retrieving the workspaceId for a collection, [here](https://github.com/DataBiosphere/terra-workspace-data-service/blob/76d9479887c5f10b670e4aeb39afdfb238f99f36/service/src/main/java/org/databiosphere/workspacedataservic …

AJ-1682: Remove `enforce-collections-match-workspace-id` test overrides

---

service/src/main/java/org/databiosphere/workspacedataservice/search/QueryParser.java
service/src/test/java/org/databiosphere/workspacedataservice/search/QueryParserTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceFilterQueryTest.java
service/src/test/resources/searchfilter/testdata.tsv

the filter-by-column feature now supports additional datatypes:
* file / array_of_file
* boolean / array_of_boolean
* date / array_of_date
* datetime / array_of_datetime
still outstanding to support: null, empty_array, relation/array_of_relation, json/array_of_json

AJ-1953: filter-by-column supports file, boolean datatypes

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/RawlsProtectedDataSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/service/WorkspaceService.java
service/src/main/java/org/databiosphere/workspacedataservice/workspace/DataTableTypeInspector.java
service/src/main/java/org/databiosphere/workspacedataservice/workspace/DataTableTypeInspectorConfig.java
service/src/main/java/org/databiosphere/workspacedataservice/workspace/RawlsDataTableTypeInspector.java
service/src/main/java/org/databiosphere/workspacedataservice/workspace/WdsDataTableTypeInspector.java
service/src/main/java/org/databiosphere/workspacedataservice/workspace/WorkspaceDataTableType.java
service/src/test/java/org/databiosphere/workspacedataservice/annotations/AnnotatedApisTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/WorkspaceServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/WorkspaceServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/workspace/RawlsDataTableTypeInspectorTest.java

Part of AJ-1957 but does not complete that ticket.
This PR adds a method `WorkspaceService.getDataTableType(WorkspaceId workspaceId)` which returns, for any given workspace id, whether that workspace should be powered by WDS data tables or Rawls Entity Service data tables.
This method is currently unused in this PR. It is a prerequisite for completing the rest of AJ-1957, and future PRs will take advantage of it.
The logic to determine the data table type is quite simple: make a request to Rawls to describe the workspace. If the workspace is of type `MC`, it uses WDS data tables. If the workspace is of type `RAWLS`, it uses Rawls Entity Service data tables.
The implementation of this logic is fairly abstracted, via a `DataTableTypeInspector` interface and a `RawlsDataTableTypeInspector` …

AJ-1957: bean to determine Rawls vs WDS data tables

---

service/src/main/java/org/databiosphere/workspacedataservice/config/DataImportProperties.java
service/src/main/resources/application-control-plane.yml
service/src/main/resources/application-data-plane.yml
service/src/main/resources/application.yml
service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesDataPlaneTest.java

This property was unused except in tests. Let's delete it.

AJ-1957: remove unused batch-write-record-sink property

---

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java
service/src/main/resources/static/swagger/openapi-docs.yaml
service/src/test/java/org/databiosphere/workspacedataservice/GeneratedClientTests.java
service/src/test/java/org/databiosphere/workspacedataservice/TestUtils.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/AllControllersPermissionsTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/ConcurrentDataTypeChangesTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvDownloadTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/TsvInputFormatsTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/NoCacheFilterTest.java
service/src/test/python/test.py

**Summary**
This PR removes the outdated v0.2 instance APIs from our swagger page. These APIs are deprecated, and we’ve moved to newer v1 Collection APIs.
**Changes**
- Deleted all v0.2 Instance API endpoints.
- Removed or updated tests related to v0.2 Instance APIs.
**Testing**
- Verified the system builds and passes all tests.
- Manually checked that no code still references the removed v0.2 Instance APIs.
**Next Steps**
- Monitor for any issues after deployment.
- Notify relevant teams about the change.
- Follow-up https://broadworkbench.atlassian.net/browse/AJ-1942

AJ-1943 Remove v0.2 Instance APIs

---

service/src/integrationTest/java/org/databiosphere/workspacedataservice/IntegrationServiceTestBase.java
service/src/integrationTest/java/org/databiosphere/workspacedataservice/service/BackupRestoreServiceFailureIntegrationTest.java
service/src/integrationTest/java/org/databiosphere/workspacedataservice/service/BackupServiceIntegrationTest.java
service/src/integrationTest/java/org/databiosphere/workspacedataservice/service/RestoreServiceIntegrationTest.java
service/src/integrationTest/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerCloneTest.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/CollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/BackupRestoreService.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDao.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java

More multi-tenancy changes in service of AJ-1971. This one removes the `CollectionDao.listCollectionSchemas()` method, which was not multi-tenant-safe.
I'll be removing `CollectionDao` piece by piece across a few PRs, to prevent any one PR from getting too big.

AJ-1971: remove CollectionDao.listCollectionSchemas()

---

service/src/integrationTest/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerCloneTest.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/CollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDao.java
service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
service/src/main/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBean.java
service/src/main/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerConfig.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerMockMvcTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDao.java
service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceGetWorkspaceIdTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceDataPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java

Deletes `CollectionDao.collectionSchemaExists()` and `CollectionDao. getWorkspaceId()`, as part of migrating fully to the multi-tenant CollectionRepository. Many unit test updates and some runtime changes to reflect these removals.
This PR has one Sonar warning, which I am ignoring; that code will be deleted shortly in the final follow-on PR, so I'm not bothering with it here.

AJ-1971: removing collection dao

---

.github/workflows/run-e2e-tests.yaml

https://broadworkbench.atlassian.net/browse/AJ-1994
This PR stops running the azure e2e tests on a regular schedule.  They can still be run as needed.

[AJ-1994] Turn off azure e2e tests

---

service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/jobexec/ImportJobUpdaterTest.java
service/src/test/java/org/databiosphere/workspacedataservice/jobexec/QuartzJobTest.java
service/src/test/java/org/databiosphere/workspacedataservice/leonardo/LeonardoDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/metrics/MetricsConfigTest.java
service/src/test/java/org/databiosphere/workspacedataservice/retry/RestClientRetryTest.java
service/src/test/java/org/databiosphere/workspacedataservice/retry/TransactionRetryTest.java
service/src/test/java/org/databiosphere/workspacedataservice/sam/BearerTokenFilterTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/DataTypeInfererTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/PermissionServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/PermissionsStatusServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceFilterQueryTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/RecordServiceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordRequestTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordResponseTest.java
service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordTest.java

This moves 20 unit tests from the data-plane profile to the control-plane profile. There are still ~45 tests in the data-plane profile; this is incremental progress.
Some tests required relatively minor setup/teardown changes; some required no changes at all other than the profile switch.

AJ-1981: some tests to the control plane

---

service/src/test/java/org/databiosphere/workspacedataservice/activitylog/AvailabilityTest.java
service/src/test/java/org/databiosphere/workspacedataservice/annotations/AnnotatedApisTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/GlobalExceptionHandlerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/controller/JobControllerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/PostgresJobDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dao/QuartzSchedulerDaoTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/FileDownloadHelperTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/ImportJobInputTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/ImportRequirementsFactoryTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbRecordConverterTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/snapshotsupport/SnapshotSupportTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/ParquetDataTypesTest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsModelTest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsource/JsonRecordSourceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsource/PfbRecordSourceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/recordsource/StreamingTest.java
service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvBatchTypeDetectionTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvDeserializerTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvErrorMessageTest.java
service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvJsonEquivalenceTest.java
service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java

Followup to #927.
This moves another 20 unit tests from the data-plane profile to the control-plane profile. There are still ~25 tests in the data-plane profile; this is incremental progress.
Some tests required relatively minor setup/teardown changes; some required no changes at all other than the profile switch.
The remaining tests will require the most attention, either because:
* they are actually testing data plane functionality and therefore we need to decide on keeping them or not
* they rely on controllers which are not yet enabled in the control plane

AJ-1981: continue moving tests to control-plane profile

---

service/build.gradle

Bumps spring-webmvc to address [security vulnerability](https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/98).  Can be removed once `spring-boot-starter-web`, which is what pulls in spring-webmvc, releases an update that includes the patch.
Reminder:
After you manually trigger the github …

AJ-1782 address security vulnerability

---

.github/workflows/release-python-client.yml
README.md
service/src/main/resources/application-bee.yml
service/src/main/resources/application-dev.yml
service/src/main/resources/application-local.yml
service/src/main/resources/application-prod.yml
service/src/main/resources/application-staging.yml

After https://github.com/DataBiosphere/terra-workspace-data-service/pull/774 we don't need the data repo url anymore; this PR removes its mention from the README and its use from `.yml` files.

AJ-2005 remove mention of datarepo url from readme

---

service/build.gradle

Some minor dependency cleanup:
* remove an obsolete comment
* remove the `constraint` on `spring-webmvc`, since the Spring Boot upgrade in #936 makes that constraint obsolete
* update to a recent version of `sam-client` and move to its "v"-based semantic versioning

AJ-1782: sam-client and spring-webmvc dependency cleanup

---

service/src/main/resources/swagger-ui-control-plane-preview.html
service/src/main/resources/swagger-ui-control-plane.html
service/src/main/resources/swagger-ui-data-plane.html

Basing these changes on https://github.com/DataBiosphere/terra-landing-zone-service/pull/502
This PR adds a `Content-Security-Policy` to swagger-ui via `<meta http-equiv …` tags.

AJ-2022: add Content-Security-Policy meta header for swagger-ui

---

.github/dependabot.yml

Dependabot automatically tags an associated ticket and the AJ team. The ticket was moved from AJ to CORE; this PR updates the ticket and which team is tagged on dependabot updates.

[CORE-69] Move dependabot updates from AJ to CORE

---

service/build.gradle

Updates java-pfb to 0.63.0. This version includes additional stack traces for debugging PFB import errors; see https://github.com/DataBiosphere/java-pfb/pull/82.
---
Reminder: …

CORE-208: update java-pfb library

---

.github/workflows/tag-and-publish.yml

The default Jira ticket for the tag-and-publish workflow was set to `AJ-####`, but as WDS is now managed by CORE, we can update that default to `CORE-####`
Reminder: …

[CORE-69] Default to CORE instead of AJ

---

service/src/main/resources/application-bee.yml
service/src/main/resources/application-data-plane.yml
service/src/main/resources/application-dev.yml

https://broadworkbench.atlassian.net/browse/CORE-301
Disable the data-table-specific APIs in the control plane. We had previously enabled these APIs in dev and bees only to enable pentests and security approval towards eventually migrating GCP/control-plane workspaces to WDS. That effort is on hold, so these APIs are only cluttering things.
Verified by running this PR version in a BEE that the APIs disappear from swagger-ui.

CORE-301: disable control-plane preview APIs

---

.github/workflows/build-and-test.yml
.github/workflows/publish-docker.yml
.github/workflows/tag-and-publish.yml

https://broadworkbench.atlassian.net/browse/CORE-302
Adjusts github actions so we stop publishing new docker images to ACR. We continue publishing to GCR, and the images already in ACR will stay there.

CORE-302: stop publishing docker images to ACR

---

service/src/main/resources/application-bee.yml
service/src/main/resources/application-dev.yml
service/src/main/resources/application-local.yml
service/src/main/resources/application-prod.yml

https://broadworkbench.atlassian.net/browse/CORE-335
As a followup to https://broadworkbench.atlassian.net/browse/CORE-264, this PR updates the WDS config to allow DRS URI resolution by adding valid hostnames for Sage BioNetworks:
- Prod: `repo-prod.prod.sagebase.org`
- Dev/BEE/Local: `repo-dev.dev.sagebase.org`
After …

[CORE-335] Add Sage BioNetworks Allowed DRS Hostnames

---

service/src/main/java/org/databiosphere/workspacedataservice/config/DataImportProperties.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidator.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportRequirements.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportRequirementsFactory.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/ProtectedDataSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/RawlsProtectedDataSupport.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsApi.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsClient.java
service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsWorkspaceDetails.java
service/src/main/resources/application.yml
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/DefaultImportValidatorTest.java
service/src/test/java/org/databiosphere/workspacedataservice/dataimport/protecteddatasupport/RawlsProtectedDataSupportTest.java
service/src/test/java/org/databiosphere/workspacedataservice/service/WorkspaceServiceControlPlaneTest.java
service/src/test/java/org/databiosphere/workspacedataservice/workspace/RawlsDataTableTypeInspectorTest.java

https://broadworkbench.atlassian.net/browse/CORE-454
Reminder: …

CORE-454 required auth domains

---

service/src/main/resources/application.yml

https://broadworkbench.atlassian.net/browse/CORE-482
Reminder: …

protect pic-sure imports

---

.github/dependabot.yml
README.md
build.gradle
client/build.gradle
service/build.gradle
settings.gradle

Jira ticket: https://broadworkbench.atlassian.net/browse/DDO-4107
**Summary of changes**
Updated the artifact source for this service to read artifacts from Google Artifact Registry instead of JFrog.
**What**
Modified the config to pull artifacts from GAR. No publishing changes were made.
**Why**
This is part of Phase 2 of the artifact migration effort to deprecated JFrog and consolidate artifacts in GAR.
**Testing these changes**
Relied on passing CI checks and tests. Artifact reading-related issues are expected to surface as pipeline failures. For example these jobs [here](https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/15309876591/job/43071753325?pr=222) and [here](https://github.com/DataBiosphere/leonardo/actions/runs/15324072477/job/43114134405?pr=4858 …

DDO-4131 read from google artifact registry

---

service/build.gradle

Ticket: https://broadworkbench.atlassian.net/browse/CORE-539
We have to upgrade `commons-beanutils` to `1.11.0` which a dependency for `org.apache.hadoop:hadoop-common:3.4.1`
because of [CVE-2025-48734](https://nvd.nist.gov/vuln/detail/cve-2025-48734)
---
If you make changes to the github actions or workflows, particularly when they are run or which other workflows they call, please update [the GHA wiki page](https://github.com/DataBiosphere/terra-workspace-data-service/wiki/GHA-structure-in-WDS) to stay up to date.

[CORE-539] Upgrade commons-beanutils to 1.11.0

---

service/build.gradle

CORE-69: bump tomcat-embed-core

---

service/src/main/resources/application.yml

CORE-577
Imports from AnVIL Data Explorer now add the "federal_data_lockdown" auth domain.
We may be removing this functionality in the future if/when we have more precise knowledge about the auth domains for individual imports.
For previous art, see:
* https://github.com/DataBiosphere/terra-workspace-data-service/pull/1013
* https://github.com/DataBiosphere/terra-workspace-data-service/pull/1011

CORE-577: AnVIL Data Explorer PFB imports get federal_data_lockdown

---

.github/workflows/build-test-tag-and-publish.yml

Found during CORE-551; does not compete that ticket.
Some merges to main are not getting deployed to dev. In my recent PRs this is happening because the workflow that should release cWDS gets canceled. It created a new release tag and then went on to deploy ... but other workflows kicked off on the tag and canceled the deploy.
This PR adjusts the GHA workflow concurrency such that it will not cancel workflows on pushes to main.

CORE-551: dont cancel github actions for pushes to main

---

service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsClientConfig.java
service/src/main/resources/application.yml

Every so often we see timeouts in the Terra UI integration tests, which run in the staging environment. These tests hit a 10-second timeout.
The actual Rawls APIs being called DO succeed - but they take longer than 10 seconds. Thanks to the additional logging in https://github.com/broadinstitute/rawls/pull/3387, I can see that in the last 5 instances of this timeout, it was the step to add a group to an auth domain that eats up the majority of the time.
This PR increases the timeout for the Rawls REST client to see if that helps with the test failures. I've changed the timeouts for all environments because it seems like a good idea anyway, but since it is driven from config we could have different timeouts for each environment if we wanted to.
---
This reimplements #1032, which was …

CORE-551: set longer timeouts for Rawls REST client

---

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbRecordConverter.java
service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/PfbParsingException.java

CORE-692
If WDS cannot find an id or recordType when parsing a PFB, we now output a much more helpful error message.

CORE-692: more helpful error messages in PFB parsing failure
