README.md, local-dev/run_postgres.sh
I have verified the Mac instructions work for me on my system; I haven't tested the Linux invocation!
=> readme and postgres updates for running dockerized wds

.github/workflows/tag-and-publish.yml
=> another test

.github/workflows/tag-and-publish.yml
=> remove initial version

.github/workflows/tag-and-publish.yml
=> test tagging

.github/workflows/tag.yml
=> need to re-test

.github/workflows/publish.yml
=> re-build to get new tag

.github/workflows/publish.yml
=> checks not running?

.github/workflows/publish.yml
=> push on tags

.github/workflows/publish.yml
=> on-create-tag

service/src/main/java/org/databiosphere/workspacedataservice/controller/EntityController.java, service/src/main/resources/static/swagger/openapi-docs.yaml
[AJ-515](https://broadworkbench.atlassian.net/browse/AJ-515)
Adds an api to create an instance (schema).
Questions: what should the URI be?  Do we need tests?  Is it worth looking out for any collisions?
=> aj-515 create instance api

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, build.gradle, service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java, service/src/main/java/org/databiosphere/workspacedataservice/controller/EntityController.java, service/src/main/java/org/databiosphere/workspacedataservice/dao/EntityDao.java, service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java, service/src/main/java/org/databiosphere/workspacedataservice/service/RefUtils.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/AttemptToUpsertDeletedEntity.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/DataTypeMapping.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/EntityReference.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/EntitySystemColumn.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/InvalidEntityReference.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/MissingReferencedTableException.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/Entity.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/EntityAttributes.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/EntityId.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/EntityMetadata.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/EntityRequest.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/EntityResponse.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/EntityType.java, service/src/test/java/org/databiosphere/workspacedataservice/DataTypeInfererTest.java, service/src/test/java/org/databiosphere/workspacedataservice/controller/EntityControllerMockMvcTest.java, service/src/test/java/org/databiosphere/workspacedataservice/dao/EntityDaoTest.java, service/src/test/java/org/databiosphere/workspacedataservice/shared/model/EntityRequestTest.java, service/src/test/java/org/databiosphere/workspacedataservice/shared/model/EntityResponseTest.java
The first commit has the changes to `build.gradle` which turns on Spotless and enables `spotlessApply` on build. Recommend ignoring whitespace while viewing that.
The second commit is the result of `./gradlew spotlessApply` and should have no functional changes, just formatting.
=> apply spotless [AJ-470]

service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java, service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java, service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java, service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java, service/src/main/java/org/databiosphere/workspacedataservice/service/RelationUtils.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/DataTypeMapping.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/InvalidRelation.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/MissingReferencedTableException.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/Relation.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/SystemColumn.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/Record.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributes.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordId.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordMetadata.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordRequest.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordResponse.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordType.java, service/src/test/java/org/databiosphere/workspacedataservice/DataTypeInfererTest.java, service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java, service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java, service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordRequestTest.java, service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordResponseTest.java
apply spotless, now that we're using the eclipse formatter.
=> spotlessApply [AJ-470]

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java, service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/AttributeSchema.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/RecordTypeSchema.java, service/src/main/resources/static/swagger/openapi-docs.yaml, service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java, service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
Adds API to describe the schema of a recordType.
=> AJ-517 first pass describeRecordType

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java, service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java, service/src/main/java/org/databiosphere/workspacedataservice/service/model/exception/InvalidNameException.java, service/src/main/resources/static/swagger/openapi-docs.yaml, service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java, service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java, service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
[AJ-574](https://broadworkbench.atlassian.net/browse/AJ-574)
Adds an API to delete record type
=> Aj 574 delete record type

service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java, service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java, service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordQueryResponse.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/SearchRequest.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/SearchResponse.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/SortDirection.java, service/src/main/resources/static/swagger/openapi-docs.yaml, service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
I moved everything under POST.  I think things are ok and fairly consistent swagger-wise, but check me there.  I wasn't totally sure what to include in the response payload so feel free to make suggestions if I'm missing things there.
=> AJ-575: Simple Paginated Results (limit, offset, sort direction)

service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
=> default for BatchWriteService

service/src/main/java/org/databiosphere/workspacedataservice/WorkspaceDataServiceApplication.java
By default, only GET, HEAD, POST is allowed for CORS. This PR changes to allow DELETE, GET, HEAD, PATCH, POST, PUT.
=> enable more http methods for CORS [AJ-632]

service/src/test/java/org/databiosphere/workspacedataservice/controller/CorsMockMvcTest.java
follow-on to #94 … this adds a unit test to verify CORS config.
=> unit test for CORS config [AJ-632]

.github/workflows/publish-docker.yml
[AJ-637](https://broadworkbench.atlassian.net/browse/AJ-637)
Automatically updates cromwhelm when a new WDS image is created.
=> AJ-637 auto-update cromwhelm

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java, service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java, service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java, service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java, service/src/test/java/org/databiosphere/workspacedataservice/DataTypeInfererTest.java, service/src/test/java/org/databiosphere/workspacedataservice/TestUtils.java, service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java, service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java
In addition to what's referenced in the jira ticket, I took the opportunity to improve some of our tests and to ensure that we're reading and writing data as expected.
=> AJ-640: Fix for writing JSON objects to jsonb

README.md, build.gradle
Removes spotless from the build process.
=> remove spotless [AJ-673]

service/src/main/resources/logback-spring.xml
- add dev profile and don't log when it's active
- change profile name to local
=> AJ-723: Make it possible to turn off logback file logging.

.github/workflows/build-and-test.yml, .github/workflows/publish-docker.yml, .github/workflows/publish-java-client.yml, .github/workflows/release-python-client.yml, .github/workflows/tag.yml
- ready to test
- AJ-55: this is merely a test
- create new branch fix up warnings
- AJ-99: just a test
- AJ-99: just another test
[AJ-99]: https://broadworkbench.atlassian.net/browse/AJ-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AJ-99]: https://broadworkbench.atlassian.net/browse/AJ-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AJ-719: Create PRs in Cromwhelm with automerge label

service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java, service/src/test/java/org/databiosphere/workspacedataservice/SentryInitializerTest.java
regex-based environment parsing for #163 163
=> sam url parsing

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java, service/src/main/java/org/databiosphere/workspacedataservice/service/InstanceService.java, service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java, service/src/main/java/org/databiosphere/workspacedataservice/service/RecordUtils.java, service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceTest.java, service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java
Changes:
- business logic is migrated from the RecordController to the RecordOrchestratorService
- transactions are moved down into the business logic service
- testing for recordController business logic
=> [AJ-497] refactor transactions

service/src/main/resources/static/swagger/openapi-docs.yaml
since they are currently being generated into python client and always return 404s. 
more details [here](https://broadworkbench.atlassian.net/browse/AJ-882).
=> AJ 882 - Remove WDS Apis marked as deprecated

service/build.gradle
addresses [NVD - CVE-2023-1370](https://nvd.nist.gov/vuln/detail/CVE-2023-1370) in json-smart
=> AJ-922: update azure-identity, which updates json-smart

.github/workflows/build-and-test.yml, .github/workflows/publish-docker.yml, .github/workflows/release-python-client.yml, .github/workflows/tag.yml
See [AJ-762](https://broadworkbench.atlassian.net/browse/AJ-762)
This PR updates the version of actions/cache to address deprecation of set-output and save-state.
[AJ-762]: https://broadworkbench.atlassian.net/browse/AJ-762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AJ-762 address set-output and save-state deprecation warnings

README.md, service/build.gradle, service/src/main/java/org/databiosphere/workspacedataservice/controller/DataRepoController.java, service/src/main/java/org/databiosphere/workspacedataservice/datarepo/DataRepoDao.java, service/src/main/java/org/databiosphere/workspacedataservice/datarepo/DataRepoException.java, service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/HttpWorkspaceManagerClientFactory.java, service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerClientFactory.java, service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerConfig.java, service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDao.java, service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerException.java, service/src/main/resources/application.properties, service/src/test/java/org/databiosphere/workspacedataservice/controller/DataRepoControllerMockMvcTest.java, service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoDaoTest.java, service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. 
After your manually trigger the github action (and it completes with no errors), you must go to [this](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that merged succesfully.
The terra-helmfile PR merge will then generate a PR in https://github.com/DataBiosphere/leonardo.  This may or may not automerge; be sure to watch it to ensure it merges.
=> AJ-1009 create snapshot ref on import

README.md, docs/WDS Running Python tests locally.md
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. 
After your manually trigger the github action (and it completes with no errors), you must go to [this](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that merged succesfully.
The terra-helmfile PR merge will then generate a PR in https://github.com/DataBiosphere/leonardo.  This may or may not automerge; be sure to watch it to ensure it merges.
=> Aj 1070 - Add instructions on how to run python tests locally

.github/release-drafter-config.yml
Add some info to the top of our draft releases. Still experimenting with these auto-created releases.
=> AJ-1063: update release-drafter template

service/src/main/resources/application.properties
https://broadworkbench.atlassian.net/browse/AJ-1115
I missed an ampersand before `additionalUrlParams`
=> AJ-1115 missing & in url

docs/WDS Python Client.md
https://broadworkbench.atlassian.net/jira/software/c/projects/AJ/boards/124?modal=detail&selectedIssue=AJ-1126
Reminder:
After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that …
=> AJ-1126: Adjust logic to get wds endpoint url in python doc

service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilder.java, service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityModels.java, service/src/main/java/org/databiosphere/workspacedataservice/service/BackupRestoreService.java
Activity logging (aka audit logging) for backup and restore.
If either the backup or restore code paths change, we may need to update the activity logging.
=> AJ-1146: activity logging for backup/restore

README.md
Update the readme to reference the `LEONARDO_URL` env var.
=> AJ-961: include LEONARDO_URL in readme for local dev

service/src/main/java/org/databiosphere/workspacedataservice/storage/AzureBlobStorage.java
When uploading to Azure blob storage, use a buffer for writes.
This is the recommended approach, per Azure documentation: https://learn.microsoft.com/en-us/java/api/com.azure.storage.blob.specialized.blockblobclient?view=azure-java-stable#com-azure-storage-blob-specialized-blockblobclient-getbloboutputstream():
> Note: We recommend you call write with reasonably sized buffers, you can do so by wrapping the BlobOutputStream obtained below with a [BufferedOutputStream](https://docs.oracle.com/javase/8/docs/api/java/io/BufferedOutputStream.html).
I added some custom logging to my locally-running WDS and called the backup API.
After this PR:
```
2023-07-21 08:23:21.091 DEBUG [3GqOoze1] [http-nio-8080-exec-3] o.d.w.w.WorkspaceManagerDao              : Finding storage resource for workspace …
```
=> AJ-1181: buffer writes to blob storage

service/build.gradle, service/src/main/java/org/databiosphere/workspacedataservice/leonardo/HttpLeonardoClientFactory.java, service/src/main/java/org/databiosphere/workspacedataservice/leonardo/LeonardoClientFactory.java, service/src/test/java/org/databiosphere/workspacedataservice/leonardo/LeonardoDaoTest.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-10682
Reminder: …
=> RW-10682 Update leo client

service/build.gradle
https://precisionmedicineinitiative.atlassian.net/browse/RW-10774
Reminder: …
=> RW-10774 Update leo client

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/TdrSnapshotSupport.java, service/src/test/java/org/databiosphere/workspacedataservice/pact/TdrPactTest.java, service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java
[AJ-1451](https://broadworkbench.atlassian.net/browse/AJ-1451)
Add additional contract coverage to `WsmPactTest` to cover interactions with `workspacemanager`.
[AJ-1451]: https://broadworkbench.atlassian.net/browse/AJ-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AJ-1451: More pacts with workspacemanager

.github/workflows/build-and-integration-test.yml, .github/workflows/build-and-test.yml, .github/workflows/publish-docker.yml, .github/workflows/publish-java-client.yml, .github/workflows/publish-pacts.yml, .github/workflows/release-python-client.yml, .github/workflows/run-e2e-tests.yaml, .github/workflows/submit-dependencies.yml, .github/workflows/tag.yml
Update `checkout`, `setup-java`, `setup-node` , `upload-artifact`, `download-artifact`github actions to latest versions.
Auto-formatter also fixed some whitespace issues.
=> AJ-1428: update various actions to latest

service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java
This includes a couple fixes that I discovered while working on the provider side of this contract.
These bugs are a reminder why it's helpful to complete the provider tests in lockstep with the consumer tests!
=> AJ-1451: Fix pact provider state

service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java
This adds additional pacts to cover the various WDS <-> WSM interactions that happen via the `WorkspaceManagerDao`.
It is paired with provider changes in https://github.com/DataBiosphere/terra-workspace-manager/pull/1528
=> AJ-1451: Add additional pacts for WSM

service/build.gradle
Updates our Azure dependencies to latest versions.
=> AJ-1463: update Azure libraries to latest

build.gradle, service/build.gradle
Maintenance ticket: [AJ-1485](https://broadworkbench.atlassian.net/browse/AJ-1485)
For dependabot findings:
* https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/46
* https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/47
[AJ-1485]: https://broadworkbench.atlassian.net/browse/AJ-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump `logback` version to 1.2.13+

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/FileDownloadHelper.java
Honestly I stumbled into the actual implementation here because Intellij kept providing suggestions that made my code terser and terser.
But the idea here is that I just added a constructor overload that takes a `DownloadHelper`, and the default constructor just wraps the method that you're currently using.
The extra constructor provides a way for you to provide your own `DownloadHelper` in a test case, which can just be a mock set up to fail once and succeed subsequently (for example).
=> Add DownloadHelper seam for test override.

service/build.gradle, service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java, service/src/main/resources/liquibase/changelog.yaml, service/src/main/resources/liquibase/changesets/20240118_number_timestamp_array_conversions.yaml, service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java
Stacked on #471. This adds support for date and date time types.
=> [AJ-1279] Add support for date and date time data type conversions 

service/build.gradle, service/src/main/resources/application-bee.yml, service/src/main/resources/application-local-promprox.yml, service/src/main/resources/application.yml
Ticket [AJ-1548](https://broadworkbench.atlassian.net/browse/AJ-1548)
* Enabled in bees
* Disabled everywhere else
* Can be enabled locally with spring-profile `local-promprox`
[AJ-1548]: https://broadworkbench.atlassian.net/browse/AJ-1548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AJ-1548: Connect to prometheus rsocket proxy

service/src/main/java/org/databiosphere/workspacedataservice/controller/RecordController.java, service/src/main/resources/static/swagger/openapi-docs.yaml, service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
Expose the update attribute data type API from #471 and #472 through the HTTP API.
=> [AJ-1279] Expose update attribute data type API

service/build.gradle, service/src/main/resources/logback-spring.xml
https://broadworkbench.atlassian.net/browse/AJ-1594
Configures logging to output in JSON format, which is required for control plane services, only in the case that the property `deploymentMode` is `control-plane`.  Otherwise keeps the non-JSON format.
Without JSON:
(local)
(in Azure portal)
With JSON:
(local)
(in Azure portal)
Reminder:
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided the action will not fully …
=> AJ-1594 convert logging to json

service/src/test/java/org/databiosphere/workspacedataservice/annotations/DeploymentModeTest.java
Prefactor for [AJ-1563](https://broadworkbench.atlassian.net/browse/AJ-1563)
Reduces friction for adding new conditional beans to the test suite.
Now simply add a new `Arguments` instance to the `conditionalBeans()` return value to test that the bean is only enabled for the specified `DeploymentMode`.
[AJ-1563]: https://broadworkbench.atlassian.net/browse/AJ-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AJ-1563 Generalize `DeploymentModeTest.java`

service/src/test/java/org/databiosphere/workspacedataservice/controller/FullStackRecordControllerTest.java
Maintenance/cleanup. Eliminates this error:
```
Note: .../path/to/FullStackRecordControllerTest.java uses unchecked or unsafe operations.
```
=> AJ-1556 Fix null safety warnings.

service/build.gradle
Updates an arbitrary handful of dependencies, with a goal of reducing the quantity of outstanding Dependabot updates. I am not trying to address ALL of the Dependabot updates.
=> AJ-1556: dep updates

client/build.gradle, client/swagger.gradle, service/build.gradle
For general maintenance: [AJ-1649](https://broadworkbench.atlassian.net/browse/AJ-1649)
Fixes up some warnings and also fixes an issue with IDE configuration.
[AJ-1649]: https://broadworkbench.atlassian.net/browse/AJ-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AJ-1649 Gradle fixup and maintenance.

service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesDataPlaneTest.java, service/src/test/java/org/databiosphere/workspacedataservice/jobexec/QuartzJobTest.java, service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java, service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceControlPlaneTest.java, service/src/test/java/org/databiosphere/workspacedataservice/service/RecordServiceTest.java, service/src/test/java/org/databiosphere/workspacedataservice/storage/GcsStorageTest.java
add `@DirtiesContext` to some more tests where it is needed
=> AJ-1649: add @DirtiesContext to more tests

.github/workflows/publish-app-version.yml, .github/workflows/publish-docker.yml
https://broadworkbench.atlassian.net/browse/AJ-1666
Before this PR:
The `publish-docker` workflow:
1. requires the input `input-tag`
2. is only called by the `tag` workflow
3. tags the new docker image with both the `input-tag` sent from `tag` and the github short hash.
The `tag` workflow, which is called manually for release:
1. discovers the new semver tag (e.g. 0.2.117)
2. passes the new tag to the `publish-docker` workflow
4. passes the new tag to sherlock to report the existence of the new docker image.
After this PR:
The `publish-docker` workflow:
1. does not require the input `input-tag`
2. is called both by the `tag` workflow and upon PR
3. If `input-tag` is present:
-  tags the new docker image with both the semver `input-tag` sent from `tag` and the github short hash
- reports …
=> AJ-1666 Report PR images to sherlock

service/build.gradle
[AJ-1681](https://broadworkbench.atlassian.net/browse/AJ-1681): Bundle of multiple dependabot bumps:
* https://github.com/DataBiosphere/terra-workspace-data-service/pull/635
* https://github.com/DataBiosphere/terra-workspace-data-service/pull/637
* https://github.com/DataBiosphere/terra-workspace-data-service/pull/638
* https://github.com/DataBiosphere/terra-workspace-data-service/pull/639
* https://github.com/DataBiosphere/terra-workspace-data-service/pull/640
[AJ-1681]: https://broadworkbench.atlassian.net/browse/AJ-1681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AJ-1681: Dependabot updates.

service/src/main/resources/application-prod.yml, service/src/main/resources/application.yml
Configure allowed import sources to match import-service.
https://github.com/broadinstitute/import-service/blob/a818658d0850818804235c5dc7f239c0de95c8cf/app.yaml.ctmpl#L69
=> [AJ-1588] Configure allowed import sources

smoke_test/tests/authenticated/cwds_job_listing_tests.py
The docstring for one smoke test was incorrect; this fixes it
=> AJ-1573: fix docstring for one smoke test

service/src/test/java/org/databiosphere/workspacedataservice/pact/RawlsPactTest.java
This is just to show how to use the newer Pact DSL to get an equivalent pact file.
Verified equivalence by diffing contents of service/build/pacts-wds-rawls.json before and after.
=> Aj 1697 Demonstrate newer pact DSL

.github/actions/create-bee/action.yml
Reverts DataBiosphere/terra-workspace-data-service#706
Reacted too eagerly; this won't be needed until devops adds their changes next week (expected 4/16, I think)
=> Revert "AJ-1743 Update bee-create"

service/src/main/java/org/databiosphere/workspacedataservice/retry/RestClientRetry.java, service/src/test/java/org/databiosphere/workspacedataservice/retry/RestClientRetryTest.java
When a request is retried, the `retryAttempt` label will be added to the `wds.outbound` metric.  The initial attempt is not labeled.
=> AJ-1515: Record `retryAttempt`

README.md
The PubSub topic has been moved out of the import service project.
=> [AJ-1677] Update readme with new PubSub config

service/src/main/java/org/databiosphere/workspacedataservice/dataimport/FileDownloadHelper.java, service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java, service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
AJ-1837
This PR enhances logging for snapshot imports. As I was debugging problems with import, I found the logs lacking in a few places. This beefs them up!
There should be no functional changes at all; only changes to logging.
_reviewer: ignore whitespace!_
=> AJ-1837: improved logging for snapshot import

service/src/main/java/org/databiosphere/workspacedataservice/service/NoCacheFilter.java
https://broadworkbench.atlassian.net/browse/AJ-1787
Small fixup to #779 based on review of https://github.com/DataBiosphere/terra-java-project-template/pull/30.
=> [AJ-1787] Use Spring constant for header names

service/src/integrationTest/java/org/databiosphere/workspacedataservice/IntegrationServiceTestBase.java, service/src/main/java/org/databiosphere/workspacedataservice/dao/CollectionDao.java, service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDao.java, service/src/main/java/org/databiosphere/workspacedataservice/service/BackupRestoreService.java, service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java, service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerSearchFilterTest.java, service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDao.java, service/src/test/java/org/databiosphere/workspacedataservice/dao/PostgresCollectionDaoTest.java, service/src/test/java/org/databiosphere/workspacedataservice/dao/RecordDaoTest.java, service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoDaoTest.java, service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java, service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamExceptionTest.java, service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceTest.java, service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorSamTest.java, service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java, service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java, service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvBatchTypeDetectionTest.java
Change signatures of `CollectionDao#dropSchema` and `CollectionDao#alterSchema` to use `CollectionId` instead of `UUID`.
=> AJ-1658: Prefer `CollectionId`

README.md
Does a README update need a Jira ticket for compliance? or is this fine?
=> [AJ-1934] add Troubleshooting section to README

service/src/main/java/org/databiosphere/workspacedataservice/controller/CollectionController.java, service/src/main/java/org/databiosphere/workspacedataservice/dao/CollectionRepository.java, service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java, service/src/main/java/org/databiosphere/workspacedataservice/shared/model/WdsCollection.java, service/src/test/java/org/databiosphere/workspacedataservice/controller/CollectionControllerMockMvcTest.java
Implement the get-collection v1 API.
Out of scope, saving for a future PR: the update-collection v1 API
=> AJ-1924: get-collection v1 API

service/build.gradle
Addresses https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/95
Reminder:
After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that …
=> [AJ-1782] Address dnsjava vulnerability

build.gradle, service/build.gradle
Updates the `jib` and `pact` gradle plugins to latest.
=> AJ-1782: update jib, pact gradle plugins

service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java, service/src/test/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorServiceTest.java
Reminder:
The terra-helmfile PR merge will then generate a PR in …
=> [AJ-1955] add wds.searchRequest.includesFilter observation

service/src/test/java/org/databiosphere/workspacedataservice/GeneratedClientTests.java
@kevinmarete A PR into your branch, not into main. `GeneratedClientTests` is passing for me after these changes. See comments inline for explanation. Feel free to merge into your branch at will.
=> suggested fixes

service/src/main/java/org/databiosphere/workspacedataservice/controller/CloningController.java, service/src/main/java/org/databiosphere/workspacedataservice/service/PermissionService.java
After this PR, WDS will have no deprecated methods!
=> AJ-1942: remove deprecated PermissionService methods

.github/workflows/publish-app-version.yml
Turn off releasing into the data plane.
=> AJ-1991: disable terra-helmfile releases

service/src/main/resources/application.yml
This turns off connectivity validation for imports.
=> CORE-208: disable import connectivity checker

service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsWorkspaceDetails.java
https://broadworkbench.atlassian.net/browse/CORE-454
Reminder: …
=> CORE-454 missing params

service/src/main/java/org/databiosphere/workspacedataservice/rawls/RawlsClientConfig.java, service/src/main/resources/application.yml
Reverts DataBiosphere/terra-workspace-data-service#1032
=> Revert "CORE-551: set longer timeouts for Rawls REST client"
